### ISSUE TITLE
Please mention react-admin 

### ISSUE THREAD

**Issue by fzaninotto** [pankod/refine#1119]
Hi, and kudos for the great work.

I'm the maintainer of react-admin, a framework that you seem to have used as base for software architecture, naming, and sometimes even your own code. React-admin is MIT so it's fine to see it forked, and you have implemented new features that could inspire us to catch up on certain subjects. 

But I'd appreciate to see in the readme and public website that this framework takes react-admin as an inspiration. You don't have to, but I think it's basic courtesy in the open-source community. 

One thing you must do, however, is to include the react-admin MIT licence in the packages you've forked. Here is an extract from react-admin's licence:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

And if you want to push things forward in the react-admin landscape, I can only invite you to collaborate on react-admin. Your contributions will have a much bigger impact on an established framework with thousands of apps already running in production. 

Cheers,

François

**Comment by omeraplak** [comment]
Hi @fzaninotto,

Thank you very much for your kind words and the friendly reminder about the reference to the React Admin project.

We added a "Special Thanks" section to GitHub project page and website to show our appreciation to React Admin. This was something we definitely wanted to include and missed to do in the launch rush :(

Besides ideas and inspiration, refine also shares some concepts and approaches with React Admin. But from a software development perspective, it's a totally distinct project with different architectural choices and different stacks.

It's developed from scratch and shares no single line of code with React Admin. refine includes no forks, modules, or components from React Admin project. Given the situation, we see no reason for a copyright statement or inclusion of an MIT license. 

If any copyrighted/licensed source code from your project is included in refine and you point this out, we'll be very happy to include all the necessary licenses and attributions. Please don't hesitate to reach us if you think this is the case.

Best regards,
Omer
