### ISSUE TITLE
[BUG] Vite unable to resolve package - incorrect module exports

### ISSUE THREAD

**Issue by shawngoh87** [pankod/refine#1122]
**Describe the bug**
Vite is unable to resolve the package.

**To Reproduce**
1. Install @pankod/refine and vite
2. Import any component anywhere
3. Run `vite`
4. Sample error:
```node_modules/vite/dist/node/chunks/dep-36bf480c.js:43807:10: error: [plugin: vite:dep-scan] Failed to resolve entry for package "@pankod/refine". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@pankod/refine". The package may have incorrect main/module/exports specified in its package.json```

**Expected behavior**
`vite` should serve the site

**Desktop (please complete the following information):**
 - MacOS Catalina
 - Safari
 - Refine v1.0.78
 - No dataProvider

**Comment by omeraplak** [comment]
Hi @shawngoh87 ,
We've released 1.0.79! Thank you for your contribution!

**Comment by shawngoh87** [comment]
Awesome. Thanks for the quick release!
