### ISSUE TITLE
Supabase keys exposed

### ISSUE THREAD

**Issue by GiovanniSM20** [pankod/refine#1124]
I was taking a look at the library and I ended up finding this reference to the supabase key, should this be [here](https://github.com/pankod/refine/blob/ab29a28d81eb453e68a7cab097e49639818ad549/examples/dataProvider/supabase/src/utility/supabaseClient.ts) ?

**Comment by omeraplak** [comment]
Hi @GiovanniSM20 ,
Thank you for the warning, but we left it on purpose. We want people to try supabase integration easily. We do not have any specific information on it. We also trust community a lot
