### ISSUE TITLE
[FEAT] Provide a way to customize react-query devtools options

### ISSUE THREAD

**Issue by tavrez** [pankod/refine#1197]
We need a way to provide options into react-query devtools, like changing it's location or using auto open on it.

**Comment by necatiozmen** [comment]
Hi @tavrez
We have added customization ability to React Query Devtools. You'll be updated when the new release is pushed. Thanks for your useful advice.

**Comment by omeraplak** [comment]
Hi @tavrez ,
We've released 1.0.93
https://github.com/pankod/refine/releases/tag/1.0.93
