### ISSUE TITLE
[FEAT] default operators for filterDropdown

### ISSUE THREAD

**Issue by Beerwerd** [pankod/refine#1199]
**Is your feature request related to a problem? Please describe.**
I cant set up default operator (for example `conditions`) for filterDropdown
By default it filters by `eq` if it simple value or `in` if array. Operator could be changed by setting up `initialFilter` or `permanentFilter`, in this case filter would be use operator from initial condition. 

**Describe the solution you'd like**
I want to be available to config operators for filterDropdown without requires to set initialFilter

**Describe alternatives you've considered**
Currently I can do it by rewriting `useTable` hook and add  extra code after mapping tableFilter after line
https://github.com/pankod/refine/blob/c2698dc06ad52a50743d26696e4175c8a45e5d3e/packages/core/src/hooks/table/useTable/useTable.ts#L193

```javascript
// Map Antd:Filter -> refine:CrudFilter
    let crudFilters = mapAntdFilterToCrudFilter(tableFilters, filters);

    if (filterConfig) {  //-------> HERE 
      crudFilters = wrapFilterConfig<TData>(crudFilters, filterConfig);
    }

    setFilters((prevFilters) =>
      unionFilters(permanentFilter, crudFilters, prevFilters),
    );

```
and add config on initial `useTable` hook

```typescript
const { tableProps, sorter, filters } = useTable<IPost>({
    filterConfig: {
      title: {
        operator: 'contains',
      },
    },
  });
```

here I change operators on which I would want

Maybe there is better way to change filter operator for filterDropdown and I missed it

**Comment by Beerwerd** [comment]
I have find solution for my case: I can pass `initialFilter` with undefined value and `useTable` will be use operator from `initialFilter`

**Comment by omeraplak** [comment]
> I have find solution for my case: I can pass `initialFilter` with undefined value and `useTable` will be use operator from `initialFilter`

It's great that it works this way. This is how we will update our documents.  Congratulations!
