### ISSUE TITLE
[BUG] An Error thrown from useNavigation Hook

### ISSUE THREAD

**Issue by rturan29** [pankod/refine#1211]
**Describe the bug**
In useEffect at app.tsx I tried to use the push method of useNavigation. But an error is thrown from useNavigationHook "Cannot read properties of undefined (reading 'push')".

**To Reproduce**
In app.tsx create an useEffect and try to push an route with useNavigation.

**Expected behavior**
"Cannot read properties of undefined (reading 'push')" error will thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/81697915/140386526-d48582b8-197d-4057-b88c-fd68f80a1536.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 1.0.92
 - Used dataProvider Firebase

**Additional context**

**Comment by omeraplak** [comment]
Hey @rturan29 ,
Not the right place to use refine hooks in `App.tsx`. Because it is out of the scope of `<Refine>` component. You can use refine hooks inside the app.
