### ISSUE TITLE
The operator property in initialFilter is always required

### ISSUE THREAD

**Issue by hectoryx** [pankod/refine#1273]
**Describe the bug**
When using filters in initialFilter the operator property is mandatory and does not have the option to be omitted.

**To Reproduce**
1.- Create a useTable
2.- Assign object initialFilter 
3.- Add object { field: "modelField", value: "value"}
4.- We get an error: "The property 'operator' is missing in the type '{ field: string; value: string; }' but it is necessary in the type 'CrudFilter'".

**Expected behavior**
The operator property could be optional and not add extra arguments to the url

**Comment by omeraplak** [comment]
Hey @hectoryx ,
We've released **@pankod/refine-strapi@2.3.2** and **@pankod/refine-strapi-graphql@2.3.2**. Could you approve this fix?

In short, instead of making the operator null, we prevented the eq filter from using a suffix.
