### ISSUE TITLE
[FEAT] Strapi v4 Integration

### ISSUE THREAD

**Issue by Saad-ISAA** [pankod/refine#1274]
Strapi v4 is released today. The API responses are different from the v3 of strapi, so it will impact the integration.

There should be either a new plugin for v4 of strapi, or an upgrade to the previous one. separate one makes sense coz there will be many who wont be migrating to v4.
Mongo DB users will not migrate to v4, coz mongo is no longer supported in v4

**Comment by omeraplak** [comment]
Hey @Saad-ISAA ,
Thanks for sharing Strapi v4 details. It will come in handy when adding v4 support. Let's see what we will do

**Comment by ch3ckmat3** [comment]
+1 for Strapi v4 🚀

A new DataProvider for Strapi v4 will be a better approach.

**Comment by omeraplak** [comment]
Hey,
We've released `@pankod/refine-strapi-v4` package!

**Comment by ch3ckmat3** [comment]
Perfect! Great job guys! 👌💪🚀
