### ISSUE TITLE
[BUG] Unable to deploy finefoods admin example to both Heroku and Netlify

### ISSUE THREAD

**Issue by niwasmala** [pankod/refine#1276]
**Describe the bug**
I don't know if this bug or some configuration needed. I'm unable to deploy the example of finefoods admin on both Heroku and Netlify. Both stopped on build step. But when I try to build on local laptop, it compiled successfully.

**To Reproduce**
1. Create new heroku or netlify project
2. Copy example/finefoods/admin 
3. Deploy

**Expected behavior**
Deploy run smoothly and application can be accessed.

**Screenshots**
![image](https://user-images.githubusercontent.com/476869/144041334-49fb560a-3fbc-4558-9c0e-4ec37c87c643.png)

![image](https://user-images.githubusercontent.com/476869/144041221-f8dd305f-2771-48a2-a9c8-d23a22f62445.png)

Deploy log
```
6:24:14 PM: yarn run v1.22.10
6:24:14 PM: $ craco build
6:24:16 PM: Creating an optimized production build...
6:28:56 PM: Failed to compile.
6:28:56 PM: 
6:28:56 PM: src/components/dashboard/recentOrders/index.tsx
6:28:56 PM:   Line 49:26:  Parsing error: Unexpected token
6:28:56 PM:   47 |             showHeader={false}
6:28:56 PM:   48 |         >
6:28:56 PM: > 49 |             <Table.Column<IOrder>
6:28:56 PM:      |                          ^
6:28:56 PM:   50 |                 key="avatar"
6:28:56 PM:   51 |                 render={(_, record) => (
6:28:56 PM:   52 |                     <Avatar
```

**Heroku:**
 - Node Version: 14.18.1
 - Yarn Version: v1.22.17

**Netlify:**
 - Node Version: 14.18.1
 - Yarn Version: v1.22.10

**Additional context**
Finefoods client application can be deployed for both Heroku and Netlify. No problems occured.

**Comment by omeraplak** [comment]
Hey @niwasmala ,
I've tried Netfily deploy and works great! 

Preview link: https://61a72cf22c1734ca2a9b1741--sharp-perlman-9f34aa.netlify.app/

Could you share your Netfily config?

**Comment by niwasmala** [comment]
It seems to happen when I delete package-lock, and using yarn install. Will try again.

**Comment by niwasmala** [comment]
Hi @omeraplak , I try to deploy using original package-lock.json and it works fine. I think we can close this issue. Thanks.
