### ISSUE TITLE
[DOC] link to contributions returns 404

### ISSUE THREAD

**Issue by lindamacdonald** [pankod/refine#1281]
**Is this issue related to an existing part of the documentation? If so, please provide a link** the link can be found here on Github and is this one: https://refine.dev/docs/contributing
Helpful info about this issue.

**Describe the thing to improve**
your link: https://refine.dev/docs/contributing returns a 404

**Describe the solution (optional)**
check where the page has been moved to

**Comment by omeraplak** [comment]
Hey @lindamacdonald ,
Thank you! We've updated!
