### ISSUE TITLE
[BUG] Wrong filter operators in refine-supabase

### ISSUE THREAD

**Issue by icomad** [pankod/refine#1282]
**Describe the bug**
There is a wrong switch case in the refine-supabase dataProvider `generateFilter` function, `contains` and `containss` are reversed. At the moment `contains`, which should be case-insensitive, is using the `like` operator, which is case-sensitive. Meanwhile `containss`, which should be case-sensitive, is using the `ilike` operator, which is case-insensitive.

**To Reproduce**
1. Bootstrap a new refine project using supabase as dataProvider
2. Add a select filter on a resource field
3. Try to filter the select options using a lowercase value where there should be an uppercase one
4. The select will not find that option

**Expected behavior**
The select filter should be able to find the option

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser Chrome 
 - Version 96.0.4664.55
 - Used dataProvider refine-supabase

**Comment by omeraplak** [comment]
Hey @icomad ,
Oh, good point. Do you want to do this for us?

**Comment by omeraplak** [comment]
Hey @icomad ,
We've released `@pankod/refine-supabase@2.4.4`. Could you approve this fix?
