### ISSUE TITLE
[BUG] useMenu returns selectedKey as "notfound"

### ISSUE THREAD

**Issue by salihozdemir** [pankod/refine#1283]
**Describe the bug**
When I want to add staticly `<Menu.Item>` on my CustomSider. `useMenu` returns selectedKey as "notfound" but it should return the current location pathname. In this way, i can manage selected menu item with their key name.

**Expected behavior**
When `useMenu` cannot find the resource, it should return location pathname. 

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3
 - Browser: Chrome 96.0.4664.93

**Comment by omeraplak** [comment]
Hey @salihozdemir  ,
I've created PR #1435. We are planning to release it today 🚀

**Comment by omeraplak** [comment]
Hey @salihozdemir ,
We've released 2.6.1. Could you approve this fix?
