### ISSUE TITLE
[BUG] When route change Layout re-render

### ISSUE THREAD

**Issue by salihozdemir** [pankod/refine#1284]
**Describe the bug**
I want to use `<SubMenu>` in my CustomSider component, but when I click on SubMenu items, the route changes, resulting in SubMenu dropdown closing but I don't want it to close.

This problem can be solved if the layout is not re-rendered in every route change.

**Expected behavior**
The Layout is not re-render in every route change.

**Desktop:**
 - OS: MacOS 11.2.3
 - Browser: Chrome 96.0.4664.93

**Comment by omeraplak** [comment]
Hey @salihozdemir ,
We've released `@pankod/refine-react-router@2.5.5`. Could you approve this fix?

**Comment by wy-z** [comment]
> Hey @salihozdemir , We've released `@pankod/refine-react-router@2.5.5`. Could you approve this fix?

Hi @omeraplak.
It seems that 'nextjs-router' has the same problem.
