### ISSUE TITLE
[BUG] Extra request being made by `Show` component

### ISSUE THREAD

**Issue by luizgribeiro** [pankod/refine#1286]
**Describe the bug**
The `Show` component seems to be making a request which results can't be used on it's context.
Because of that, it was needed to configure the `useShow` hook in order to get the request result and therefore two requests were made to the same endpoint as suggested by the following image:

![image](https://user-images.githubusercontent.com/10711482/145033171-8c32a8f6-6550-4295-bfb1-2c45e46eef5c.png)

The number of requests being made was shown as expected when the `Show` component was replaced by the `Card` component.
The image bellow confirms this behavior.

![image](https://user-images.githubusercontent.com/10711482/145033700-be507e47-6a53-488e-84d0-27329a78196b.png)

**To Reproduce**
1. Configure a `List` view with a show button
2. Click on the show button
3. Configure the `Show` with with both `Show` and `Card` components
4. See the different number of requests being made in each case

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 94.0.2
 - Used dataProvider: RestAPI

**Comment by omeraplak** [comment]
Hey @luizgribeiro ,
Thank you for contacting us!
`<RefreshButton>` component is used in the Show component. It uses `useOne` hook inside `<RefreshButton>`. This query is `enabled: false` by default (https://github.com/pankod/refine/blob/master/packages/core/src/components/buttons/show/index.tsx#L58).

The value "2" you see in React Query dev tools shows how many components/hooks have a connection on this `cacheKey`, not how many times the request went.

When you look at the Network tab, you can verify that the requests do not go more than once. If you see more than one request in the network tab, please let me know.

Could you please warn me if there is something I missed?
