### ISSUE TITLE
[FEAT] Add initialFetchSize and caseSensitiveSearch field to useSelect's props

### ISSUE THREAD

**Issue by RayhanHamada** [pankod/refine#1289]
**Is your feature request related to a problem? Please describe.**

1. useSelect is by default only fetch 10 initial data candidates, in my case i have more than 10 candidates to show under the select component, would be nice if we can have more.

2. useSelect search results seems to be only returning elements filtered with 'contains' operator. Also would be nice to have option to use 'containss' operator.

**Describe the solution you'd like**
1. add initialFetchSize inside UseSelectProps that specify initial size of data to fetch.
2. add caseSensitiveSearch inside UseSelectProps that specify whether the search should be case sensitive.

Not quite sure how to implement it as i haven't skim through useSelect code yet.

Please correct me if i'm missing something. Thank you.

**Comment by omeraplak** [comment]
Hey @RayhanHamada ,
Thanks for the feature request. We'll get it in our backlog as soon as possible!

**Comment by omeraplak** [comment]
Hey @RayhanHamada ,
We've released 2.5.0. We've added `[fetchSize](https://refine.dev/docs/api-references/hooks/field/useSelect/#fetchsize)` and `[onSearch](https://refine.dev/docs/api-references/hooks/field/useSelect/#onsearch)` support!
