### ISSUE TITLE
[FEAT] Adding initialFilter parameters in useForm 

### ISSUE THREAD

**Issue by hectoryx** [pankod/refine#1309]
**Is your feature request related to a problem? Please describe.**
Currently the hook useForm does not have a way to add parameters to the request, this happens when we get values when editing a record. 

**Describe the solution you'd like**
We could add the initialFilter property as used in useTable, this would add more parameters to our request.

Example:

/post/1?field=value

**Comment by omeraplak** [comment]
Hey @hectoryx ,
Firstly, Could you add the Issue title?

Could you also share your use case with us? What do you want to do and why is it not working? Theoretically you shouldn't need this. But we are wondering about the use case.

**Comment by hectoryx** [comment]
> Hey @hectoryx , Firstly, Could you add the Issue title?
> 
> Could you also share your use case with us? What do you want to do and why is it not working? Theoretically you shouldn't need this. But we are wondering about the use case.

Sure, in the specific case of strapi, when we have draft records, these records are not visible in the requests, the solution is to add ?_publicationState=preview to the request, this applies in one record or many.

**Comment by omeraplak** [comment]
> > Hey @hectoryx , Firstly, Could you add the Issue title?
> > Could you also share your use case with us? What do you want to do and why is it not working? Theoretically you shouldn't need this. But we are wondering about the use case.
> 
> Sure, in the specific case of strapi, when we have draft records, these records are not visible in the requests, the solution is to add ?_publicationState=preview to the request, this applies in one record or many.

Ohh okay. We add the use of the "metadata" field for "publicationState" for Strapi v4 data provider. I think we can do the same for v3. So you get what you want!

I don't know if we can do this anytime soon, but I think you can too.

While doing this, you can be inspired by Strapi v4 Data provider,

https://github.com/pankod/refine/blob/strapi-v4/packages/strapi-v4/src/dataProvider.ts#L101

https://github.com/pankod/refine/blob/strapi-v4/packages/strapi-v4/src/dataProvider.ts#L190

**Comment by hectoryx** [comment]
Got it, Thanks!
