### ISSUE TITLE
[FEAT] Local development supports bundless solutions.

### ISSUE THREAD

**Issue by rancy98** [pankod/refine#1311]
**Is your feature request related to a problem? Please describe.**
When I try to start the newly created demo project, although it is very small, it obviously takes much longer to start than the vite project. Similarly, I hope the local development experience can be different from ordinary webpack applications.

**Describe the solution you'd like**
Integrated vite. Like Remix.

**Comment by omeraplak** [comment]
Hey @rancy98 ,
Vite support would be great we'll look into it but maybe you can speed it up now by using the filter on the start or bootstrap command.

What command are you using when running the project?

For example,
if you want just run Core and react-router,

```npm run start -- --scope @pankod/refine --scope @pankod/refine-react-router```

You can select the project to run using the command.

**Comment by miyavsu-limited** [comment]
Hey @rancy98,

Do you mean to integrate it to your project that uses and depends on refine or do you mean to integrate it to refine core packages and their development flow?

**Comment by jadhavajay** [comment]
Can Refine also support Remix as part of its core package?
