### ISSUE TITLE
axios headers type error

### ISSUE THREAD

**Issue by Ding-Fan** [pankod/refine#1312]
https://github.com/pankod/refine/blob/d58495007d71034ba05678c44246257641eadb7e/examples/dataProvider/strapi/src/App.tsx#L28

I'm using TypeScript and this line got an error. 

```
Type '{ Authorization: string; }' is not assignable to type 'HeadersDefaults'.
  Object literal may only specify known properties, and 'Authorization' does not exist in type 'HeadersDefaults'.ts(2322)
```

It should be 

```ts
            axiosInstance.defaults.headers.common = {
```

Also applies to the the next occurrence of `defaults.headers`

https://github.com/pankod/refine/blob/d58495007d71034ba05678c44246257641eadb7e/examples/dataProvider/strapi/src/App.tsx#L44

Reference: https://github.com/axios/axios#custom-instance-defaults

**Comment by eren-dhoheiri** [comment]
try to check your Axios version. It must be equal to Axios version in dataProvider.
