### ISSUE TITLE
[BUG] useTable returns stale result while loading when using pagination

### ISSUE THREAD

**Issue by IgnusG** [pankod/refine#1316]
**Describe the bug**
`useTable` returns the current data as result (with loading set to false) while loading when using the pagination. Once the result comes in, the hook returns the correct data (loading is still set to false). This causes the loading animation to not play while using pagination since loading is always false.

**To Reproduce**
1. Go to list element using useTable
2. Click on another page
3. Observe that stale data is delivered by hook (no loading animation is started)
4. Once data arrives, the page updates with the new data

**Expected behavior**
The hook returns loading true when using pagination instead of a stale result such that the loading animation plays.

**Screenshots**
![refine-pagination-bug](https://user-images.githubusercontent.com/6438760/145853100-dada1863-a4ac-4808-acde-91594216daae.gif)

**Desktop (please complete the following information):**
 - Browser: Edge
 - Version: 2.0.7
 - dataProvider: fake with a custom delay

<details>
<summary><code>dataProvider</code></summary>
<pre>
const dataProvider: DataProvider = {
    async getList(props) {
      console.log("Started request - will wait for a few seconds");
      await new Promise((resolve) => setTimeout(resolve, 5000));
      console.log("Request 'finished'");
      return {
        total: 100,
        data: new Array(10).fill(undefined).map((_, index) => ({
          Title: `Content ${
            ((props.pagination?.current ?? 1) - 1) * 10 + index
          }`,
          id: index,
        })),
      } as GetListResponse<any>;
    }
}
</pre>
</details>

<details>
<summary><code>list.tsx</code></summary>
<pre>
export function ContentList() {
  const { tableProps } = useTable<Content>();
  useEffect(() => {
    console.log("List props updated", tableProps);
  }, [tableProps]);
    return (
    &lt;List&gt;
      &lt;Table {...tableProps} rowKey=&quot;id&quot; tableLayout=&quot;auto&quot;&gt;
        &lt;Table.Column
          render={(content: Content) =&gt; &lt;ContentThumbnail content={content} /&gt;}
          className={`${tailwind(&quot;w-24&quot;)}`}
        /&gt;
        &lt;Table.Column
          dataIndex=&quot;Title&quot;
          title=&quot;Title&quot;
          render={(content: Content) =&gt; &lt;TextField value={content} /&gt;}
        /&gt;
        &lt;Table.Column&lt;Content&gt;
          title=&quot;Actions&quot;
          className={`${tailwind(&quot;w-24&quot;)}`}
          dataIndex=&quot;actions&quot;
          render={(_text, record): React.ReactNode =&gt; {
            return (
              &lt;Space&gt;
                &lt;EditButton size=&quot;small&quot; recordItemId={record.id} /&gt;
              &lt;/Space&gt;
            );
          }}
        /&gt;
      &lt;/Table&gt;
    &lt;/List&gt;
  );
}
</pre>
</details>

**Comment by omeraplak** [comment]
Hey @IgnusG ,
We've released @pankod/refine@2.4.5. Could you approve the fix?

**Comment by IgnusG** [comment]
> Hey @IgnusG , We've released @pankod/refine@2.4.5. Could you approve the fix?

Yep, works now. Thanks for the quick fix!
