### ISSUE TITLE
[FEAT] filter support for Airtable

### ISSUE THREAD

**Issue by IgnusG** [pankod/refine#1317]
**Is your feature request related to a problem? Please describe.**
I see that the list query for data providers allows for passing a filter in. It seems the Airtable data provider does not support this yet.

**Describe the solution you'd like**
Airtable does support filtering through the [`filterByFormular`](https://vancelucas.com/blog/airtable-api-filterbyformula/) query parameter (supported by the Airtable JS library too). A library like https://github.com/Qualifyze/airtable-formulator can be used to ensure type safety and an ORM-like interface between them.

**Additional context**
I can create a PR with the changes to the Airtable provider to enable this. It just needs a translation layer to transform the Refine CrudFilters into a string that can be given to `filterByFormula` similar to eg.  the strapi data provider package and co

**Comment by omeraplak** [comment]
Hey @IgnusG ,
It's a great point. We are waiting for your PR!

**Comment by omeraplak** [comment]
Hey @IgnusG ,
We've released 2.4.11! Thank you
