### ISSUE TITLE
[FEAT] Limit Offset Pagination for simple-rest-provider?

### ISSUE THREAD

**Issue by sajjad006** [pankod/refine#1318]
Currently the simple-rest data provider has the feature of paginating queries based on starting and ending values. It would be great if other pagination formats such as limit offset pagination, page number pagination, etc. could be incorporated so as to enable to seamlessly connect to other third party backend REST applications such as the DJango rest framework.

**Comment by omeraplak** [comment]
Hey @sajjad006 ,
You can do `offset` pagination by overriding `@pankod/refine-simple-rest`'s `getList` function. The fact that simple-rest supports multiple pagination strategies will create complexity. We want you to write or override your own `dataProvider` where necessary.

We try to support as many popular APIs as possible, but we cannot support all of them. For example, if you develop a dataProvider for Django, please don't forget to share it with Community. 

Thank you very much for your understanding and support! Cheers!
