### ISSUE TITLE
[DOC] Specify project node version in Contributions 

### ISSUE THREAD

**Issue by IgnusG** [pankod/refine#1371]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
I think Contributions would be a good place to put this into.

**Describe the thing to improve**
I was not sure which version of node to use for development but I see that package-lock.json is at version 1 so I opted for the latest node 14 version which finally did not seem to adjust package-lock.json on initial install.

My initial install with node 17 upgraded the whole package-lock.json which should not usually not be something a contributor does (I know I hate it when contributors create a PR with 50k lines of changes since they changed the lock version or structure by using a newer node/npm/yarn version). 😅 

**Describe the solution (optional)**
Either a version file (.nvm, .tool-versions or similar) with the node version or a mention on the [contributing](https://refine.dev/docs/contributing/) page would be good to have.

**Comment by omeraplak** [comment]
Thank you very much for the warning. We updated it to our Contribution document!
