### ISSUE TITLE
[BUG] The API in title seems old in tutorial

### ISSUE THREAD

**Issue by bathtimefish** [pankod/refine#1376]
https://github.com/pankod/refine/blob/6bdf88fe80a2d548e602240cb057502b041760f5/documentation/docs/tutorial.md?plain=1#L254

Is `https://api.fake-rest.refine.dev/posts` the correct URL?

The API url seems old in tutorial doc because it has indicated SSL problem.

**Comment by omeraplak** [comment]
Hey @bathtimefish,
Thank you. We've fixed it!
