### ISSUE TITLE
[BUG] Hasura Count Aggregation Filter

### ISSUE THREAD

**Issue by narayandreamer** [pankod/refine#1377]
**Describe the bug**
In Hasura and may be other similar packages too aggregation doesn't have filters

**To Reproduce**
1. Use Hasura dataProvider
2. Apply filters in list
3. Scroll down to page numbers
4. There will be empty pages without data

**Expected behavior**
Pagination count creates problem resulting in empty pages

**Screenshots**
![screenshot-localhost_3000-2021 12 19-13_33_14](https://user-images.githubusercontent.com/61919250/146668031-e68bdbf8-9538-4ed3-91fc-f8056c25bd56.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [Chrome]
 - Version [96]
 - Used dataProvider [Hasura]

**Additional context**
We can use variables of filters in main operation in aggregate operation too

**Comment by omeraplak** [comment]
Hey @narayandreamer ,
We've released `@pankod/refine-hasura@2.4.13`. Thank you!
