### ISSUE TITLE
[QUESTION] How to programmatically refresh table?

### ISSUE THREAD

**Issue by niwasmala** [pankod/refine#1384]
Hi. I want to ask how to programmatically refresh table?

My use case is like this. I have a table which has drag-and-drop sort. 

![image](https://user-images.githubusercontent.com/476869/147316164-72cc0e2d-cee7-4e37-a948-204f0933f3a7.png)

Here is the pseudo code used to display the table. Index is like row number with values 1, 2, etc.

```jsx
const { tableProps } = useTable<IForm>({
    initialSorter: [{
      field: 'index',
      order: 'asc',
    }],
});

const onSortEnd = async ({ oldIndex, newIndex }: any) => {
    if (oldIndex !== newIndex) {
       // DONE: call api to update the index
       
       // TODO: how to force table to refresh it's data?
    }
};
```

I already implement the handler in the table with [this reference from ant design table](https://ant.design/components/table/#components-table-demo-drag-sorting-handler), and sent api call to backend to update the index.

What I need to do now is after calling api, I want to make the table refresh it's data from server so I can get the correct sort. Is there any way to make the table reload?

I was expecting on return values of `useTable` has refresh function that I can call such as

```jsx
const { tableProps, refresh } = useTable<IForm>();

const onSortEnd = async ({ oldIndex, newIndex }: any) => {    
    if (oldIndex !== newIndex) {
       // DONE: call api to update the index
       
       // TODO: how to force table to refresh it's data?
       refresh();
    }
};
```

**Comment by omeraplak** [comment]
Hey,
You can use "tableQueryResult" of useTable hook.

Example,
const { tableProps, tableQueryResult } = useTable<IForm>();

tableQueryResult.refetch();

Have a great day!

**Comment by niwasmala** [comment]
Awesome! Thanks a lot 👍

**Comment by omeraplak** [comment]
> Awesome! Thanks a lot 👍 

You're welcome!

Normally you shouldn't need to "refetch". Refine mutation automatically invalidates the resources that occur. Could you share your final code with us so we can see if there is a problem? We want to make sure everything is okay. Thanks
