### ISSUE TITLE
[BUG] Unable to run Airtable example

### ISSUE THREAD

**Issue by samantha-wong** [pankod/refine#1385]
**Describe the bug**
Unable to run the Airtable example from the repo. The UI is non-responsive.

Console is returning uncaught referenceError: process is not defined.

**To Reproduce**
1. cd to examples/dataProvider/airtable
2. install dependencies
3. fix category in post list component (needs a fallback check)
4. yarn start

**Expected behavior**
User should be able to interact with the demo (edit/create post)

**Screenshots**
![image](https://user-images.githubusercontent.com/19571028/147340858-4bd11927-4310-4a68-b21e-e0e576f94eed.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 1.33.106
 - Used dataProvider Airtable

**Comment by omeraplak** [comment]
Hey @samantha-wong ,
We've fixed Airtable Example! Thank you!
