### ISSUE TITLE
[FEAT] Loosen ID type to include numbers as well as strings

### ISSUE THREAD

**Issue by doender** [pankod/refine#1397]
**Is your feature request related to a problem? Please describe.**
In our current API id's are represented as numbers.  In hooks like `useMany` and `useSelect` I currently have to convert them to strings myself, e.g.:
```
type ProductCategory = {
  id: number
  name: string
}

const { data: categoriesData, isLoading } = useMany<ProductCategory & { id: string }>({
   resource: 'categories',
   ids: categoryIds.map((id) => id.toString()),
   queryOptions: {
      enabled: categoryIds.length > 0,
   },
});
```  

**Describe the solution you'd like**
Accept numbers as well as strings.

**Comment by omeraplak** [comment]
Hey @doender ,
We've released 3.4.0. Could you approve this fix?
