### ISSUE TITLE
[FEAT] Preserve filters and page number when navigating back from create/update page

### ISSUE THREAD

**Issue by IgnusG** [pankod/refine#1410]
**Is your feature request related to a problem? Please describe.**
When clicking on back on an update page or after save, the user is taken to the first page without any sorting or filters applied.
As a user It would be nice for filters, sorting and the current page number to stay the same when navigating back to the list of records after updating a record or clicking on the back arrow.

**Describe the solution you'd like**
Refine could keep track of the sorting, filters, and page number in the URL (would make it possible to bookmark or share these too) which could then be used for back navigation.

**Describe alternatives you've considered**
None so far. But I assume this might need some work to save all of this data onto the URL and then update filters, sorting and page numbers accordingly. Especially filters and sorting might need a breaking change - not sure if this change would not go against their current API.

**Additional context - Example**

![refine-stateful-url-suggsion](https://user-images.githubusercontent.com/6438760/148128597-3bf44ac3-83ec-4d87-a7b2-ba5efcc829f1.gif)

1. Go to list page
2. Go to second page
3. Click on edit
4. Click on back
5. Observe that we are on the first page again

**Comment by omeraplak** [comment]
Hey @IgnusG ,
I have good news for you. This already exists! 

You can use "syncWithLocation"
https://refine.dev/docs/api-references/hooks/table/useTable/#properties
