### ISSUE TITLE
[BUG] Warnings when running the project 

### ISSUE THREAD

**Issue by hectoryx** [pankod/refine#1422]
**Describe the bug**
When starting the project, we get 2 warnings, in the export-to-csv module, the project starts normally as long as we do not need that library.

**To Reproduce**
Run yarn start or npm run start, inside the project folder.

**Expected behavior**
Avoid warnings when running the project.

**Additional context**
This warning started coming with "react-scripts@5".

**Comment by omeraplak** [comment]
Hey @hectoryx ,
The main source of this issye is the react-scripts package. We follow this issue from react-scripts issues!

**Comment by omeraplak** [comment]
Hey @hectoryx ,
I'm closing this as it's a similar issue #1250

**Comment by omeraplak** [comment]
Hey @hectoryx ,
We've released 3.2.2. Could you approve this fix?
