### ISSUE TITLE
[BUG] Sidebar menu does not indicate right item

### ISSUE THREAD

**Issue by ahmethakanbesel** [pankod/refine#1432]
**Describe the bug**
If resource names similar it does not show active item correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/6422460/149373673-c45f7fda-eca9-4a01-9f1e-fdcaf025ca4c.png)
![image](https://user-images.githubusercontent.com/6422460/149374405-3969b28c-0aa7-4acb-a795-69e2d5a07d17.png)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0
 - Used dataProvider REST API

**Comment by omeraplak** [comment]
Hey @ahmethakanbesel ,
Thank you for reaching us. I've created PR #1435. We are planning to release it today 🚀

**Comment by omeraplak** [comment]
Hey @ahmethakanbesel ,
We've released 2.6.1. Could you approve this fix?

**Comment by ahmethakanbesel** [comment]
> Hey @ahmethakanbesel , We've released 2.6.1. Could you approve this fix?

Yes, it's resolved. Thanks for the fast response.
