### ISSUE TITLE
[BUG] Custom route name does not take effect with `refine-nextjs-router`

### ISSUE THREAD

**Issue by wy-z** [pankod/refine#1442]
**Describe the bug**
Custom route name does not take effect with `refine-nextjs-router`.

**To Reproduce**
1. Register resource with custom route
```javascript
{
  name: "foo",
  options: {
    route: "/custom/foo",
  }
}
```
2. Create dynamic nextjs pages
```
pages/custom/[resource]
pages/custom/[resource]/index.tsx
...
```
3. Request `/custom/foo`, the server return `404`

**Expected behavior**
The server should return resource page as expected.

**Additional context**
Look at the following codes
https://github.com/pankod/refine/blob/69b36225c3d097dfe5f9d915cc81c47a49280a9b/packages/nextjs-router/src/nextRouteComponent.tsx#L36
Nextjs router find resource by comparing `resource name` and `resource.route`, but `resource.route` is changeable.

The following codes worked for me
```js
const resource = resources.find((res) => res.name === routeResourceName); 
```
Or
```js
const resource = resources.find((res) => res.name === routeResourceName || res.route === routeResourceName); 
```

**Comment by omeraplak** [comment]
Hey @wy-z ,
Thanks for the bug report.

Yes, your solution is nice but when I use something other than `resource` name as `customRoute` this solution doesn't work.

Example;
```
{
   name: "foo",
   options: {
     route: "/custom/bar",
   }
}
```
Any ideas on how we can handle this?

**Comment by wy-z** [comment]
> Hey @wy-z , Thanks for the bug report.
> 
> Yes, your solution is nice but when I use something other than `resource` name as `customRoute` this solution doesn't work.
> 
> Example;
> 
> ```
> {
>    name: "foo",
>    options: {
>      route: "/custom/bar",
>    }
> }
> ```
> 
> Any ideas on how we can handle this?

 Hi @omeraplak , thank you for your support.
https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes
```
Dynamic routes can be extended to catch all paths by adding three dots (...) inside the brackets. 
```
For example:
1. Create dynamic nextjs page
```
pages/[...resource].tsx
```
2. Request `/custom/bar`, the `resource` param will be `['custom', 'bar']`

So, one possible way is
1. if the type of `resource` is string, compare with `resource.name` and `resource.route`
2. if the type of `resource` is array, splice the strings together (`['custom', 'bar']-> '/custom/bar'`), and compare with `resource.route`

**Comment by omeraplak** [comment]
Hey @wy-z ,
Ups I didn't know that. I tried quickly but this time I got stuck on another limitation.

Refine needs 2 dynamic routes when used with next.js.

1. `[resource]` -> `/posts`
2. `[resource]/[action]/[id]` -> `/posts/create` or `/posts/edit/1`

Now when I want to use `[...resource]` instead of `[resource]` as you suggested, I get an error like this,
`Error: Catch-all must be the last part of the URL.`

It seems like we can't do what we want with Next.js' dynamic route support. Do you have any idea?

but we can do this
I know it's not a very good solution, but I'll suggest it temporarily.

By creating a page as `/pages/custom/bar` you can handle like the [`user`](https://github.com/pankod/refine/blob/master/examples/refine-next/pages/users/index.tsx) page our [refine-next](https://github.com/pankod/refine/tree/master/examples/refine-next) example.

How does this sound?

**Comment by wy-z** [comment]
> Hey @wy-z , Ups I didn't know that. I tried quickly but this time I got stuck on another limitation.
> 
> Refine needs 2 dynamic routes when used with next.js.
> 
> 1. `[resource]` -> `/posts`
> 2. `[resource]/[action]/[id]` -> `/posts/create` or `/posts/edit/1`
> 
> Now when I want to use `[...resource]` instead of `[resource]` as you suggested, I get an error like this, `Error: Catch-all must be the last part of the URL.`
> 
> It seems like we can't do what we want with Next.js' dynamic route support. Do you have any idea?
> 
> but we can do this I know it's not a very good solution, but I'll suggest it temporarily.
> 
> By creating a page as `/pages/custom/bar` you can handle like the [`user`](https://github.com/pankod/refine/blob/master/examples/refine-next/pages/users/index.tsx) page our [refine-next](https://github.com/pankod/refine/tree/master/examples/refine-next) example.
> 
> How does this sound?

Sorry, my mistake, `resource`, `action`, `id` are both required for `refine-nextjs-router`. 🤦‍♂️
`By creating a page as /pages/custom/bar .` looks good to me.
In my opinion, the route that cannot contain `resource name` is a very special case, in most cases `[resource]/[action]/[id]` can meet the requirements.

**Comment by omeraplak** [comment]
Yes, you are right. I think applying what you say is much better than the current version. I created a PR (#1443 ) for it! Thanks for everything!

By the way, do you still have Layout re-render issue when changing the route in "nextjs-router"? I saw your comment yesterday but I can't see it today.

**Comment by wy-z** [comment]
> Yes, you are right. I think applying what you say is much better than the current version. I created a PR (#1443 ) for it! Thanks for everything!

It's my pleasure. 

> By the way, do you still have Layout re-render issue when changing the route? I saw your comment yesterday but I can't see it today.

When create a custom page with `refine-nextjs-router`, `LayoutWrapper` is necessary, and when route change to a custom page, sider bar will be re-rendered, sub menu state will be changed.
Is there a good solution?

**Comment by omeraplak** [comment]
I have now created version 2.6.3. It will be published in ~15 minutes!

By the way, I have an idea for Layout re-render issue. I'll open a new issue and tag you!

**Comment by wy-z** [comment]
> I have now created version 2.6.3. It will be published in ~15 minutes!
> 
> By the way, I have an idea for Layout re-render issue. I'll open a new issue and tag you!

Truly grateful for your kindness. 
Good luck and great success in the New Year.
