### ISSUE TITLE
[BUG] Many examples fail to run out of box

### ISSUE THREAD

**Issue by ronnyek** [pankod/refine#1445]
**Describe the bug**
Many of the examples (notably in examples/customization) fail to run successfully. They both have issues running locally, as well as some of the examples that are code playgrounds in the documentation. I actually get more errors running in linux environment with the same version of node.

**To Reproduce**
1. Clone this repo
2. change directory to examples/customization/<project> (customTheme for example)  
3. restore packages (npm install here fails for me, yarn succeeds)
4. yarn start

Observe
```
Compiled with problems:X

ERROR

Failed to load plugin 'react' declared in '..\..\..\.eslintrc': Cannot find module 'eslint-plugin-react'
Require stack:
- C:\Dev\source\refine\.eslintrc
Referenced from: C:\Dev\source\refine\.eslintrc

```

**Expected behavior**
I'd expect to see running examples with their denoted behavior, customTheme, or customLogin, or headermenu etc.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows and Ubuntu LInux
 - Browser Latest Chrome, Brave
 - Node 16.13.2

**Additional context**
These errors popup, but you can hit the x in the browser, but I as actually able to get different errors on ubuntu linux box with same node version, that would not let these specific examples run at all.

**Comment by omeraplak** [comment]
Hey @ronnyek ,
Could you try `DISABLE_ESLINT_PLUGIN=true` to `.env` file?

**Comment by ronnyek** [comment]
That definitely seemed to help with some of those errors I was running into with examples. Thanks!
