### ISSUE TITLE
Update Dataprovider for Appwrite >0.12 

### ISSUE THREAD

**Issue by BobcatProgrammer** [pankod/refine#1453]
The recent relase of Appwrite 0.12 has changed the database API of Appwrite. Specifically the permissions have been changed. The `"*"` wildcard permission has been replaced by `"role:all"`. You can find more info in the [Migration Guide](https://dev.to/appwrite/appwrite-012-migration-post-3cha) blog post.

I found 4 instances of falling back to the `"*"` wildcard in the provider:
https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L139
https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L140

https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L155
https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L156

https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L172
https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L173

https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L226
https://github.com/pankod/refine/blob/cba0000f86d35774f9b397fcf3a2f4edae62a739/packages/appwrite/src/index.ts#L227

**Comment by omeraplak** [comment]
Hey @BobcatProgrammer ,
The Appwrite team warned us about this. Let's review the Migration Guide and see what we can do. Thank you!

**Comment by BobcatProgrammer** [comment]
As far as I understood it the old `"*"` is equivalent to `"role:all"` and changed on all documents during appwrite migration to 0.12. so just changing the instances I marked above should be enough (and a comment in the docs that appwrite >=0.12 is required)

**Comment by omeraplak** [comment]
> As far as I understood it the old `"*"` is equivalent to `"role:all"` and changed on all documents during appwrite migration to 0.12. so just changing the instances I marked above should be enough (and a comment in the docs that appwrite >=0.12 is required)

Great, do you want to do this for us?

**Comment by bhagatpratham** [comment]
I can do that?

I just need to replace ``` ["*"] ``` with ``` ["role:all"] ``` in refine/packages/appwrite/src/index.ts

am I correct?

**Comment by omeraplak** [comment]
Yes, it looks great. Also, in [Appwrite Guide](https://refine.dev/docs/guides-and-concepts/data-provider/appwrite/), we need to add a warning for those who use an Appwrite version older than 0.12.

@BobcatProgrammer what do you think? Do you want to do it? @bhagatpratham can it?

**Comment by BobcatProgrammer** [comment]
wont be able to get around to it anytime soon so @bhagatpratham your stage 🚀!

**Comment by bhagatpratham** [comment]
> wont be able to get around to it anytime soon so @bhagatpratham your stage 🚀!

okay, let's go 🚀!

**Comment by bhagatpratham** [comment]
> Yes, it looks great. Also, in [Appwrite Guide](https://refine.dev/docs/guides-and-concepts/data-provider/appwrite/), we need to add a warning for those who use an Appwrite version older than 0.12.
> 
> @BobcatProgrammer what do you think? Do you want to do it? @bhagatpratham can it?

hey @omeraplak can you guide me on how to create a warning? thanks

**Comment by BobcatProgrammer** [comment]
The Appwrite docs are [here](https://github.com/pankod/refine/blob/master/documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/appwrite.md) 
in the docs you can scroll down to the bottom and click "Edit this page" and it takes you to the related github file
![image](https://user-images.githubusercontent.com/22432834/151228810-d3f28d1e-3170-4733-95d4-02eda5874283.png)

**Comment by omeraplak** [comment]
> > Yes, it looks great. Also, in [Appwrite Guide](https://refine.dev/docs/guides-and-concepts/data-provider/appwrite/), we need to add a warning for those who use an Appwrite version older than 0.12.
> > @BobcatProgrammer what do you think? Do you want to do it? @bhagatpratham can it?
> 
> hey @omeraplak can you guide me on how to create a warning? thanks

We use [Docusaurus](https://docusaurus.io/) for docs. 
Here you can find how to add Warning, https://docusaurus.io/docs/markdown-features/admonitions.

here is what you need to run our docs, https://refine.dev/docs/contributing/#starting-documentation-in-watch-mode

**Comment by omeraplak** [comment]
Hey @BobcatProgrammer , @bhagatpratham ,
We've released `@pankod/refine-appwrite@2.7.1`. Thank you!

ps. @bhagatpratham, Are you on our Discord server? If you DM me on Discord, I will give you the "Contributor" role.
Discord: https://discord.gg/UuU3XCc3J5

@BobcatProgrammer, I already gave it to you :)
