### ISSUE TITLE
[BUG] show error: TypeError: Cannot read property 'push' of null when using next.js router

### ISSUE THREAD

**Issue by RudyLu** [pankod/refine#1478]
**Describe the bug**
show error: TypeError: Cannot read property 'push' of null when using next.js router.

**To Reproduce**
1. Follow the tutorial by using:
`npx superplate-cli tutorial`
2. select `refine-nextjs` as the project type
3. select `Yarn` as the package manager

**Expected behavior**
Can show the first page after `yarn dev`

**Screenshots**
![Screen Shot 2022-01-26 at 2 06 14 PM](https://user-images.githubusercontent.com/1704629/151112394-a332acbd-3971-4e63-b112-6534fc400ff3.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Versions:
   - refine: 2.7.1
   - yarn: 1.22.5

**Comment by omeraplak** [comment]
Hey @RudyLu ,
Ups sorry for this situation. Can you try to upgrade all the refine packages to the latest version?
like this;
```
rm -rf package-lock.json node_modules
npm i @pankod/refine@latest @pankod/refine-nextjs-router@latest @pankod/refine-simple-rest@latest
```

**Comment by RudyLu** [comment]
Thanks for the reply.
Just realized that this could only be reproduced when using `yarn`.
I tried to switch back to `npm` and it works fine.

**Comment by omeraplak** [comment]
Thanks a lot for your quick reply. We solved this problem with Refine 3 (headless). I'm closing this issue for now.
