### ISSUE TITLE
[BUG] Strapi V4 dataProvider useUpdate

### ISSUE THREAD

**Issue by kalib-code** [pankod/refine#1482]
Strapi V4 dataProvider

useUpdate is working with no error but changes don't  on strapi

on the  data provider, you have this

![code  fix](https://user-images.githubusercontent.com/17924045/151299192-7913b66d-b1a4-45c8-8bd3-b9f65c8cf4e8.png)

after doing some debugging I found out that you don't need the data and just pasting the variables for strapi V4 don't require you to past data at the start of your payload

![code ddd](https://user-images.githubusercontent.com/17924045/151299360-4ed20b3d-f0a7-41b0-90e6-669a00eac36d.png)

**Comment by omeraplak** [comment]
Hey @kalib-code ,
Thank you! We've released `@pankod/refine-strapi-v4@2.7.3`
