### ISSUE TITLE
Provide the ability to redirect a user to a custom page after login

### ISSUE THREAD

**Issue by vmalep** [pankod/refine#1504]
**Is your feature request related to a problem? Please describe.**
After login, the user is taken to the list page of the 1st resource. However, we would like the user to be taken to a custom dashboard instead.

**Describe the solution you'd like**
I suggest that a custom path coud be added to the `return Promise.resolve();` of the login method, alike for the logout method, that would send the user to the desire path.

For example: `return Promise.resolve("/dashboard/overview");`

**Comment by ozkalai** [comment]
Hello @vmalep,

We've released custom redirect support for login method of AuthProvider on version 3.1.1. You can check how to use it on this link.

[](https://refine.dev/docs/next/core/hooks/auth/useLogin/)

Please share with us how your experience will be about this support.

**Comment by vmalep** [comment]
It seems to work great. Tanks!
Why not to apply the same for all the Promise.resolve() of the authProvider? So we can also redirect to custom page in case of error or logout? Should I create a new issue for that?
