### ISSUE TITLE
[FEAT] Do Refetch in useEditableTable or useTable

### ISSUE THREAD

**Issue by natserract** [pankod/refine#1512]
So, when i use this `useEditableTable` or `useTable`,  and want to refetch data after some event. 

```tsx
const {
  ...
  queryResult,
  tableQueryResult
  ...
} = useEditableTable({
...
})

// Call this
queryResult.refetch(); // or
```

![Screen Shot 2022-02-04 at 9 26 02 PM](https://user-images.githubusercontent.com/31182611/152536728-f3364d7d-1fab-4e02-8c31-325a7b3e8327.png)

That's hooks invoked `getOne` function in data provider. I don't know why this hooks call getOne?, and this show an error. Because of that's here i want to share about doing refetch data in useEditableTable or useTable properly maybe some weird trick.

1. Create initial state:
```tsx
const [doRefetch, setDoRefetch] = useState(false);
```
2. Use **query options** in `useEditableTable`. See here more detail [useEditableTable API](https://refine.dev/docs/api-references/hooks/table/useEditableTable/#api) 
```tsx
const {
  tableProps,
  formProps,
  sorter,
  searchFormProps,
} = useEditableTable({
    ...
    queryOptions: {
      enabled: doRefetch // use doRefetch state
    }
  })
```
3. Prepare for fetch on mount
```tsx
const refetchQuery = useCallback(() => {
 setDoRefetch(true)

 // Change state after process done
 // You can change to default value after get data
 // Make sure the request done and success.
 setTimeout(() => setDoRefetch(false), 50)
}, [])

// Fetch when mount, only first time
useEffect(refetchQuery, [])
```
4. Ready to use in some event, example here:
```tsx
<DeleteButton
  ...
  hideText
  size="small"
  recordItemId={record.Username}
  onSuccess={refetchQuery}
/>
```
When delete success, call refetchQuery and `useEditableTable` will do re-called (refetch).

I hope this can helps and for enhancement. Thanks!

**Comment by omeraplak** [comment]
Hey @natserract ,
The `queryResult` returning from the `useEditableTable` hook is for the edited record. If you want to `refetch` Table's data, you can call `tableQueryResult` refetch method. Didn't that work?

Normally, when a mutation is applied on 'resource', 'refetch' is done automatically. As far as I understand, the mutation is done on a different `resource` than the Table's data. Is this true?

**Comment by natserract** [comment]
Yes tableQueryResult.refetch not affect anything. 

@omeraplak yup, resource name and table it’s different. The problem is, resource name and route it’s same, in my case the route (url) not same with resource, because of that i give a resource name (ex) ‘users’ and in table ‘listUser’. I know cause of that why table not refetch automatically.

So in my case, i use that’s away (above). And it’s work.

**Comment by omeraplak** [comment]
Now for a quick test, I created a CodeSandbox, and table `refetch` worked. Am I missing something?

https://codesandbox.io/s/refine-use-editable-table-example-forked-kj5zx?file=/src/pages/posts/list.tsx

**Comment by natserract** [comment]
How about this, using different resource

```tsx
//lists.tsx
useEditableTable({
    resource: 'listPosts',
    …
})

//App.tsx

 <Refine
      dataProvider={dataProvider(API_URL)}
      routerProvider={routerProvider}
      resources={[
        {
          name: "posts",
          list: PostList
        }
      ]}
/>
```

**Comment by omeraplak** [comment]
Hey @natserract,
Now I did as you said and it worked again (https://codesandbox.io/s/refine-use-editable-table-example-forked-kj5zx?file=/src/pages/posts/list.tsx). Could you create a CodeSandbox?

**Comment by omeraplak** [comment]
Hey @natserract,
Is this issue still valid?
