### ISSUE TITLE
[FEAT] Dynamic resource options

### ISSUE THREAD

**Issue by karani12** [pankod/refine#1513]
**Is your feature request related to a problem? Please describe.**

I wanted to do things dynamically.. To do this I needed to get columns based on a table. This  information is stored in  meta tables. The table names may have the same name as they belong to different schemas. To do that I needed to make sure I was getting column information of the correct table. 

**Describe the solution you'd like**
The solution I would like is to allow an extra property such as a ID or Object as options to a resource. This options should be accessible to list, edit, show and create views. The most general solution would be to allow an options object where we can pass extra information besides label and route.  We are migrating from react admin and this was how they did it.
[passing options to resource.](https://marmelab.com/react-admin/Resource.html#options)

**Comment by xiaoyunwu** [comment]
@ozkalai any update on this?

**Comment by ozkalai** [comment]
Hello @xiaoyunwu ! I will start working on this issue next week.
