### ISSUE TITLE
[BUG] Upgrade to react-scripts v5 killed all Craco / LESS functionality on Node 16

### ISSUE THREAD

**Issue by rassie** [pankod/refine#1514]
**Describe the bug**
All the examples, tutorials and templates have been upgraded to `react-scripts` v5 in https://github.com/pankod/refine/commit/b73577793f5c4bd4d90e88a297c09df53e183d11. There is no Craco version which is compatible to v5, so that any customization based of Craco is broken, including enabling LESS support for theming.

**To Reproduce**
1. Create a new refine project with `superplate`
2. Enable theming support in the wizard
3. Observe error during initial `npm install`.

**Expected behavior**
Default and proposed configuration and also documented behaviours should work out of the box.

**Comment by omeraplak** [comment]
Hey @rassie ,
Now I tried and it worked. Are you using version 2 of `craco-less`? Also, what is your node version?

**Comment by rassie** [comment]
Tried it just now: 
```
❯ npx superplate-cli refine-test

✔ Cloned remote source successfully.
✔ Select your project type › refine-react
✔ What will be the name of your app · refine-test
✔ Package manager: · npm
✔ Do you want to customize theme?: · less
✔ Data Provider: · custom-json-rest-data-provider
✔ Auth Provider: · none
✔ Do you want to add an example page? · example-resource
✔ Do you want to customize layout? · no
✔ i18n - Internationalization: · no
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/npr/refine-test
    at ChildProcess.<anonymous> (/home/npr/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}
```

Besides that: `package.json` contains `react-scripts` v5 and `craco`, which are not compatible at this time, so if `craco-less` somehow works, it's only accidental. Executing `npm install` in that directory leads to 

```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: refine-test@0.1.0
npm ERR! Found: react-scripts@5.0.0
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"^5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.3
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/npr/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/npr/.npm/_logs/2022-02-04T14_43_23_537Z-debug.log

```

I'm on Node 16.13.2, but I don't think that should be relevant, since `craco` explicitely only works with Webpack v4 and thus `react-scripts` v4. 

Could you show what you tried?

**Comment by omeraplak** [comment]
I'm using npm@6 so I didn't encounter any errors. Have you tried the `--legacy-peer-deps` option?

**Comment by rassie** [comment]
No, but I downgraded my Node to LTS (14), which seems to work. I don't consider this a perfect solution, but it's an LTS after all, this is something that could be documented. Also it's weird that `craco-less` is CRAv5 compatible while `craco` itself is not. Hopefully `craco` will release a v5-compatible version soon, so this can be resolved.
