### ISSUE TITLE
[BUG] `generateFilter` in `simple-rest` data provider doesn't always handle multi-values

### ISSUE THREAD

**Issue by rassie** [pankod/refine#1518]
**Describe the bug**

Currently, there is only one way to create a filter with multi-values in `simple-rest`: 

```
    const filters = [
      {
        field: "postId",
        operator: "eq",
        value: [1, 2],
      }
    ];
```
The query string for this is `?postId=1&postId=2`

However, I would expect that the following would work the same way:

```
    const filters = [
      {
        field: "postId",
        operator: "eq",
        value: 1,
      },
      {
        field: "postId",
        operator: "eq",
        value: 2,
      },
    ];
```

This currently produces `?postId=2` as its querystring.

**Expected behavior**

For both filter variants, query string `postId=1&postId=2` should be generated.

**Comment by omeraplak** [comment]
Hey @rassie ,
Thank you for contacting us! This is because when we union filters, we ensure that there is only one filter from the same `field` and `operator` (https://github.com/pankod/refine/blob/master/packages/core/src/definitions/table/index.ts# L205). This usage works for us in many cases.
Why do they both have to work? Array usage is already supported.

**Comment by rassie** [comment]
They don't *have* to both work, if it's a design decision, and I wasn't sure whether it was one or not. It's something I've stumbled upon and found at least a bit confusing. I think there are cases where filters are collected in a loop, so that some kind of automatic aggregation might be nice, but it doesn't need to be, arrays work fine and as intended. Thanks!

**Comment by omeraplak** [comment]
> They don't _have_ to both work, if it's a design decision, and I wasn't sure whether it was one or not. It's something I've stumbled upon and found at least a bit confusing. I think there are cases where filters are collected in a loop, so that some kind of automatic aggregation might be nice, but it doesn't need to be, arrays work fine and as intended. Thanks!

Oh, thanks so much! I'm glad we didn't miss anything!
