### ISSUE TITLE
[FEAT] Does this work via React Admin

### ISSUE THREAD

**Issue by ssshammi** [pankod/refine#1520]
So I tried to make it work with react admin because the ra-strapi-rest is not working, i think it's quite old because of the count functionality
`import { Admin, Resource } from 'react-admin';
import { DataProvider  } from '@pankod/refine-strapi-v4';
import { PostList } from './components/PostList';

const dataProvider = DataProvider('http://localhost:1337/api');
<Admin dataProvider={dataProvider}>
                <Resource name="Courses" list={PostList} />
            </Admin>`

This is my PostList
`import React from 'react';
import { List, Datagrid, TextField } from 'react-admin';

export const PostList = (props) => (
    <List {...props}>
        <Datagrid>
            <TextField source="id" />
            <TextField source="name" />
            <TextField source="description" />
        </Datagrid>
    </List>
);`

Or if i use refine. will i be able to create custom login and pages, i am using a template. It calls undefiend for some reason. 
http://localhost:1337/api/undefined?pagination[page]=1&pagination[pageSize]=10&

i dont want to use the refine front end just the authorisation and rest provider for strapi. 
as per the document it probably looking for this 
resources={[{ name: "posts", list: PostList }]}

I am so confused, i have the UI components now i just want the strapi rest to work with it, will i be able to incorporate the template in refine

**Comment by omeraplak** [comment]
Hey @ssshammi ,
Thank you for contacting us! Refine and React Admin are different projects. I don't think you can run both together. Their approaches are completely different. Maybe you can try to get help for strapi v4 from react-admin.

**Comment by ssshammi** [comment]
@omeraplak yes i am not using react-admin now. just wanted to use the authorization and dataProvider but this repo is useful because I am to use strapi.v4 api. maybe later ill use the other components.
