### ISSUE TITLE
[FEAT] Partytown support

### ISSUE THREAD

**Issue by geoman2** [pankod/refine#1531]
Hello, this is a feature request to have support for Partytown https://partytown.builder.io in Refine. There are huge boost performance when metered with Lighthouse. Hope there is nothing complex to add this in a near future release, now that you finished the headless feature :)

**Comment by omeraplak** [comment]
Hey @geoman2 ,
I hadn't heard of Partytown before, it intrigued me, thank you very much.
But I'm confused about how to integrate it into Refine.

Is it not enough for a Refine user who wants to use Partytown to follow this document?
https://partytown.builder.io/react

Many thanks for your help in advance!

**Comment by omeraplak** [comment]
> Here is a blog post https://leosvel.dev/blog/creating-my-personal-website-with-astro-tailwindcss-and-nx/ when the author implemented partytown to run auxiliar scripts (in his case an analytics script, see the last section) on his JAMstack based blog (astrojs ssg with tailwindcss). Just wanted to have it integrated out of the box, a good addition to the headless feature you just added :)

Hey @geoman2 ,
Great news! Since Refine became Headless, it's no longer dependent on UI. We'll prepare an example and blog post with Partytown so thank you very much!!

**Comment by geoman2** [comment]
Hi @omeraplak , can I send here a feature request how to implement support for react native on top of the nextjs, with not much work Would be very welcome if this is implemented next? Refine and its API running on mobile will be fire ;)

I'm speaking about the solito project, developed by https://twitter.com/FernandoTheRojo, the author of many react native+web projects like Moti (animation based on Reanimated 2) and dripsy a design system running on mobile and web.
So please read how solito works here https://solito.dev/gradual-adoption (please read also the methodology chapter).
Regarding your most recent feature multi-level menu, is this the same as nested routes implemented in many frameworks like vue, solid, remix and react?
And the last question, is partytown feature not implemented yet?

**Comment by omeraplak** [comment]
Hey @geoman2,
I think it's a good idea! We've talked to the core team, but we're not sure if we can take the time to do this, we can prioritize this if we get enough requests from the Community. 

We'll be posting a blog post and sample about Partytown this week!

**Comment by omeraplak** [comment]
Hey @geoman2 ,
Added Partytown support to superplate! Thank you 🚀
