### ISSUE TITLE
[FEAT] CrudOperators  'between', 'nbetween', 'nnull' are required for using directus as dataprovider

### ISSUE THREAD

**Issue by tspvivek** [pankod/refine#1537]
**Is your feature request related to a problem? Please describe.**
When trying to custom dataprovider to use directus some crud operators supported by directus are missing in refine.

**Describe the solution you'd like**
Add commonly used directus operators like  'between', 'nbetween' and 'nnull' in CrudOperators type.
https://docs.directus.io/configuration/filter-rules/#filter-operators

**Describe alternatives you've considered**
Modifying CrudOperators type to any so that we can use our own operators depending on CMS we use.

**Comment by omeraplak** [comment]
Hey @tspvivek ,
We've release `@pankod/refine-core@3.1.2`. Thank you! 
btw, Do you plan to share it with the Community when Directus Data Provider is finished?

**Comment by tspvivek** [comment]
Hi @omeraplak  Yes, i am planning to share in community. 

For now i am facing few issue with refine which i am trying to resolve, like in nextjs inside pages/attendance/wfhapproval directory i created custom pages with resource prop value 'wfhapproval' and syncwithlocation enabled. When i open http://localhost:3000/attendance/wfhapproval, refine is redirecting to http://localhost:3000/wfhapproval?current=1&pageSize=10, Refine is using resource name 'wfhapproval' instead of current route 'attendance/wfhapproval', hwich ends in 404 error. 
We could not use subdirectory in nextjs due to this.
