### ISSUE TITLE
[BUG] useSimpleList in nextjs with syncWithLocation on, url is not getting appended with current and pageSize.

### ISSUE THREAD

**Issue by tspvivek** [pankod/refine#1539]
**Describe the bug**
Tried using useSimpleList in nextjs with syncWithLocation on. But the url is not getting appended with current and pageSize.

**To Reproduce**
`
const { listProps } = useSimpleList<IPost>({
    resource: "wfhapproval",
    syncWithLocation: true,
    queryOptions: {
      initialData,
    },
    pagination: {
      pageSize: 24
    }
  });
`

**Expected behavior**
url should be appended with current and pageSize.

**Comment by tspvivek** [comment]
After removing the code which disables syncWithLocation when custom resourceProp is included, syncWithLocation is working fine. Except the issue i mentioned in this comment https://github.com/pankod/refine/issues/1537#issuecomment-1038700511 which is common to both useTable and useSimpleList.

**Comment by omeraplak** [comment]
> After removing the code which disables syncWithLocation when custom resourceProp is included, syncWithLocation is working fine. Except the issue i mentioned in this comment [#1537 (comment)](https://github.com/pankod/refine/issues/1537#issuecomment-1038700511) which is common to both useTable and useSimpleList.

Hey @tspvivek, 
Yes, now I remember why we turn off `syncWithLocation` when using "resource" prop. 
The part that causes this is:
https://github.com/pankod/refine/blob/master/packages/core/src/hooks/useTable/index.ts#L144

We will discuss how we can improve this behavior. Do you have a suggestion?

**Comment by tspvivek** [comment]
@omeraplak You mean the extra render.

**Comment by omeraplak** [comment]
> @omeraplak You mean the extra render? Can we use shallow routing like https://nextjs.org/docs/routing/shallow-routing in nextjs? For react-router can we use history.replace() ?

The problem was not rendering, but using `resourceName` for routing. I created a PR #1542 . I hope there will be a merge soon :)

**Comment by tspvivek** [comment]
Great, Waiting try it. :)

**Comment by tspvivek** [comment]
@omeraplak Tested and Works great !!
