### ISSUE TITLE
Failed when running yarn dev or yarn build

### ISSUE THREAD

**Issue by arizkyana** [pankod/refine#1547]
Hello,

I have a problem when I run 

```
yarn dev
```

or 

```
yarn build
```

![image](https://user-images.githubusercontent.com/6881663/154017640-885442c8-d8a4-4784-b4dd-f94d666c23fd.png)

A couple of times of debugging, I found a strange behaviour. When I remove this line 
```
import "../styles/app.less"
```

It works normally and the app is running so well. 

Then, every time I run for development, I have to remove that line then put it again when the hot-reload feature is working.

But, my teammates have run the app normally. He works on Windows 10, I work on macOS. 

Are there some compatibility issues with the operating system?

**Comment by omeraplak** [comment]
Hey @arizkyana ,
Thank you for contact with us. Could you share the full error log?

**Comment by arizkyana** [comment]
> Hey @arizkyana , Thank you for contact with us. Could you share the full error log?

Hi @omeraplak , here the full error log

![image](https://user-images.githubusercontent.com/6881663/154020070-1eb0ff5c-85bd-49cc-87bf-00099f83111b.png)

**Comment by omeraplak** [comment]
Could you share node.js version?

**Comment by arizkyana** [comment]
> Could you share node.js version?

here is the node.js version

![image](https://user-images.githubusercontent.com/6881663/154030241-f5a04d7f-cda5-4871-b65d-e4615ebd8f98.png)

**Comment by arizkyana** [comment]
@omeraplak 

My workflows are : 

1. remove `import '../styles/app.less'`
2. run `yarn dev`
3. wait until logs show this information
```
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 3.7s (3683 modules)
```

4. put again import `app.less`
5. then the logs are changing to this

```
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 3.7s (3683 modules)
wait  - compiling...
error - uncaughtException: Error: read ECONNRESET
postcss-resolve-url: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[11].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[11].use[2]!./node_modules/next/dist/compiled/resolve-url-loader/index.js??ruleSet[1].rules[2].oneOf[11].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[2].oneOf[11].use[4]!./src/styles/app.less
Warning
```

**Comment by omeraplak** [comment]
I think it is due to Next.js + less incompatibility. We use this package for theme support, https://github.com/elado/next-with-less

maybe you can check out alternatives

**Comment by arizkyana** [comment]
> I think it is due to Next.js + less incompatibility. We use this package for theme support, https://github.com/elado/next-with-less
> 
> maybe you can check out alternatives

I use the same library with you.

```javascript
const withLess = require("next-with-less");
withLess.patchNext(require("next/dist/build/webpack/config/blocks/css"));

module.exports = withLess({
  reactStrictMode: true,
  compress: true,
  webpack5: true,
  lessLoaderOptions: {},
});
```

**Comment by omeraplak** [comment]
Hey @arizkyana ,
Does your problem persist?
