### ISSUE TITLE
[DOC] Improve Ant Design useTable sorting 

### ISSUE THREAD

**Issue by omeraplak** [pankod/refine#1559]
**Describe the thing to improve**
In the sorting process, first of all, the column's "key" property is used as the column name, if not exist, the "dataIndex" property is used. we should state this clearly in the docs.

Code: https://github.com/pankod/refine/blob/e6909125ea133b94340ce1411b5e8dab56f112e5/packages/antd/src/definitions/table/index.ts#L59

Doc: https://refine.dev/docs/ui-frameworks/antd/hooks/table/useTable/#sorting

**Comment by mlhekinci** [comment]
#1672
