### ISSUE TITLE
[BUG] Module '"@pankod/refine-antd"' has no exported member 'useGetIdentity'

### ISSUE THREAD

**Issue by FrancoAA** [pankod/refine#1571]
**Describe the bug**
I'm trying to do the tutorial but after initializing the application with superplate `npx superplate-cli -p refine-react <app_name>` and executing `npm run dev` I encounter with this error

>  Module '"@pankod/refine-antd"' has no exported member 'useGetIdentity'

**To Reproduce**
1. Create a new app using superplate `npx superplate-cli -p refine-react <app_name>` with the following configuration:

> ✔ Cloned remote source successfully.
> ✔ What will be the name of your app · refine-tutorial
> ✔ Do you want to using UI Framework?: · antd
> ✔ Do you want to customize theme?: · css
> ✔ Data Provider: · custom-json-rest-data-provider
> ✔ Auth Provider: · custom-auth-provider
> ✔ Do you want to add an example page? · example-resource
> ✔ Do you want to customize layout? · custom-layout
> ✔ i18n - Internationalization: · no

2. run `npm run dev` on the root folder of the recently created application
3. You should see the error on your terminal and the app crashing.

**Expected behavior**
Expect to see the app running on https://localhost:3000

**Additional context**
This is the generated package.json
```
{
  "name": "refine-tutorial",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.23",
    "@types/node": "^12.20.10",
    "@types/react": "^17.0.4",
    "@types/react-dom": "^17.0.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.0",
    "typescript": "^4.2.4",
    "web-vitals": "^1.1.1",
    "@pankod/refine-core": "^3.1.0",
    "@pankod/refine-react-router": "^3.1.0",
    "@pankod/refine-antd": "^3.1.0",
    "@pankod/refine-simple-rest": "^3.1.0",
    "react-markdown": "^6.0.1",
    "react-mde": "^11.1.0"
  },
  "scripts": {
    "dev": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by omeraplak** [comment]
Hey @FrancoAA ,
Thank you for contacting us. Could you try again?
