### ISSUE TITLE
[FEAT] Multi-level default sider

### ISSUE THREAD

**Issue by rassie** [pankod/refine#1580]
**Is your feature request related to a problem? Please describe.**
Not all resources are equally important and some are also intertwined. For example, `Comment`s might only make sense in the context of `Post`s, so that it might become semantically important to display them differently in the sider, e.g. in a multi-level list. 

**Describe alternatives you've considered**
Making a custom sider is possible, however I haven't checked whether it's possible to add necessary options to the resources' array to make this happen.

**Comment by omeraplak** [comment]
Hey @rassie ,
Thank you for the feature request! How would you like to manage multilevel menus with Refine? Do you have a structure suggestion?

**Comment by omeraplak** [comment]
Thank you @rassie ! Let's see what we can do!

**Comment by omeraplak** [comment]
Hey @rassie ,
We've released `3.9.0`. Thanks a lot for your help!
