### ISSUE TITLE
[BUG] onFinish doesn't work when used in a stepsForm

### ISSUE THREAD

**Issue by arthursfreitas** [pankod/refine#1594]
**Describe the bug**
When I have a steps Form and I need to use onFinish to modify the payload before sending the API, this doesn't happen. The form does not modify the payload.

**To Reproduce**
1. Go to an Editing Steps Form
2. Click to save edit
3. In your browser's network you can debug the payload sending
4. And verify that the payload has not been modified

**Expected behavior**
The sent payload is expected to have been modified by onFinish

**Screenshots**
![refine-use-steps-form-example (forked) - CodeSandbox - 26 February 2022](https://user-images.githubusercontent.com/24879499/155846524-f287ff89-0d9b-4204-909a-26793c018fd5.gif)

**Desktop (please complete the following information):**
 - OS: Linux Zorin OS 16
 - Browser: Chrome
 - Version Version 98.0.4758.80 (Official Build) (64-bit)
 - Used dataProvider: simpleRestDataProvider

**Additional context**
Link to codesandbox with example:
https://codesandbox.io/s/refine-use-steps-form-example-forked-3kww9e?file=/src/pages/posts/edit.tsx

**Comment by omeraplak** [comment]
Hey @arthursfreitas ,
Thank you for contacting us! Steps Form, due to its dynamic form structure, you cannot override values through the "Form" component.

You can override the submit button instead,

```
{current === formList.length - 1 && (
            <SaveButton
              {...saveButtonProps}
              onClick={() => {
                const values = form.getFieldsValue(true);
                submit({
                  ...values,
                  title: "test2"
                });
              }}
            />
          )}
```

https://codesandbox.io/s/refine-use-steps-form-example-forked-l6hi3l?file=/src/pages/posts/edit.tsx
