### ISSUE TITLE
[FEAT] Custom Landing Pages

### ISSUE THREAD

**Issue by Danjavia** [pankod/refine#1595]
**Is your feature request related to a problem? Please describe.**
I cannot to create a Landing page for managing all the website with only tool (Refine in this case)

**Describe the solution you'd like**
Would be nice that I can to set a custom page or pages and set custom routes when user is unauthorized

**Comment by omeraplak** [comment]
Hey @Danjavia ,
We've released 3.4.0. Could you approve this fix?

**Comment by Danjavia** [comment]
Awesome!!!, Thanks!!
