### ISSUE TITLE
[DOC] Found a Typo on Comparison Table

### ISSUE THREAD

**Issue by mayhs19** [pankod/refine#1603]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
Helpful info about this issue.
https://refine.dev/docs/comparison/ has a Typo "anyting" under "Supported UI Frameworks"

**Describe the thing to improve**
A clear and concise description of problems.
I would like to fix this Typo to make "anyting" as "anything" :) 

**Describe the solution (optional)**
Ideas about what we should do to improve experience of beginners and readers. It may be new pages to add, grammar fixes etc.
Grammar/Spelling fix:  Fix this Typo to make "anyting" as "anything" :)

**Comment by omeraplak** [comment]
Hey @mayhs19 ,
We are waiting for your PR. Thank you!

**Comment by omeraplak** [comment]
Hey @mayhs19 ,
We've fixed it now! Thank you!
