### ISSUE TITLE
[FEAT] Allow DELETE requests' payload (as per RFC 7231)

### ISSUE THREAD

**Issue by banuni** [pankod/refine#1635]
Not that often, but sometimes, one would like to add a payload/body to their DELETE requests - that is allowed according to [RFC 7231 / 4.3.5](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5):

>    A payload within a DELETE request message has no defined semantics;
>    sending a payload body on a DELETE request might cause some existing
>    implementations to reject the request.

 However, `useDelete`'s callback does not allow the passing of any data along.
I suggest adding this capability, just as in `useCreate`, `useUpdate` etc.

My specific usecase is telling the server whether this is a "soft" delete" or a "hard" delete

```ts
const { mutate: delete } = useDelete()
const deleteCategory = (catId) => delete({
    resource: "categories",
    id: catId,
    values: { hard: true },
})
const archiveCategory = (catId) => delete({
    resource: "categories",
    id: catId,
    values: { hard: false },
})
```

currently working around this via the metaData attribute in the provider:
```ts
// data-provider.ts
return {
    ...superDataProvider,
    deleteOne: ({ resource, metaData, id }) => {
      return httpClient
        .delete(`${baseUrl}/${resource}/${id}`, {
          data: metaData, // THIS IS A HACK-WORKAROUND TO MAKE DELTE WORK WITH BODY PARAMETERS
        })
        .then((r) => ({
          data: r.data,
        }));
    }
}
```

**Comment by omeraplak** [comment]
Hey @banuni ,
Thank you, let's see what we can do!

**Comment by omeraplak** [comment]
Hey @banuni ,
We've created PR #1700. I hope we will release it today!

**Comment by omeraplak** [comment]
Hey @banuni ,
We've released `3.12.0`! 🎉

**Comment by banuni** [comment]
@omeraplak Awesome! will update & use ASAP :)
thx!

**Comment by banuni** [comment]
@omeraplak - I added the use of this to the `simple-rest` data provider in a PR, hope it's ok: https://github.com/pankod/refine/pull/1707

**Comment by omeraplak** [comment]
> @omeraplak - I added the use of this to the `simple-rest` data provider in a PR, hope it's ok: #1707

Look's cool! Thank you 🎉
