### ISSUE TITLE
[BUG] Unexpected behavior of useDrawerForm

### ISSUE THREAD

**Issue by kmaguswira** [pankod/refine#1646]
**Describe the bug**
Hi guys, I've some questions when I tried to use `useDrawerForm` (v.3.6.3). I intended to use this hook to managing contextual data (like relations). so I use this hook in the page that use `useShow` to show the detail of the parent data, `useTable` to list the children, and `useDrawerForm` to create and edit the children. 

1. When I use this hook with action create, it show clone tag on the header, how can i remove this tag? And after i save it, and then click a create button again, it show the data that i've input before, can i reset this form?

2. When I use this hook with action edit. after I save the data, it will call an API to retrieve the updated data but with wrong id (it use parentId), I've set redirect to false on the options, but it still happen, is there a way to disable API call after update?

**Expected behavior**
1. The page header should be no `clone` tag, and after submit the form should be reset
2. After edit and submit, the id is should be the `childId` not the `parentId`

**Screenshots**
<img width="617" alt="Picture-1" src="https://user-images.githubusercontent.com/11132557/158410967-76ae8804-8103-449e-992d-c9ca0ee1bd37.png">

<img width="1079" alt="Picture-2" src="https://user-images.githubusercontent.com/11132557/158410948-e4448302-f408-4b00-b6e5-fa412f1d59de.png">

**Comment by omeraplak** [comment]
Hey @kmaguswira ,
Thank you! We've released `3.7.1`. Could you approve this fix?
