### ISSUE TITLE
[BUG] #405 error on localhost?

### ISSUE THREAD

**Issue by weisisheng** [pankod/refine#1657]
**Describe the bug**

Trying to use the example with email sign up exercise--> https://refine.dev/blog/e-mail-subscription-panel-with-refine/ and getting error, double checked the API URLs for frontend and backend.

**To Reproduce**
0. Updated all packages to latest
1. Go to login screen after setting up content and user on strapi
2. Click on login button
3. Error code "​POST http://localhost:1337/auth/local 405 (Method Not Allowed)"

**Expected behavior**
Login and finish rest of example

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Ubuntu 21.04
 - Browser [e.g. chrome, safari]  google chrome Version 99.0.4844.74 (Official Build) (64-bit)
 - Used dataProvider Strapi V4
 - Node.js v.17.3.0

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**

**Comment by omeraplak** [comment]
Hey @weisisheng ,
Thank you for contacting us. This tutorial was created using strapi-v3. You can get around this by looking at how we built the authProvider from our Strapi v4 example. https://github.com/pankod/refine/blob/master/examples/dataProvider/strapi-v4/src/App.tsx
