### ISSUE TITLE
[BUG] Does defaultValueQueryOptions and queryOptions serve the same purpose?

### ISSUE THREAD

**Issue by kfcaio** [pankod/refine#1673]
**Describe the bug**
Looking at [useSelect docs](https://refine.dev/docs/ui-frameworks/antd/hooks/field/useSelect/), I stumbled upon `queryOptions` and `defaultValueQueryOptions` props. Both refer to react-query [useQuery](https://reactquery.tanstack.com/reference/useQuery) options, however they have different behavior. It would be nice if documentation about them were more specific or if one of them were dropped.

**To Reproduce**
1. Go to https://refine.dev/docs/ui-frameworks/antd/hooks/field/useSelect/
2. Scroll down to Properties 

Also, I could not reproduce `defaultValueQueryOptions`. I've tried to run `console.log`when status of the query errored, but execution didn't reach my `onError: {() => console.log("foo")}` code inside `defaultValueQueryOptions`

**Desktop (please complete the following information):**
 - OS: MacOS X Monterey
 - Browser: Chrome
 - Version: 99.0.4844.84 (Official Build) (x86_64)
 - Used dataProvider: custom

**Comment by omeraplak** [comment]
Hey @kfcaio ,
We've released `3.10.1`

**Comment by kfcaio** [comment]
> Hey @kfcaio , We've released `3.10.1`

Thank you!
