### ISSUE TITLE
Server side validation example

### ISSUE THREAD

**Issue by misterx** [pankod/refine#1681]
Could you provide server side validation, please?

I have backend-based validation according to business rules. Backend returns 442 HTTP response code as error payload with JSON key-value array, where key is the problematic field name and value - the error description. 

I've tried to use `onMutationError` callback in `useForm` hook, there i can get errors but haven't form ref that's needed for setting errors according antd docs by `formRef.setFields()`

Also I have tried to use `onFinishFailed` prop in the `Form` component, but it isn't called when error.

How can i set server errors to form?

**Comment by omeraplak** [comment]
Hey @misterx 👋,
Thank you for contacting us
Have you checked Custom Form Validation example?

https://refine.dev/docs/examples/form/custom-form-validation/

**Comment by misterx** [comment]
@omeraplak yes, thanks. Example is covering a different flow, it's using pre-submit validation, but i need to display errors during submit process.

**Comment by misterx** [comment]
I've created some workaround for that, while waiting a better way

```typescript
import {BaseRecord, FormInstance, useForm} from "@pankod/refine-antd";
import {HttpError} from "@pankod/refine-core";
import {UseFormProps as UseFormPropsRefine} from "@pankod/refine-antd/dist/hooks/form/useForm";

export type UseFormProps<
    TData extends BaseRecord = BaseRecord,
    TError extends HttpError = HttpError,
    TVariables = {}
    > =  UseFormPropsRefine<TData, TError, TVariables> & {
    onMutationError?: (error: TError, variables: TVariables, context: any, formInstance:FormInstance) => void;
};

export const useFormWithInstance:typeof useForm = <
    TData extends BaseRecord = BaseRecord,
    TError extends HttpError = HttpError,
    TVariables = {},
    >(useFormProps: UseFormProps<TData, TError, TVariables>|undefined) => {

    let formInstance:FormInstance;

    const onMutationError = (error:TError,variables:TVariables,context:any)=> {
        if(useFormProps?.onMutationError){
            useFormProps.onMutationError(error,variables,context,formInstance)
        }
    }

    const useFormReturn = useForm({...useFormProps,onMutationError});
    formInstance = useFormReturn.form;
    return useFormReturn;
}
```

Btw, how i can import `UseFormProps` from `@pankod/refine-antd` instead `@pankod/refine-antd/dist/hooks/form/useForm` ?

**Comment by omeraplak** [comment]
Hey @misterx ,
When I tried this way, I succeeded. Is there a point I missed?
```
const { formProps, saveButtonProps, form } = useForm<IPost>({
        resource: "hede",
        onMutationError: () => {
            form?.setFields([
                {
                    name: "title",
                    errors: ["Any error!"],
                },
            ]);
        },
    });
```

**Comment by misterx** [comment]
@omeraplak Thanks, your solution is much better.
