### ISSUE TITLE
[BUG] Cannot disable login on homepage with custom page

### ISSUE THREAD

**Issue by bangdragon** [pankod/refine#1682]
**Describe the bug**
Cannot disable login on homepage with custom page

**To Reproduce**
Add route to router provider:
```
{
  element: <Dashboard/>,
  path: "", 
},
```
with no luck, and try:
```
{
  element: <Dashboard/>,
  path: "/", 
},
```
with no luck too.
**Expected behavior**
When enter homepage it should not show login. It should show dashboard page but it does not

**Additional context**
I use @pankod/refine-react-router-v6

**Comment by omeraplak** [comment]
Hey @bangdragon ,
Thank you for contacting us! I've created a CodeSandbox and it's working.
https://codesandbox.io/s/custom-pages-example-forked-rwpbyn?file=/src/App.tsx

Is there a point I missed?

**Comment by hasnain-cyber** [comment]
> Hey @bangdragon , Thank you for contacting us! I've created a CodeSandbox and it's working. https://codesandbox.io/s/custom-pages-example-forked-rwpbyn?file=/src/App.tsx
> 
> Is there a point I missed?

Hello sir, I am currently struggling with the same issue described above,  below is my code

`import { Refine } from "@pankod/refine-core";
import {
  notificationProvider,
  RefineSnackbarProvider,
  CssBaseline,
  GlobalStyles,
  Layout,
  ThemeProvider,
  LightTheme,
  ReadyPage,
  ErrorComponent,
} from "@pankod/refine-mui";

import dataProvider from "@pankod/refine-simple-rest";
import { MuiInferencer } from "@pankod/refine-inferencer/mui";
import routerProvider from "@pankod/refine-react-router-v6";
// import LandingPage from "pages/LandingPage/LandingPage";

function App() {
  const LandingPage = () => {
    return (
      <div>
        Landing page
      </div>
    )
  }

  return (
    <ThemeProvider theme={LightTheme}>
      <CssBaseline />
      <GlobalStyles styles={{ html: { WebkitFontSmoothing: "auto" } }} />
      <RefineSnackbarProvider>
        <Refine
          dataProvider={dataProvider(`${process.env.REACT_APP_API_URL}/courses`)}
          notificationProvider={notificationProvider}
          Layout={Layout}
          ReadyPage={ReadyPage}
          catchAll={<ErrorComponent />}
          // resources={[
          //   {
          //     name: "posts",
          //     list: MuiInferencer,
          //     edit: MuiInferencer,
          //     show: MuiInferencer,
          //     create: MuiInferencer,
          //     canDelete: true,
          //   },
          // ]}
          routerProvider={{
            ...routerProvider,
            routes: [
              {
                path: "/",
                element: <LandingPage />
              }
            ]
          }}
        />
      </RefineSnackbarProvider>
    </ThemeProvider>
  );
}

export default App;
`
For some reason, this does not spawn a landing page on '/' route, also please feel free to ask for additional context, and project details.

**Comment by hasnain-cyber** [comment]
> Hey @bangdragon , Thank you for contacting us! I've created a CodeSandbox and it's working. https://codesandbox.io/s/custom-pages-example-forked-rwpbyn?file=/src/App.tsx
> 
> Is there a point I missed?

Hello sir, I am currently struggling with the same issue described above,  below is my code

```import { Refine } from "@pankod/refine-core";
import {
  notificationProvider,
  RefineSnackbarProvider,
  CssBaseline,
  GlobalStyles,
  Layout,
  ThemeProvider,
  LightTheme,
  ReadyPage,
  ErrorComponent,
} from "@pankod/refine-mui";

import dataProvider from "@pankod/refine-simple-rest";
import { MuiInferencer } from "@pankod/refine-inferencer/mui";
import routerProvider from "@pankod/refine-react-router-v6";
// import LandingPage from "pages/LandingPage/LandingPage";

function App() {
  const LandingPage = () => {
    return (
      <div>
        Landing page
      </div>
    )
  }

  return (
    <ThemeProvider theme={LightTheme}>
      <CssBaseline />
      <GlobalStyles styles={{ html: { WebkitFontSmoothing: "auto" } }} />
      <RefineSnackbarProvider>
        <Refine
          dataProvider={dataProvider(`${process.env.REACT_APP_API_URL}/courses`)}
          notificationProvider={notificationProvider}
          Layout={Layout}
          ReadyPage={ReadyPage}
          catchAll={<ErrorComponent />}
          // resources={[
          //   {
          //     name: "posts",
          //     list: MuiInferencer,
          //     edit: MuiInferencer,
          //     show: MuiInferencer,
          //     create: MuiInferencer,
          //     canDelete: true,
          //   },
          // ]}
          routerProvider={{
            ...routerProvider,
            routes: [
              {
                path: "/",
                element: <LandingPage />
              }
            ]
          }}
        />
      </RefineSnackbarProvider>
    </ThemeProvider>
  );
}

export default App;
```
For some reason, this does not spawn a landing page on '/' route, also please feel free to ask for additional context, and project details.
