### ISSUE TITLE
[DOC] Update "Setting Authorization Credentials"

### ISSUE THREAD

**Issue by IanSaucy** [pankod/refine#1683]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
The authorization credential part of the docs is a little vague. I think it would be useful for beginners to have more complete documentation. 

[Setting Authorization Credentials](https://refine.dev/docs/core/providers/auth-provider/#setting-authorization-credentials)

**Describe the thing to improve**
The importance of a singular Axios instance and other methods for setting credentials.

**Comment by omeraplak** [comment]
Hey @IanSaucy ,
Congrats. It's much more descriptive. I think the Token example is sufficient because in general API authentications work in similar ways
