### ISSUE TITLE
[FEAT] Optional invalidation of query cache after the mutation is successful for useUpdate hook

### ISSUE THREAD

**Issue by mayank-meragi** [pankod/refine#1687]
**Is your feature request related to a problem? Please describe.**
I am trying to implement autosave feature, but after every save, the data gets reloaded because of which the form get loaded with data. This makes the fields loose focus and there is a slight jump in the data as well. I would like to update the form in the background silently without any re-renders in the ui

**Describe the solution you'd like**
I think making the invalidation controllable with a flag should solve the issue. For all these autosave, I would set the invalidation to false, and for all the other use case can still invalidate and work as usual

**Comment by omeraplak** [comment]
Hey @mayank-meragi ,
I've created draft PR #1690 . You can follow the development through this PR

**Comment by omeraplak** [comment]
Hey @mayank-meragi ,
We've released `3.11.0`. You can use like this;
```
useUpdate({
...
invalidates: false
});
```
