### ISSUE TITLE
[FEAT] Can not custom the operator for FilterDropdown when use in Table

### ISSUE THREAD

**Issue by hiko-vietduong** [pankod/refine#1691]
**Is your feature request related to a problem? Please describe.**
I can not custom the operator, it's always build to `_eq` compare

**Describe the solution you'd like**
I think should have a property allow us pass the operator into Filter and a function to custom value pass to Filter (e.g: can update the value into `%value%` to get string contains)

**Additional context**
This is my code:
```
const FilterDropdownOpt = (props: FilterDropdownProps) => (
  <FilterDropdown {...props}>
    <Input />
  </FilterDropdown>
);
```
And it always build the `_eq` query
![image](https://user-images.githubusercontent.com/79821926/161878678-e80b4bd4-dd4f-4538-8fb5-b9c63163ab21.png)

**Comment by omeraplak** [comment]
Hey @hiko-vietduong 👋,
Thank you for contacting us! 
Unfortunately, this is not possible now but maybe this Issue can inspire you.

https://github.com/pankod/refine/issues/1373
