### ISSUE TITLE
[BUG] Filters can only be applied immediately

### ISSUE THREAD

**Issue by rassie** [pankod/refine#1711]
**Describe the bug**

This can be easily described by a screencap. Filters won't apply if the popup has been dismissed. Only filters with immediate application will work.

https://user-images.githubusercontent.com/23448/162918225-8cd1a7e8-f665-493d-a258-caeb5f420f19.mp4

**Comment by omeraplak** [comment]
Hey @rassie ,
Thank you, let's see what we can do! 🎉

**Comment by omeraplak** [comment]
Hey @rassie ,
We've released [`3.14.1`](https://github.com/pankod/refine/releases/tag/v3.14.1). Could you approve this fix?

**Comment by rassie** [comment]
Thanks! I'll check it out as soon as I can (still Easter holidays where I live).

**Comment by omeraplak** [comment]
happy Easter 🎉

**Comment by rassie** [comment]
Can confirm, my use case works fine now. Thanks!
