### ISSUE TITLE
How can I generate automatic typescript types, with Hasura and graphql-codegen [Question]

### ISSUE THREAD

**Issue by nirmaanlabs** [pankod/refine#1713]
I was following Hasura automatic type generation for React/Angular Apps. It seems that `code-gen` takes all the query and mutation and introspection and then it generates typescript  type defs. 

https://hasura.io/learn/graphql/typescript-react-apollo/codegen/

In refine since I don't have to write query and mutation, how can I generate typescript type definition file.
As of now I am writing all possible query and mutation.

I am using create react app and refine as npm deps

**Comment by omeraplak** [comment]
Hey @nirmaanlabs 👋,
Thank you for contacting us.I will look into it for you.

Hey @BatuhanW, do you have any idea?

**Comment by omeraplak** [comment]
Hey @nirmaanlabs ,
I guess there is no way to create Typescript types without queries. Did you find a way

**Comment by nirmaanlabs** [comment]
@omeraplak 
No I did not find a good solution for now. 

For now I have to add all the query and mutation in `.graphl` file so that it can generate it types

1. If you could somehow expose the function which build query and mutation internally, or a function which output query and mutation file ?

Can you share me the the code file, which is responsible for generating or making query and mutations by introspection ?

Also I tried to a find a tool, which does introspection and generates query and mutation, but I could not, also hasura has it's query name and mutation name defined in very specific way

Thanks

**Comment by omeraplak** [comment]
Unlike GraphQL clients, Refine does not use introspection. Our approach is to generate a query. We think this approach is much more manageable, but not being able to auto generate TypeScript types is a big miss...

Data providers are responsible for creating the queries.
for example,
https://github.com/pankod/refine/blob/master/packages/graphql/src/index.ts#L63

**Comment by nirmaanlabs** [comment]
@omeraplak just updated my comments

**Comment by nirmaanlabs** [comment]
@omeraplak If I may suggest , the `operationName` was missing from mutation, I think it will be better if operation name is also sent along with it, because I just copied my mutation from network tab and pasted it, without `operationName` it somehow fails to generation types properly

**Comment by nirmaanlabs** [comment]
> but



> Hey @nirmaanlabs, Unlike GraphQL clients, Refine does not use introspection. Our approach is to generate a query. We think this approach is much more manageable, but not being able to auto-generate TypeScript types is a big miss...
> 
> Data providers are responsible for creating the queries. for example, https://github.com/pankod/refine/blob/master/packages/graphql/src/index.ts#L63

@omeraplak
Is there any faster approach I can use ? Meanwhile I am trying to find a way to generate possible queries and mutations

**Comment by omeraplak** [comment]
In our example, we manage interfaces manually. An example line where this definition works is,

https://codesandbox.io/s/refine-hasura-example-790ew?from-embed=&file=/src/pages/posts/list.tsx:2105-2171

> If I may suggest , the operationName was missing from mutation, I think it will be better if operation name is also sent along with it, because I just copied my mutation from network tab and pasted it, without operationName it somehow fails to generation types properly

We send `operationName` to mutations. Am I missing something?
https://github.com/pankod/refine/blob/master/packages/hasura/src/index.ts#L212

> Is there any faster approach I can use ? Meanwhile I am trying to find a way to generate possible queries and `mutations`

I'm afraid there is no faster way

**Comment by nirmaanlabs** [comment]
> 

@omeraplak sorry It's `queryName` 
example

This is how it was in network tab

```
mutation ($object: temp_post_insert_input!) {
  insert_temp_post_one(object: $object) {
    id
    content
  }
}

Then I changed it into

```
mutation insert_temp_post_one($object: temp_post_insert_input!) {
  insert_temp_post_one(object: $object) {
    id
    content
  }
}
```

**Comment by nirmaanlabs** [comment]
> has to be named manually

@omeraplak Is it possible I may run into any issue If i used autogenerated type ?

**Comment by omeraplak** [comment]
> > has to be named manually
> 
> @omeraplak Is it possible I may run into any issue If i used autogenerated type ?

You won't have any problems. If you succeed, can you share it with us?

**Comment by nirmaanlabs** [comment]
@omeraplak yes definitely. Let me first try how to generate all possible queries and mutation
Thanks
