### ISSUE TITLE
[BUG] Multi-level routing does not work under next.js

### ISSUE THREAD

**Issue by smparekh** [pankod/refine#1714]
**Describe the bug**
Due to the way next.js routing is setup: [resource]->[action]->[id], multi-level routing breaks when trying to access a resource under a parent resource

**To Reproduce**
1. Clone and run `yarn dev` on https://github.com/smparekh/refine-test
2. Click on 'CMS'
3. Click on 'Posts'
4. Posts will not be displayed as expected

**Expected behavior**
When routing to a resource under a parentResource it should still handle it the same way as a top-level menu item

**Screenshots**
WITH POSTS UNDER CMS:

<img width="1434" alt="Screen Shot 2022-04-12 at 18 49 12" src="https://user-images.githubusercontent.com/2242057/163067135-e9fd7dc2-9470-4192-85ae-8d129bd50977.png">

WITH POSTS AT TOPLEVEL:
<img width="1440" alt="Screen Shot 2022-04-12 at 18 50 35" src="https://user-images.githubusercontent.com/2242057/163067355-f466fca6-4213-4ee1-aa25-a04fa02aa2c6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 
 - Used: supabase, next.js, antd, custom layout

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**
```
@pankod/refine-antd@3.12.2
│  ├─ @ant-design/icons@^4.5.0
│  ├─ @pankod/refine-core@^3.12.1
│  ├─ antd@^4.17.1
│  ├─ dayjs@^1.10.7
│  ├─ react-markdown@^6.0.1
│  ├─ react-query@^3.19.2
│  ├─ remark-gfm@^1.0.0
│  ├─ sunflower-antd@1.0.0-beta.3
│  └─ tslib@^2.3.1
├─ @pankod/refine-core@3.12.1
│  ├─ export-to-csv-fix-source-map@^0.2.1
│  ├─ humanize-string@^2.1.0
│  ├─ lodash-es@^4.17.21
│  ├─ lodash@^4.17.21
│  ├─ papaparse@^5.3.0
│  ├─ pluralize@^8.0.0
│  ├─ qs@^6.10.1
│  ├─ react-query@^3.19.2
│  └─ tslib@^2.3.1
├─ @pankod/refine-nextjs-router@3.12.1
│  ├─ @pankod/refine-core@^3.12.1
│  └─ qs@^6.10.1
├─ @pankod/refine-supabase@3.12.1
│  ├─ @pankod/refine-core@^3.12.1
│  └─ @supabase/supabase-js@^1.22.4
```

**Comment by omeraplak** [comment]
Hey @smparekh ,
Thanks for the issue. It'll take some time to fix this. We are currently working on our Remix support.

**Comment by smparekh** [comment]
@omeraplak I did find a workaround by updating the sider code, not sure if this would be the final fix:

https://github.com/smparekh/refine-test/commit/95f8d479d5ea7c7f9940993603d3f08fe63c57ae#diff-95aeff52219693db176376e7afbf6af570d9d1431b61b2e940d8283a24ee1f2b

This enables routing to work as normal even for keys under a single parent (haven't tested it for deeper children).

**Comment by smparekh** [comment]
Actually the sider change screws up the create/edit/show functionality. A better fix would be to just specify the route under options in _app.tsx:

```
{
  name: "posts",
  parentName: "CMS",
  list: PostList,
  create: PostCreate,
  // This will ensure multi-level menu works with next.js routing!
  options: {
    route: "/posts"
  }
}
```

I think we should update the documentation to make users aware of this.

**Comment by omeraplak** [comment]
Hey @smparekh ,
As far as I can see, "Sider" component and theme are outdated in projects created with superplate. We'll update this and your changes won't be needed. @biskuvit, can you take care of it?

Doc: https://refine.dev/docs/ui-frameworks/antd/hooks/resource/useMenu/#recreating-the-default-sider-menu Source code: https://github.com/pankod/refine/blob/master/packages/antd/src/components/layout/sider/index.tsx#L27
Theme: https://github.com/pankod/refine/blob/master/packages/antd/src/assets/styles/custom-theme.less

Secondly, Next.js, Unfortunately, does not have a flexible routing structure, so it is left to Next.js users to manage routing. Would you like to add the warning you specified to this document?
https://refine.dev/docs/guides-and-concepts/multi-level-menu/multi-level-menu/

**Comment by biskuvit** [comment]
Hey @smparekh,
Thank you for reporting a bug. I fixed your issue. Can you try again?

**Comment by smparekh** [comment]
@omeraplak - I can make the update to the document

@biskuvit - What was the update to? refine or superplate?

thanks

**Comment by omeraplak** [comment]
> @omeraplak - I can make the update to the document
> 
> @biskuvit - What was the update to? refine or superplate?
> 
> thanks

Hey @smparekh ,
We've updated superplate. Thank you!
