### ISSUE TITLE
[FEAT] Nested resources

### ISSUE THREAD

**Issue by eliasfeijo** [pankod/refine#1724]
I have an API endpoint that goes like: `/api/admin/stores/:store_id/employees/:id`
Where `:store_id` and `:id` can both be an integer.

I would like to be able to create nested resources like this (for example: Employees resources that belongs to a specific Store).

I don't know if this is possible with the current multi-level menu, I've checked the documentation but it doesn't include the `:store_id` part in the URL, nor in the hooks (useList, etc) API requests.

Does anyone know how to implement this feature with the current version of refine? Or is it impossible right now?

My suggestion would be to approach this with a React Context, storing the selected `:store_id` (from a Select input, for example), and passing as a parameter to the resource, but I'm guessing the only way to do this is by creating a Custom Page and implement the API request with axios or something.

I'm using these dependencies in my package.json (basically refine + react + typescript + antd), and I've deleted my yarn.lock and reinstalled just now, so I could get the most recent version (right now in my yarn.lock has `"@pankod/refine-core" "^3.14.0"`):

```
"dependencies": {
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.23",
    "@types/node": "^12.20.10",
    "@types/react": "^17.0.4",
    "@types/react-dom": "^17.0.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^5.0.0",
    "typescript": "^4.2.4",
    "web-vitals": "^1.1.1",
    "@pankod/refine-core": "^3.1.0",
    "@pankod/refine-react-router-v6": "^3.3.0",
    "@pankod/refine-antd": "^3.1.0",
    "@craco/craco": "^6.1.2",
    "craco-less": "^2.0.0",
    "@pankod/refine-simple-rest": "^3.1.0",
    "react-markdown": "^6.0.1",
    "react-mde": "^11.1.0",
    "i18next": "^20.1.0",
    "react-i18next": "^11.8.11",
    "i18next-browser-languagedetector": "^6.1.1",
    "i18next-xhr-backend": "^3.2.2"
  },
```

**Comment by omeraplak** [comment]
Hey @eliasfeijo 👋,
Actually the nested resource is only used for UI (example Sider component). All hooks like useForm, useTable, useCreate take "resource" parameter. You can use "resource" parameter like API path.

example;
useTable({
resource: 'api/admin/stores/{STORE_ID}/employees/{ID}'
});
I hope it was useful for you 🚀

**Comment by eliasfeijo** [comment]
Thank you @omeraplak!!! I've succeeded in making the nested resource API call using the `resource` parameter of `useTable`, just as you've suggested. I've implemented an AppContext that stores the `:store_id` when the user select from a list, and then I use the :store_id in a custom page that calls the nested API resource.

I was confused before because I thought that I needed the URL in the same format (in the admin application), like in the API (`/stores/:store_id/employees/:id`). But that is unnecessary in the frontend, I ended up creating a Custom Page with a simple route `/employees` in the end.

I don't know if it makes sense to put this kind of logic inside the library itself, so I guess it's the frontend developer's job to implement the code manually with refine and react. I don't really see any other solution for this issue, but I might be wrong, so I'm open to suggestions.

Probably there's a better pattern to do the same thing that I did, so I won't close the issue right now, because maybe someone could propose a better solution than my own. But feel free to close the issue if you think there's no point on keeping this conversation going. =)

**Comment by omeraplak** [comment]
Our general approach is not to spend too much energy on problems that can be solved with existing APIs without too much effort. Maybe we should create a FAQ page to include such questions and their answers! Thank you so much! ❤️

**Comment by rners01** [comment]
> useTable

Can you please give example of how to utilize `resource: 'api/admin/stores/{STORE_ID}/employees/{ID}'`?
If I have dynamic `STORE_ID` and `ID` then where to get them from?

**Comment by omeraplak** [comment]
> > useTable
> > @omeraplak
> > Can you please give example of how to utilize `resource: 'api/admin/stores/{STORE_ID}/employees/{ID}'`?
> > If I have dynamic `STORE_ID` and `ID` then where to get them from?
> > Im using `DataGrid` from `@mui/x-data-grid`

Hey,
If you are using URL parameters for your dynamic parameters, you can use the `useParsed` hook. https://refine.dev/docs/routing/hooks/use-parsed/#params

**Comment by rners01** [comment]
> > > useTable
> > > @omeraplak
> > > Can you please give example of how to utilize `resource: 'api/admin/stores/{STORE_ID}/employees/{ID}'`?
> > > If I have dynamic `STORE_ID` and `ID` then where to get them from?
> > > Im using `DataGrid` from `@mui/x-data-grid`
> 
> Hey, If you are using URL parameters for your dynamic parameters, you can use the `useParsed` hook. https://refine.dev/docs/routing/hooks/use-parsed/#params

Hey, thanks for the quick reply
(In general I haven't found any example of how to setup nested resources, especially with nested list/edit pages)

my problem is with nested resources
For example edit nested resource on save redirects from
`api/admin/stores/{some_store_id}/employees/{some_employee_id}/edit`
to
`api/admin/stores/{some_employee_id}/employees/{some_employee_id}`

Also if I have nested resource with `list` page then I don't have back button or breadcrumb as it treats this resource `employees` as standalone
`api/admin/stores/{some_employee_id}/employees?pageSize=25&current=1`

my `<Refine resources= />` setup

`[
                {
                  name: 'stores',
                  list: '/stores',
                  show: '/stores/:id',
                  edit: '/stores/:id/edit',
                },
{
                  name: 'employees',
                  list: '/stores/:id/employees',
                  show: '/stores/:id/employees/:id',
                  edit: '/stores/:id/employees/:id/edit',
                  meta: {
                    dataProviderName: 'employees',
                    hide: true,
                  },
                }]`

**Comment by rners01** [comment]
Hey @omeraplak, is it worth to create separate issue?

**Comment by aliemir** [comment]
Hey @rners01, the issue is when you define your routes in resource definitions you used `/:id` for defining both of the variables/parameters which should not be the same. You may want to replace the first `/:id` to something like `/:storeId` and provide `storeId` value in your meta properties or it will still be propagated if there's already a parameter defined in your router params as `storeId`. 

Check out the docs I'm sharing below to have a better understanding how nested routes and navigation work with Refine. Feel free to open up a new issue if you encounter any bugs or errors about this.

Defining nested routes with multiple parameters: https://refine.dev/docs/guides-concepts/multi-tenancy/#configuring-multi-tenant-routes

Using `meta` to provide route parameters: https://refine.dev/docs/ui-integrations/ant-design/components/buttons/show-button/#meta

Passing `meta` when using `useNavigation` hook: https://refine.dev/docs/routing/hooks/use-navigation/#return-values-1

Using `meta` when using `useGo` hook: https://refine.dev/docs/routing/hooks/use-go/#with-resource

When composing routes/navigation, Refine will look for the provided `meta` value, the `meta` value from the resource definition and also the `params` from the router and if any of these provide the required parameter Refine will use it when handling navigation and route matching.
