### ISSUE TITLE
[BUG] The base app doesn't work with React 18, missing children prop.

### ISSUE THREAD

**Issue by pabloalcaraz** [pankod/refine#1725]
**Describe the bug**
The app doesn't work with React 18, the propertie "children" is mising in types of refine-antd and refine-core components that use.

**To Reproduce**
Update to react 18 on package.json and start the app.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474775/163717759-06972bc2-f2d9-4543-b512-edf234048b33.png)

**Comment by omeraplak** [comment]
Hey @pabloalcaraz 👋,
Many of our dependencies haven't released React@18 support as `latest` yet. These are `ant-design`, `react-testing-library` and `react-query`. We are tracking all our dependencies and will upgrade to React@18 as soon as possible.

Possible workarounds are listed here,
https://github.com/facebook/react/issues/24304

Refine React@18 PR: https://github.com/pankod/refine/pull/1718

**Comment by omeraplak** [comment]
Our general approach is not to spend too much energy on problems that can be solved with existing APIs without too much effort. Maybe we should create a FAQ page to include such questions and their answers! Thank you so much! ❤️
