### ISSUE TITLE
[BUG] Appwrite Storage Error

### ISSUE THREAD

**Issue by quanganh206** [pankod/refine#1733]
**Describe the bug**

**To Reproduce**
1. Go to dataProvider Apprwite example
2. try to create new Product
3. Upload image

<img width="1792" alt="Screen Shot 2022-04-19 at 20 26 24" src="https://user-images.githubusercontent.com/12064619/164015540-5879f001-94b6-476e-b9b6-3eb3ac035292.png">
<img width="889" alt="Screen Shot 2022-04-19 at 20 26 56" src="https://user-images.githubusercontent.com/12064619/164015527-779d2df6-451d-4658-b34d-e4eb316c9ad4.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser chrome
 - Version 100.0.4896.127
 - Used dataProvider Appwrite

**Additional context**
Appwrite Storage now has a new interface with Bucket and current createFile interface not compatible with new storage's interface. 

Ref. https://dev.to/appwrite/announcing-appwrite-013-with-major-upgrades-to-storage-and-functions-3hpf

**Comment by omeraplak** [comment]
Hey @quanganh206 ,
I think it will be enough to update the Appwrite package. I will try to revive this PR!
https://github.com/pankod/refine/pull/1516

**Comment by quanganh206** [comment]
@omeraplak yes, I think so. @refine-appwrite has a nice exposed native function from Appwite.

**Comment by omeraplak** [comment]
Hey @quanganh206 ,
We've released `@pankod/refine-appwrite@3.14.2`. You can check upload example, 
https://github.com/pankod/refine/blob/master/examples/dataProvider/appwrite/src/pages/posts/create.tsx#L98

**Comment by quanganh206** [comment]
Great work @omeraplak, love Refine support so much!
