### ISSUE TITLE
[DOC] Dependent Queries 

### ISSUE THREAD

**Issue by thatjosh** [pankod/refine#1735]
## Is this issue related to an existing part of the documentation? If so, please provide a link

1. Added helpful info on using dependent queries from React Query.
2. Refine documentation page: https://refine.dev/docs/core/hooks/data/useMany/
3. React query documentation page: https://react-query.tanstack.com/guides/dependent-queries

## Describe the thing to improve
Dependent query is useful in a case where there are queries that depend on a preceding query's results.  This can be added to the Refine documentation to make the documentation more robust.

Personally, I ran into a problem where I had 5 queries, 4 of which depend on the first query's result. What happens is all 5 queries appear to run synchronously on load and 4 error messages popped up once before running successfully for the second time. The random error messages popping up can be distracting for the end user. This issue can be resolved with the use of dependent queries from React Query's useQuery options. 

## Describe the solution (optional)

I can create a pull request and add the following to the documentation: 

:::tip
`useQuery` options also allows you to implement dependent query whereby a query is only executed after a particular query result is fetched. This is particularly useful if you have queries that are dependent on the query results of a preceding query.  

[Refer to react-query docs on **dependent queries** for more information.](https://react-query.tanstack.com/guides/dependent-queries)

-   Suppose you want this query to run after `id_query_result` is fetched by a preceding query, you can set  `enabled` to `!!id_query_result`. 

```tsx
const categoryQueryResult = useMany<ICategory>({
    resource: "categories",
    ids: ids_query_result,
    queryOptions: { enabled: !!id_query_result },
});
```
:::

<br />

**Comment by omeraplak** [comment]
Hey @thatjosh ,
Thank you! When I reviewed our tutorial, I saw that this information was given on the List page.
https://refine.dev/docs/ui-frameworks/antd/tutorial/#creating-a-list-page

Would it be better to make this warning more specific in the tutorial instead of adding it to the `useMany` hook?

**Comment by thatjosh** [comment]
Hello @omeraplak,
Thank you for the prompt response as well as taking the time to review this! I think you have a better perspective on how the information should be outlined in the documentation! As a beginner & an end user, it didn't occur to me that this information was on this page, so perhaps it might be a good idea for the information to be more accessible with the search function. That could perhaps be achieved by making this more specific.

**Comment by omeraplak** [comment]
maybe it's time we did the FAQ document :) thanks for lighting the fire :)

**Comment by thatjosh** [comment]
Alrighty then! Should I close the issue?

**Comment by omeraplak** [comment]
Hey @thatjosh ,
You can create an FAQ page for us if you want. This could be the first item on the FAQ page :)

**Comment by omeraplak** [comment]
Hey @thatjosh ,
We've created [FAQ](https://refine.dev/docs/faq/) page. You can add it to this page :)

**Comment by thatjosh** [comment]
Thanks so much @omeraplak, I've added it to the FAQ and created a pull request here: https://github.com/pankod/refine/pull/1758 

:D

**Comment by omeraplak** [comment]
> Thanks so much @omeraplak, I've added it to the FAQ and created a pull request here: #1758
> 
> :D

Hey @thatjosh 👋,
Looks so cool! Thank you!
