### ISSUE TITLE
[FEAT] Add support for "id" prop in "useForm" hook

### ISSUE THREAD

**Issue by eliasfeijo** [pankod/refine#1745]
Refine already supports the `id` parameter in `useShow` hook, but not in the `useForm` hook. Currently, the only way to specify the resource's `id` in `useForm` is by calling the method `setId` that is returned by the hook. 

My use case is: I want to create an edit form, in a Custom Page. It would be easier if I could only specify the resource's `id` directly in the `useForm` hook, instead of calling the `setId` method somewhere in the component (I'm currently calling `setId` inside an `useEffect` hook).

This feature was discussed previously in a similar issue: https://github.com/pankod/refine/issues/1729#issuecomment-1102137974, and it seems to be possible to implement, as the `useShow` hook already supports the parameter `id`.

**Comment by omeraplak** [comment]
Hey @eliasfeijo 👋,
I've created PR #1749 . We'll release it soon! Thank you

**Comment by omeraplak** [comment]
Hey @eliasfeijo 👋,
We've released `3.16.0`. https://github.com/pankod/refine/releases/tag/v3.16.0  🎉
