### ISSUE TITLE
[BUG]Pagination does not take over filter conditions

### ISSUE THREAD

**Issue by nrikiji** [pankod/refine#1746]
**Describe the bug**
https://example.admin.refine.dev/orders

If I click on a page number after filtering by criteria on this screen, the RestAPI does not request the filtering criteria.

How to reproduce.

https://user-images.githubusercontent.com/4780752/164377041-6857ac45-d501-4bd5-a36e-e469f5e0c3d5.mov

**Comment by omeraplak** [comment]
Hey @nrikiji ,
We've released `3.15.1`. Could you approve this fix?

**Comment by nrikiji** [comment]
Thank you. I have confirmed that it has been fixed.
