### ISSUE TITLE
[DOC] Update comparison table with react-admin v4

### ISSUE THREAD

**Issue by arnaudvergnet** [pankod/refine#1756]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
https://refine.dev/docs/comparison/

**Describe the thing to improve**
This table compares Refine with other frameworks such as react-admin. A new react-admin version (v4) was [released a few days ago](https://github.com/marmelab/react-admin/releases/tag/v4.0.0). This is a near complete rewrite changing a lot behind the scenes so the table is now outdated.

**Describe the solution (optional)**
Some changes include the state management and the dev tools as they do not use redux and switched to react-query. I did not take the time to analyze all the changes but you can find the full changelog here: https://github.com/marmelab/react-admin/releases/tag/v4.0.0

**Comment by omeraplak** [comment]
Hey @arnaudvergnet ,
Thank you. We've updated with https://github.com/pankod/refine/commit/291cce56fe4ca21c9f15f3ae4a81b75eede32f6f.

We have not reviewed all of the changes. If you see something wrong, please let me know 🚀
