### ISSUE TITLE
[BUG] Infinite loading when provided initialData to useTable

### ISSUE THREAD

**Issue by AndrejG231** [pankod/refine#1776]
When providing initialData to useTable hook and setting staleTime to Infinity, there is an infinite loading screen. The loading state in tableProps is always true.

The query should not be loading at all when passing initialData when infinite stale time.

**Comment by omeraplak** [comment]
Hey @AndrejG231 👋,
Thank you for contacting us! Let's see what we can do! 🚀 As a workaround can you manage the loading state yourself?

**Comment by omeraplak** [comment]
I guess for this case it is much better for the user to manage the loading state. I couldn't find a way to handle the two situations. Any ideas? https://github.com/pankod/refine/blob/master/packages/antd/src/hooks/table/useTable/useTable.ts#L157
