### ISSUE TITLE
[BUG] Checkboxes on a form won't submit a false value 

### ISSUE THREAD

**Issue by rbnswartz** [pankod/refine#1779]
**Describe the bug**
I have a create form that has a checkbox on it. If I submit the form the boolean value isn't submitted. If I check the box and uncheck it again it

**To Reproduce**
1. Create a form with a create form on it and a checkbox form item with the rest api provider
2. Submit the form without checking the checkbox
3. No value for the field is submitted

**Expected behavior**
A false value is submitted to the api

**Screenshots**
![Form](https://user-images.githubusercontent.com/724704/166618554-cab893e3-3a47-45b9-9011-d2b0fd909d04.png)

The value is missing from the request being posted to the api

![image](https://user-images.githubusercontent.com/724704/166618640-c0d0539d-dd79-488c-9750-3f1b482f276c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser edge
 - Version 100.0.1185.50
 - Used dataProvider REST

**Additional context**
Using refine and refine-antd version 3.16.2

**Comment by omeraplak** [comment]
Hey @rbnswartz 👋,
Thank you for contacting us! 🚀 For Checkboxes you have to set "valuePropName" in "Form.Item" Component

Example;

<Form.Item
                    label="Active"
                    name="Active"
                    valuePropName="checked"
                >
                    <Checkbox />
                </Form.Item>

**Comment by rbnswartz** [comment]
@omeraplak Thanks for the reply. I already have that in place. If I check the checkbox and then uncheck it then it will submit a false value otherwise it won't submit a value at all
![image](https://user-images.githubusercontent.com/724704/166669940-3dafc2e2-01bf-48d7-8b44-c0fd026a0cdd.png)

**Comment by omeraplak** [comment]
> @omeraplak Thanks for the reply. I already have that in place. If I check the checkbox and then uncheck it then it will submit a false value otherwise it won't submit a value at all ![image](https://user-images.githubusercontent.com/724704/166669940-3dafc2e2-01bf-48d7-8b44-c0fd026a0cdd.png)
> 
> Perhaps I'm missing something else?

hmmm can you create a simple CodeSandbox for us? Thank you! 🚀

**Comment by omeraplak** [comment]
Hey @rbnswartz 👋,
When I searched in Ant Design issues, I found that the form should be given `initalValues` as a solution. 

like this;
```
 <Form
        {...formProps}
        initialValues={{
          active: false
        }}
      >
```

Also I created CodeSandbox for you,
https://codesandbox.io/s/refine-use-form-example-forked-z19qzi?file=/src/pages/posts/create.tsx:1058-1115

I hope it helps for you 🎉

**Comment by rbnswartz** [comment]
@omeraplak Yup that was exactly what I needed. Thank you so much for your help.
