### ISSUE TITLE
[BUG] Module not found: Error: Can't resolve 'rc-picker/lib/generate/dayjs' in '/Users/.../refine_tutorial/node_modules/@pankod/refine-antd/dist/esm'

### ISSUE THREAD

**Issue by maethub** [pankod/refine#1793]
**Describe the bug**
I'm trying to do the tutorial as described on the tutorial page. Unfortunately, I end up with the following error when running `npm run dev` in the freshly created project.

```
ERROR in ./node_modules/@pankod/refine-antd/dist/esm/index.js 978:0-46
Module not found: Error: Can't resolve 'rc-picker/lib/generate/dayjs' in '/Users/.../refine_tutorial/node_modules/@pankod/refine-antd/dist/esm'
```

**To Reproduce**
1. `npx superplate-cli -p refine-react tutorial`
2. `cd tutorial`
3. `npm install`
4. `npm run dev`
5. See error

**Expected behavior**
The tutorial should start without an error.

**Screenshots**
<img width="1410" alt="CleanShot 2022-05-11 at 12 57 23@2x" src="https://user-images.githubusercontent.com/9783664/167834011-a831f0a8-da96-459a-9d29-58aaa0e82f18.png">

**Desktop:**
 - OS: macOS Monterey
 - Browser: Brave
 - Node: v16.13.0
 - Used with UI, with REST API and Custom Authorization

I don't know how to fix it... 
Thanks for any hints or solutions!

**Comment by omeraplak** [comment]
Hey @maethub 👋,
Thank you for contacting us. I tried but couldn't reproduce the problem :( Can you delete package-lock and node_modules and try again?

**Comment by maethub** [comment]
Hi @omeraplak,

Thanks for the quick response. 

A clean installation of the dependencies (as you proposed) did not resolve the issue. But I played around with the configuration options that superplate offers you and found a solution.

Turns out, if I don't use the UI (Ant Design), then it works. See the screenshots below which show the difference in the setup which seems to cause the issue for me.

I can do the tutorial without the UI, so the issue is resolved for me. But I can give you more information if you wan't to investigate further.

Cheers,
Mathias

![CleanShot 2022-05-11 at 14 25 15](https://user-images.githubusercontent.com/9783664/167849724-1172b8d8-946a-48c2-9c9a-ba314842e5d5.png)

![CleanShot 2022-05-11 at 14 22 48](https://user-images.githubusercontent.com/9783664/167849663-8c26d5c4-7ebe-495f-ae59-e96941ec4fd3.png)

**Comment by omeraplak** [comment]
Thank you for detailed reply @maethub . We would very much like to solve this problem. I've updated to the `refine` versions on superplate. Could you please create a project with `superplate` again?

If the problem persists, could you share your package.json file with me? 

Thank you for your patience and help! 🎉

**Comment by vibl** [comment]
It should be solved by upgrading Node.
