### ISSUE TITLE
[BUG] @pankod/refine-nhost is not handling graphQL error responses

### ISSUE THREAD

**Issue by KrishnaPG** [pankod/refine#1794]
**Describe the bug**
The `@nhost/nhost-js` does not throw errors for graphQL errors, instead it returns `error` field in the return value. Callers are expected to check for the `error` field in the return values and act appropriately.

https://github.com/nhost/nhost/blob/19ccc5ab0d69ba516305548678e09807809845c3/packages/nhost-js/src/clients/graphql.ts#L55-L60
 
However,
The `refine-nhost` is not considering this situation and is not handling the error return values. 
https://github.com/pankod/refine/blob/38278e6b61af8c4cbf90d61e790bd619825fead5/packages/nhost/src/index.ts#L203-L204

This is leading to situation where the error message is eaten away by the `refine-nhost` and no way for the app or caller to know about the graphQL error responses. App gets a "success" notification, but the backend does not have the data and no way to know about it (since console log also does not show any errors).

**To Reproduce**
Use `refine-nhost` to make a graphQL query that returns errors (such as permission error) etc.

**Expected behavior**
Error message should be thrown or notification should be displayed

**Comment by omeraplak** [comment]
Hey @KrishnaPG 👋,
Thank you for contacting us! Great point! It seems our graphql providers are missing error handling. We'll deal with that this week! 🚀

**Comment by omeraplak** [comment]
Hey @KrishnaPG ,
We've created #1797. How does it look for you?

**Comment by omeraplak** [comment]
Hey @KrishnaPG ,
We've released `@pankod/refine-nhost@3.8.1`. Could you approve this fix?

**Comment by omeraplak** [comment]
Hey @KrishnaPG 👋,

This is because the `checkError` method is implemented incorrectly in our `nhost` example. We fixed this bug in the same PR.
https://github.com/pankod/refine/pull/1797/files#diff-7e4a8e1e594e9fcc142149ad1e98c9c3af520a1e25e5ce609fdb8a5d29d630f2R47

**Comment by KrishnaPG** [comment]
Thank you @omeraplak 

Not sure about the example or `checkError`. 

I tested the `"@pankod/refine-nhost": "^3.18.1"` (the latest release you indicated above) and the `handleError` is the one I am seeing in the code as the new fix that has the `promise.reject` (which is causing the screenshot shown earlier above)

https://github.com/pankod/refine/blob/daa900ddf7272d4a7c6bd515b9179a0b8c747d67/packages/nhost/src/index.ts#L110-L120

My test repo https://github.com/KrishnaPG/refine-nhost-test illustrates this problem with this new fix.

**Comment by omeraplak** [comment]
I understand, but as I mentioned, your `checkError` method returns `Promise.reject()` which causes the user to log out.
please update your `checkError` method as follows,
```
  checkError: (error) => {
    console.log('check error: ', error);
    if (error.status === 401) {
      return nhost.auth.refreshSession();
    }
    return Promise.resolve();
  },
```

Don't forget to have a look at the `checkError` documentation, https://refine.dev/docs/core/providers/auth-provider/#checkerror.

I hope it will be useful for you 🚀

**Comment by KrishnaPG** [comment]
Thank you @omeraplak 

Yes, updating the `checkError` method as you suggested fixed the `logout` problem. Now the error is being notified without logout. That is helpful.

But the issue of **retryer** still seems to be present. The graphQL query is being made multiple times before the notification is finally being shown. How to fix it?

How to tell the **retryer** not to retry this specific query, especially when the status code has been 200 ?

**Comment by omeraplak** [comment]
Cool! 🎉
You can set the `queryOptions` property of hooks (`useList`, `useCreate`, `useTable`, `useForm`, etc.) like `{ retry: false }`.

If you want to do this globally, please have a look here,
https://refine.dev/docs/core/components/refine-config/#reactqueryclientconfig

**Comment by KrishnaPG** [comment]
Thank you @omeraplak 

The problem is **retryer** is retrying even when status code is 200 (because the `handleError` is rejecting the promise). 

Is there anyway this `{ retry: false }` can be set specifically for this graphQL request.

https://github.com/pankod/refine/blob/daa900ddf7272d4a7c6bd515b9179a0b8c747d67/packages/nhost/src/index.ts#L137-L140

Is there any additional parameter or something that can be passed here that will tell the retryer not to retry this?

Doing it here will fix all the cases instead of doing one by one for each of `useList`, `useCreate`, `useTable`, `useForm` etc.,

Also, I do not want to turn off the retries globally. Only when the status code is 200, do not retry.

**Comment by KrishnaPG** [comment]
wow... perfect. It worked like magic. Thank you much @omeraplak Your help is greatly appreciated.

The `reactQueryClientConfig` with custom `retry` logic has been what I have been struggling to figure out.

**Comment by omeraplak** [comment]
Yeeyy!! You're welcome 🚀🚀🚀
