### ISSUE TITLE
[BUG] Pagination in graphql package when getList

### ISSUE THREAD

**Issue by youcefTab** [pankod/refine#1802]
i'm using graphql dataProvider to reach to my data in the backend, when i try to get a list of elements with useTable (that uses getList) 
the total in pagination section of tableProps is undefined, i checked the implementation of getList and it returns this : 

![OnPaste 20220512-175443](https://user-images.githubusercontent.com/25765736/168128425-8b0f8e24-5fce-45d2-a7bf-ab457a525319.png)

shouldn't the total be get for exemple like this : response[totalCount] ?

**Comment by omeraplak** [comment]
Hey @youcefTab 👋,
The `@pankod/refine-graphql` package was made as an example. It's not based on a real backend, we built it based on strapi's GraphQL schema. You can create a new data provider based on your own backend 🚀
