### ISSUE TITLE
[FEAT]  Implement support for Deck.GL / Apache-arrow  -> Apache-arrow mjs files and refine webpack config not working. 

### ISSUE THREAD

**Issue by albcunha** [pankod/refine#1804]
**Describe the bug**
When i try to use Deck.Gl with refine.js, I get several errors like this:

module not found: Error: Can't resolve './io/whatwg/builder' in 'C:\Users\Alberto\desenvolvimento\atrium\Atrium-Frontend\node_modules\apache-arrow' Did you mean 'builder.mjs'?

**To Reproduce**

`npx superplate-cli -p refine-react tutorial`

√ Cloned remote source successfully.
√ What will be the name of your app · tutorial
√ Package manager: · npm
√ Do you want to use an UI Framework?: · antd
√ Do you want to customize theme?: · less
√ Router Provider: · react-router-v6
√ Data Provider: · custom-json-rest-data-provider
√ Auth Provider: · none
√ Do you want to add an example page? · example-resource
√ Do you want to customize layout? · custom-layout
√ i18n - Internationalization: · no
√ Would you like to share your choices with us anonymously? · yes
/ Installing packages with npm

`yarn add deck.gl --save `

Delete everything. Leave only` index.tsx` and `reportWebVitals.ts`
Based on deck.GL example on how to use it with open streetmaps tilers: [https://github.com/visgl/deck.gl/blob/8.7-release/examples/website/map-tile/app.js](https://github.com/visgl/deck.gl/blob/8.7-release/examples/website/map-tile/app.js), create app.jsx with the content bellow:

```
import React from 'react';
import {render} from 'react-dom';

import DeckGL from '@deck.gl/react';
import {MapView} from '@deck.gl/core';
import {TileLayer} from '@deck.gl/geo-layers';
import {BitmapLayer, PathLayer} from '@deck.gl/layers';

const INITIAL_VIEW_STATE = {
  latitude: 47.65,
  longitude: 7,
  zoom: 4.5,
  maxZoom: 20,
  maxPitch: 89,
  bearing: 0
};

const COPYRIGHT_LICENSE_STYLE = {
  position: 'absolute',
  right: 0,
  bottom: 0,
  backgroundColor: 'hsla(0,0%,100%,.5)',
  padding: '0 5px',
  font: '12px/20px Helvetica Neue,Arial,Helvetica,sans-serif'
};

const LINK_STYLE = {
  textDecoration: 'none',
  color: 'rgba(0,0,0,.75)',
  cursor: 'grab'
};

/* global window */
const devicePixelRatio = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;

function getTooltip({tile}) {
  return tile && `tile: x: ${tile.x}, y: ${tile.y}, z: ${tile.z}`;
}

export default function App({showBorder = false, onTilesLoad = null}) {
  const tileLayer = new TileLayer({
    // https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Tile_servers
    data: [
      'https://a.tile.openstreetmap.org/{z}/{x}/{y}.png',
      'https://b.tile.openstreetmap.org/{z}/{x}/{y}.png',
      'https://c.tile.openstreetmap.org/{z}/{x}/{y}.png'
    ],

    // Since these OSM tiles support HTTP/2, we can make many concurrent requests
    // and we aren't limited by the browser to a certain number per domain.
    maxRequests: 20,

    pickable: true,
    onViewportLoad: onTilesLoad,
    autoHighlight: showBorder,
    highlightColor: [60, 60, 60, 40],
    // https://wiki.openstreetmap.org/wiki/Zoom_levels
    minZoom: 0,
    maxZoom: 19,
    tileSize: 256,
    zoomOffset: devicePixelRatio === 1 ? -1 : 0,
    renderSubLayers: props => {
      const {
        bbox: {west, south, east, north}
      } = props.tile;

      return [
        new BitmapLayer(props, {
          data: null,
          image: props.data,
          bounds: [west, south, east, north]
        }),
        showBorder &&
          new PathLayer({
            id: `${props.id}-border`,
            visible: props.visible,
            data: [
              [
                [west, north],
                [west, south],
                [east, south],
                [east, north],
                [west, north]
              ]
            ],
            getPath: d => d,
            getColor: [255, 0, 0],
            widthMinPixels: 4
          })
      ];
    }
  });

  return (
    <DeckGL
      layers={[tileLayer]}
      views={new MapView({repeat: true})}
      initialViewState={INITIAL_VIEW_STATE}
      controller={true}
      getTooltip={getTooltip}
    >
      <div style={COPYRIGHT_LICENSE_STYLE}>
        {'© '}
        <a style={LINK_STYLE} href="http://www.openstreetmap.org/copyright" target="blank">
          OpenStreetMap contributors
        </a>
      </div>
    </DeckGL>
  );
}

```

**ERROR RESULT**

Attempted import error: 'FixedSizeList' is not exported from 'apache-arrow/Arrow.dom' (imported as 'FixedSizeList').
ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 18:25-38
export 'FixedSizeList' (imported as 'FixedSizeList') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

ERROR in ./node_modules/@loaders.gl/schema/dist/esm/category/mesh/mesh-to-arrow-table.js 18:49-54
export 'Field' (imported as 'Field') was not found in 'apache-arrow/Arrow.dom' (module has no exports)

**Expected behavior**
Show Deck.GL map.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101
 - Used dataProvider restAPI

**Additional context**
Maybe it has something to do with apache-arrow mjs files and webpack 5 config. This is discussed here:
[https://github.com/apache/arrow/issues/9752](https://github.com/apache/arrow/issues/9752)

I tried to change craco.config.js to add what was suggested, like this, but it didn´t work:
module.exports = {
    resolve: {
        extensions: ['.ts', '.mjs', '.js']
    },
    module: {
        rules: [
            {
                test: /\.m?js/,
                resolve: {
                    fullySpecified: false
                }
            },
        ]
    },
	plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            // modifyVars: { "@primary-color": "#1DA57A" },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};

**Temporary fix **
On package.json, change **"react-scripts": "^5.0.0" for "react-scripts": "^4.0.3"**, Found it here: [https://github.com/solana-labs/wallet-adapter/issues/231](https://github.com/solana-labs/wallet-adapter/issues/231)

**Comment by omeraplak** [comment]
Hey @albcunha ,
Thank you for contacting us. Apparently, it's a webpack compatibility-related issue. I'm not sure if there is anything we can do about it. Your workaround seems to be the best for now. Could you please let me know if there is something I missed?
