### ISSUE TITLE
using graphql Package

### ISSUE THREAD

**Issue by youcefTab** [pankod/refine#1805]
i'm using useTable from "@pankod/refine-antd", i'm trying to look how the response from the backend should look like, but there is an inconsistency in the getList function as eu may see here : 

![image](https://user-images.githubusercontent.com/25765736/168392095-6acb20fe-bcd3-4213-856b-4e3adcfaa600.png)

the total should be something like response[totalCount], do you know how the response format should look like if may be i'm not having it right ?

**Comment by omeraplak** [comment]
Hey @youcefTab 👋,
Thank you for contacting us! 

Could you please review our answer?
https://github.com/pankod/refine/issues/1802#issuecomment-1125795328

**Comment by youcefTab** [comment]
thank you for your response, i think this point should more detailed in the documentation because graphql can be very confusing when using low code solutions.

**Comment by omeraplak** [comment]
Thank you so much @youcefTab🔥 In which document do you think we should state this? Or better yet, can you do this for us? 🚀
