### ISSUE TITLE
[FEAT] Preserve query params when navigating from list to edit and back 

### ISSUE THREAD

**Issue by BenGardiner123** [pankod/refine#1806]
When a table/list is being displayed and filtered, the user clicks the edit button  and navigates to the edit page. 
Once they are finished in the edit page it would be cool to have the option of returning to previous page in the navigation history rather than refreshing the page with the same data being displayed.

for example when A user selects from the Table filter dropdown for example  lets say the the url is 
"http://localhost:3000/tags?tagType=21&pageSize=50"
then.. when i click the edit button =>  edit page =>  save it returns me to "localhost:3000/tags"

ideally you should be able to return to 
"http://localhost:3000/tags?tagType=21&pageSize=50" if you would like

**Comment by omeraplak** [comment]
Hey @BenGardiner123,
Thank you for contacting us. We definitely need improvement here. Thank you so much for forwarding this to us. We will try to do our best. 
If we thought you had this feature, how would you like to use it? Hey @rassie, would you have any suggestions?

**Comment by rassie** [comment]
I think I would like this feature too and using History API for this seems straightforward. It might be possible to create some kind of global query parameters cache for each table, but that would break multi-tab workflows, so using the URL bar with History API is probably the best bet.

**Comment by omeraplak** [comment]
> I think I would like this feature too and using History API for this seems straightforward. It might be possible to create some kind of global query parameters cache for each table, but that would break multi-tab workflows, so using the URL bar with History API is probably the best bet.

Thank you @rassie ! So is the usage I shared above acceptable for you in terms of DX? Do you think it makes sense for this to be the default behavior without writing extra configuration?

**Comment by rassie** [comment]
I would certainly consider it being the better UX, after all if you are traversing a large table and want to edit an item or two, you wouldn't want to be thrown back to page one or reset the filter.

(this reminds me, I need to rebase that PR for better anchors...)

**Comment by omeraplak** [comment]
Hey @BenGardiner123,
One good and one bad news.

bad news, we need to work on this feature a little more 💪

good news,
I created a PR #1811 that solved the error when you used it in the workaround. It will be released soon! 🚀

**Comment by BenGardiner123** [comment]
Thanks so much @omeraplak and @rassie
