### ISSUE TITLE
[BUG] getOne (to show and edit one item) does not work properly with id's that has special characters

### ISSUE THREAD

**Issue by youcefTab** [pankod/refine#1814]
when i list my elements, theirs id's are like : "UHJvdmlkZXJUeXBlOjE=" when it's being passed to the URL (in show and edit) the special characters like "=" are being encoded so we get a url like : "resource/show/UHJvdmlkZXJUeXBlOjE%3D" this make the detection of the resource name and id don't work, it would detect the resource to be the full URI like so : "resource/show/UHJvdmlkZXJUeXBlOjE%3D" and the id is an empty string : ""
i eventually made it work by specifying the operation manually in metaData of useShow and passing the recordItem in the Show component, but i thing it's against the automation principles that refine work with specially that i'm not creating a custom page.

**Comment by omeraplak** [comment]
Hey @youcefTab 👋,
Thank you for contacting us! It's interesting because I thought we handled it (https://github.com/pankod/refine/issues/1506)

Where exactly does the `id` value come from the empty string? for example, I tried this in our `fineFoods admin demo` and saw that the id was correct in the request (although it returned 404)

https://example.admin.refine.dev/orders/show/UHJvdmlkZXJUeXBlOjE%3D

**Comment by youcefTab** [comment]
for now it's a basic application, i have a resource named provider, i created a listProviders in witch i added a showButton and an editButton, they both have a recordItemId where i pass the record.id, in the function that handles the showProvider for exemple, if i don't passe the parameter : **operation: "provider"** i will have the following query : 
![image](https://user-images.githubusercontent.com/25765736/169039905-f32dfa15-47d1-4a99-b771-328425d77b67.png)
as you can se it detects the id ( i don't remember what i've changed to make it work ) but the operation is wrong. for the resources that has an id without special characters it works just fine.

**Comment by youcefTab** [comment]
yes i solved it by giving the operation manually as you would for a custom page, for the routerProvider i'm using the one imported from refine-react-router-v6
![image](https://user-images.githubusercontent.com/25765736/169067534-9cb508ee-c9e9-40ab-9498-ad218f653b8b.png)

for the editProvider layout i'm using it like this : 
![image](https://user-images.githubusercontent.com/25765736/169068060-8a2e0974-a0ef-440e-bd0e-06674604a1bb.png)

to make things work at least partly i'm passing operation: "provider in the metaData and i customized my graphql dataProvider to use the operation instead of the resource.

i can add files in CodeSandbox even tho they are basic files, but i can't share my backend, is that ok ?

**Comment by omeraplak** [comment]
hmmm can you share your dataProvider?  Thanks a lot for your understanding! 🚀

**Comment by youcefTab** [comment]
i'm using the graphql dataProvider : "https://github.com/pankod/refine/tree/master/packages/graphql" i copied the index.ts to my local and adapted the return response to match my backend and of course giving refine what it's wainting for as a response

**Comment by omeraplak** [comment]
Sorry, I'm a little confused. Is there anything else we need to do on this issue?
