### ISSUE TITLE
[BUG]TypeScript error for Next.js

### ISSUE THREAD

**Issue by dzcpy** [pankod/refine#1839]
**Describe the bug**
In `_app.tsx` there is a TypeScript error:
`Property 'children' does not exist on type 'IntrinsicAttributes & RefineProps'`

**To Reproduce**
1. Initialize project with superplate, choose Nest.js and Strapi v4.
2. Upgrade dependencies

**Expected behavior**
Should allow children in TypeScript definition.

**Screenshots**
![image](https://user-images.githubusercontent.com/203980/170370586-e9422d13-d0e7-4c9d-a638-978da2f6ad64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Used dataProvider Strapi V4

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**
TypeScript 4.7.2
React 18.1.0

**Comment by omeraplak** [comment]
Hey @dzcpy ,
Thank you for contacting us! We are working on React@18 support. Actually, we have successfully upgraded all our packages, but the packages we use in many of our examples do not yet support React@18. I guess @18 support of the entire React ecosystem will take some time. Thank you for your understanding and patience 

https://github.com/pankod/refine/issues/1725

note: I'm closing this issue, you can follow it in other issue
