### ISSUE TITLE
[DOC]File upload labels are not marked as required.

### ISSUE THREAD

**Issue by nrikiji** [pankod/refine#1840]
<img width="607" alt="スクリーンショット 2022-05-26 10 43 01" src="https://user-images.githubusercontent.com/4780752/170397989-40324ee2-14ba-46d6-a85e-eaf64807b6fa.png">

https://github.com/pankod/refine/blob/master/examples/fineFoods/admin/src/components/product/create.tsx#L61-L72

This is how it's supposed to be.
```
<Form.Item label={t("products.fields.images.label")}>
  <Form.Item
    name="images"
    valuePropName="fileList"
    getValueFromEvent={getValueFromEvent}
    noStyle
    rules={[
      {
        required: true,
      },
   ]}
  >
 ・・・
```

It seems to show up like this.
```
  <Form.Item
    label={t("products.fields.images.label")}
    name="images"
    valuePropName="fileList"
    getValueFromEvent={getValueFromEvent}
    noStyle
    rules={[
      {
        required: true,
      },
   ]}
  >
 ・・・
```

**Comment by omeraplak** [comment]
Hey @nrikiji ,
Thank you for contacting us. Do you want to open PR? It would be great 🔥

**Comment by nrikiji** [comment]
I would fix it if I could, but it doesn't seem to work in my environment. Sorry.

**Comment by omeraplak** [comment]
If I'm not mistaken it's an Ant Design bug. We will check if it is fixed

**Comment by omeraplak** [comment]
This issue is on the side of ant Design. No solution is specified. I'm closing for now
