### ISSUE TITLE
[BUG]react-dom.development.js:67 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by nrikiji** [pankod/refine#1858]
I have been getting this error since version @pankod/refine-antd@3.21.0. What are the possible reasons?

**Comment by omeraplak** [comment]
Hey @nrikiji ,
Thank you for contacting us. Let's see what we can do 🚀

**Comment by nrikiji** [comment]
Thank you. I have confirmed that it has been resolved.
