### ISSUE TITLE
How to work with multiple data providers?

### ISSUE THREAD

**Issue by KrishnaPG** [pankod/refine#1885]
Some of our data comes from REST backend and some from GraphQl and some from others.

`Refine` seems to be accepting only one `dataProvider=` prop. What is the recommended way to deal with multiple data backends. For example, some `resources` need to use one particular backend and others need to use other backends - how to specify this?

To illustrate, consider the scenario of admin dashboard that has `users` data coming from identity access databases (such as LDAP) and `server metrics` / `performance` data coming from time-series databases etc.

**Comment by omeraplak** [comment]
Hey,
Refine has native multiple data provider support. This example may be useful for you,

Example: https://refine.dev/docs/examples/data-provider/multiple/
Doc: https://refine.dev/docs/core/providers/data-provider/#usage


I hope it will be useful for you
