### ISSUE TITLE
[BUG]: Issue in useTable hook when resource has API URL with query parameter 

### ISSUE THREAD

**Issue by sourabhcnh** [pankod/refine#1892]
Issue in useTable hook when resource has API URL with query parameter 

Steps to reproduce:
1. Define dataProvider in App.tsx
2. Create a ticket.tsx under pages and use "useTable" hook 
   a. Below is the code defined in the 
   export const TicketPage: React.FC = () =>{    
        const { tableQueryResult } = useTable<IVehicleList>({
            resource: "**ticket/getTickets?ticketNoList=3107,3106,3105,3104**",
        });
        return (
            <div>
             Ticket list here
            </div>
        );
   }

On running above code, I see API request as "http://abc.com/ticket/getTickets?ticketNoList=3107,3106,3105,3104?limit=10&offset=0&" in Network tab under developer debugger 

**Expected behavior**
1. I think "useTable" hook should check if there are query parameter in API URL then it should not append '?' again, rather append limit and offset
2. There should be flag(bool flag) in "useTable" hook to skip paging query parameter ( limit and offset)

Not sure if I am missing anything. Please suggest

**Comment by omeraplak** [comment]
Hey @sourabhcnh ,

Thank you for contacting us! It looks like you are trying to apply a filter called `ticketNoList`. The correct way to do this with `useTable` is to give it permanentFilter.

I'm not sure which data provider you are using, but this might be helpful.

```js
const { tableQueryResult } = useTable({
     resource: "ticket/getTickets",
     permanentFilter: [
         {
             field: "ticketNoList",
             value: ["3107", "3106", "3105", "3104"],
             operator: "in",
         },
     ],
});
```
if your dataProvider doesn't support "in",

```js
const { tableQueryResult } = useTable({
     resource: "ticket/getTickets",
     permanentFilter: [
         {
             field: "ticketNoList",
             value: "3107,3106,3105,3104"
             operator: "eq",
         },
     ],
});
```

note: the way you send `operator` and `value` may differ depending on your dataProvider

I hope it will be useful for you. Please feel free to write if you need more help!

**Comment by sourabhcnh** [comment]
@omeraplak : Thank you very much for quick response. Really appreciate that. I am exploring refine for my application and so far liking it 👍

**Comment by omeraplak** [comment]
You're welcome 🎉 Your support and feedback are very important, don't forget to tell your friends about us! 🚀 btw, If you haven't joined [Discord](https://discord.gg/refine) yet, we are waiting for you ❤️
