### ISSUE TITLE
[BUG] refine 3.23.2 does not work on nextjs: Multiple children were passed to <Link> 

### ISSUE THREAD

**Issue by clebeaupin** [pankod/refine#1894]
**Describe the bug**

The last version  of refine 3.23.3 does not work with nextjs on list pages

When you try to view to a list page like http://localhost:3000/posts, it failed with this error:

```
Unhandled Runtime Error

Error: Multiple children were passed to <Link> with `href` of `/posts?current=1&pageSize=10` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children 
Open your browser's console to view the Component stack trace.
```

**To Reproduce**
1. Install the refine tutorial with nextjs: npx superplate-cli -p refine-nextjs tutorial
2. Select these options:

```
npx superplate-cli -p refine-nextjs tutorial

✔ Cloned remote source successfully.
✔ What will be the name of your app · tutorial
✔ Do you want to use an UI Framework?: · antd
✔ Do you want to customize theme?: · css
✔ Data Provider: · custom-json-rest-data-provider
✔ Auth Provider: · custom-auth-provider
✔ Do you want to add an example page? · example-resource
✔ Do you want to customize layout? · custom-layout
✔ i18n - Internationalization: · i18n-antd
✔ Would you like to share your choices with us anonymously? · no
```

3. Start refine: npm run dev
4. Go to http://localhost:3000/posts
5. See error

**Comment by aliemir** [comment]
Hey @clebeaupin 
Thank you for your patience, we've been able to reproduce and finally fix the issue with #1897. Currently you can update your dependencies from the `next` channel, we're also going to do a release to the `latest` channel today including the fix.

**Comment by omeraplak** [comment]
Hey @clebeaupin ,
We've released `@pankod/refine-antd@3.25.4`. Could you approve this fix?

**Comment by clebeaupin** [comment]
It works for pagination list but now I have other issues with antd hooks : useEditableTable and useModalForm

**Comment by omeraplak** [comment]
> It works for pagination list but now I have other issues with antd hooks : useEditableTable and useModalForm

Hey @clebeaupin ,
Thank you for your reply! What issues are you having with useModalForm and useEditableTable? Can you give some details?

**Comment by clebeaupin** [comment]
useModalForm: the modal form never displays instead it redirects to a classic page with the form

useEditableTable: I click on the EditButton and nothings happens
