### ISSUE TITLE
[BUG][strapi-graphql] graphql-request type issue

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#1929]
Hi,

Due to the difference in typescript between the latest version of graphql-request and the version of graphql-request@3.5.0 used in the strapi-graphql package, I get an error as follows. Can be upgrade or change to other usages of npm.

`Argument of type 'import("D:/*****/node_modules/graphql-request/dist/index").GraphQLClient' is not assignable to parameter of type 'import("D:/*****/node_modules/@pankod/refine-strapi-graphql/node_modules/graphql-request/dist/index").GraphQLClient'.
  Type 'GraphQLClient' is missing the following properties from type 'GraphQLClient': batchRequests, setEndpointts(2345)`

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us! Would you like to open a PR that solves the issue? If you don't have time please don't worry, we can do it too

btw Refine community prefers English.  Can you use english if possible?  Thanks a lot for your understanding.

**Comment by omeraplak** [comment]
Hey @emehmet ,
It seems "graphql-request" has released version 4, but Refine packages are using version 3. You have to go with version 3 until we get to version 4. In the meantime, we will also update our docs. Thank you for understand

```
npm i graphql-request@3
```

**Comment by emehmet** [comment]
Thank you @omeraplak ,

I've done it with the resolutions for now.

`  "resolutions": {
        "graphql-request": "4.3.0"
    }
`

**Comment by omeraplak** [comment]
Hey @emehmet ,
We've released [`@pankod/refine-graphql@4.1.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-strapi-graphql%404.1.0) with `graphql-request` v4 support 💥

Also, you can check out GraphQL doc -> https://refine.dev/docs/guides-and-concepts/data-provider/graphql/#usage
