### ISSUE TITLE
[BUG] ExportButton is not presenting CSV file download

### ISSUE THREAD

**Issue by paularntz** [pankod/refine#1942]
**Describe the bug**
ExportButton animation hangs, CSV file is not presented.  I can see the graphql query fetching the correct information.

**To Reproduce**
1. Set up according to the docs

**Expected behavior**
CSV download like this: https://example.admin.refine.dev/orders?current=1&pageSize=10

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: latest
 - Used dataProvider: graphql

**Comment by omeraplak** [comment]
Hey @paularntz ,
Thank you for contacting us. We were unable to reproduce this error. Can you share a screen recording where we can see the Network request with us? Thank you for understand

**Comment by omeraplak** [comment]
Hey @paularntz ,
Your `getList` method must be returning the `total` value correctly. Otherwise, the export process will never end.

https://refine.dev/docs/core/providers/data-provider/#getlist
