### ISSUE TITLE
[Feat] strapi v4 with graphql

### ISSUE THREAD

**Issue by HaveF** [pankod/refine#1971]
**Describe the bug**
I suspect there is a bug, but not sure.

[strapi v3 graphql query](https://docs-v3.strapi.io/developer-docs/latest/development/plugins/graphql.html#query-api)
```
query {
  users {
    username
    email
  }
}
```
[strapi v4 graphql query](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/graphql-api.html#fetch-multiple-entries), the field nested under `attributes`
```
query {
  documents {
    data {
      id
      attributes {
        title
        categories {
          data {
            id
            attributes {
                name
            }
          }
        }
      }
    }
    meta {
      pagination {
        page
        pageSize
        total
        pageCount
      }
    }
  }
}
```

In refine, it will query like this:
```
{
  "query": "query ($where: JSON, $sort: String, $start: Int, $limit: Int) { symptomsConnection (where: $where) { aggregate { count } } symptoms (sort: $sort, where: $where, start: $start, limit: $limit) { name } }",
  "variables": {
    "where": {},
    "sort": "id:asc",
    "start": 0,
    "limit": 10
  }
}
```

1. Does the `symptoms { name }` seems use strapi v3 graphql grammer?
2. There are also error messages on request :
```
...
"Cannot query field \"symptomsConnection\" on type \"Query\"."
...
"Unknown argument \"where\" on field \"Query.symptoms\"."
...
```

Do I missing something? Or @pankod/refine-strapi-graphql is used for strapi V3?

**deps**
    "@pankod/refine-strapi-graphql": "3.25.6",
    "@pankod/refine-strapi-v4": "3.25.6",

**backend deps**
    "@strapi/plugin-graphql": "4.2.0",
    "@strapi/strapi": "4.2.0",

**Comment by HaveF** [comment]
I'm not sure I have the ability to do that thing. 😂 
Can you point out how to do this? Or I can try to step by step, the worst case is that I can't do it, but I leave some information for further develop

**Comment by omeraplak** [comment]
Great, I think you're being unfair to yourself on this one. Now I will share some documents and examples that will make your development easier 🚀

How does Refine handle GraphQL queries?
https://refine.dev/docs/guides-and-concepts/data-provider/graphql/

Hasura GraphQL data provider:
https://github.com/pankod/refine/blob/next/packages/hasura/src/index.ts

NHost GraphQL data provider:
https://github.com/pankod/refine/tree/next/packages/nhost

Discord server where you can get support from us whenever you need help: https://discord.gg/refine :)

**Comment by HaveF** [comment]
After some research, except for some technical issues, I find the support to v4 graphql support should be delay. 

[Lots of complains are found in strapi forum](https://forum.strapi.io/t/discussion-regarding-the-complex-response-structure-for-rest-graphql-developer-experience/13400/39). I guess there would be some changes in the future.

And some technical issues includes:
- strapi-v4 's normalizeData function could handle response problems
- but query problems(mess data, attributes) are hard to resolve

@omeraplak close this issue or just leave it to wait?

**Comment by omeraplak** [comment]
Hey @HaveF,
Thanks a lot for your research. I think we can close the issue. For now, we need some time

**Comment by R3flector** [comment]
Spent 2 hours before realizing I needed version 3 of strapi

**Comment by omeraplak** [comment]
> Spent 2 hours before realizing I needed version 3 of strapi

Sorry to hear that. We should clearly state this in our documents

**Comment by ch1llysense** [comment]
yes u should

> > Spent 2 hours before realizing I needed version 3 of strapi
> 
> Sorry to hear that. We should clearly state this in our documents
