### ISSUE TITLE
[BUG] When I am using graphql query it throws an error missing selection set

### ISSUE THREAD

**Issue by Thirumalai08** [pankod/refine#1992]
**Describe the bug**
I created the project with refine hasura and also when i am trying to fetch the values from my hasura graphql it is throwing error
react_devtools_backend.js:4026 Error: missing selection set for "customer": {"response":{"errors":[{"extensions":{"path":"$.selectionSet.customer.selectionSet","code":"validation-failed"},"message":"missing selection set for \"customer\""}],"status":200,"headers":{"map":{"content-type":"application/json; charset=utf-8"}}},"request":{"query":"query ($limit: Int, $offset: Int, $order_by: [customer_order_by!], $where: customer_bool_exp) { customer (limit: $limit, offset: $offset, order_by: $order_by, where: $where)  customer_aggregate (where: $where) { aggregate { count } } }","variables":{"limit":10,"offset":0,"order_by":{},"where":{}}}}
If I am using the endpoint which is used in the documentation it is not throwing any error. Can you please help me to fix this ?

**Screenshots**
![image](https://user-images.githubusercontent.com/50919570/174472093-47b4864e-f6e1-4c6e-8c83-2d4da139e3e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Used dataProvider Hasura Graphql

**Comment by omeraplak** [comment]
Hey @Thirumalai08 ,
Thank you for contacting us! Could you share your query?

**Comment by Thirumalai08** [comment]
> Hey @Thirumalai08 , Thank you for contacting us! Could you share your GraphQL query?

You can find below:
{"query":"query ($limit: Int, $offset: Int, $order_by: [customer_order_by!], $where: customer_bool_exp) { customer (limit: $limit, offset: $offset, order_by: $order_by, where: $where)  customer_aggregate (where: $where) { aggregate { count } } }","variables":{"limit":10,"offset":0,"order_by":{},"where":{}}}

**Comment by omeraplak** [comment]
Can you please share the code you produced for query?

**Comment by Thirumalai08** [comment]
interace:
export interface ICustomer {
    customer_id: number;
    customer_email: string;
    customer_password: string;
}
list.tsx
import {
    List,
    // DateField,
    Table,
    // TextField,
    TagField,
    useTable,
} from "@pankod/refine-antd";

import { ICustomer } from "interfaces";

export const AdminList: React.FC = () => {
    const { tableProps } = useTable<ICustomer>();
    return (
        <List>
            <Table {...tableProps} rowKey="customer_id">
                <Table.Column dataIndex="customer_id" title="ID" />
                <Table.Column dataIndex="customer_email" title="Email" render={(value) => <TagField value={value} />} />
                {/* <Table.Column
                    dataIndex="createdAt"
                    title="createdAt"
                    render={(value) => <DateField format="LLL" value={value} />}
                /> */}
            </Table>
        </List>
    );
};
App.tsx
import { ErrorComponent, LoginPage, notificationProvider, ReadyPage } from "@pankod/refine-antd";
import "@pankod/refine-antd/dist/styles.min.css";
import { Refine } from "@pankod/refine-core";
import dataProvider from "@pankod/refine-hasura";
import routerProvider from "@pankod/refine-react-router-v6";
import { Footer, Header, Layout, OffLayoutArea, Sider, Title } from "components/layout";
import { GraphQLClient } from "graphql-request";
import { AdminList } from "pages/admin";
import { useTranslation } from "react-i18next";
import { authProvider } from "./authProvider";

const API_URL = "https://teaching-man-81.hasura.app/v1/graphql";
const client = new GraphQLClient(API_URL, {
    headers: {
        "x-hasura-admin-secret": "717rS6ZsmrfJTZvee9n5mTOqPeEokVSgyYf8f2C71TsKaByi7TCMcmxk5Ig13ecn",
    },
});
const gqlDataProvider = dataProvider(client);

function App() {
    const { t, i18n } = useTranslation();

    const i18nProvider = {
        translate: (key: string, params: object) => t(key, params),
        changeLocale: (lang: string) => i18n.changeLanguage(lang),
        getLocale: () => i18n.language,
    };

    return (
        <Refine
            notificationProvider={notificationProvider}
            ReadyPage={ReadyPage}
            catchAll={<ErrorComponent />}
            routerProvider={routerProvider}
            dataProvider={gqlDataProvider}
            resources={[
                {
                    name: "customer",
                    list: AdminList,
                },
            ]}
            authProvider={authProvider}
            LoginPage={LoginPage}
            Title={Title}
            Header={Header}
            Sider={Sider}
            Footer={Footer}
            Layout={Layout}
            OffLayoutArea={OffLayoutArea}
            i18nProvider={i18nProvider}
        />
    );
}

export default App;

**Comment by Thirumalai08** [comment]
Issue Idenitified missed to add the metadata in useTable hook. So I am closing this bug
