### ISSUE TITLE
Does refine has a excel like spread sheet view.

### ISSUE THREAD

**Issue by nirmaanlabs** [pankod/refine#1997]
I ran into a use case where user need to enter like lot of data. It seems very easy to enter this data in excel. 

To enter/edit/update large amount of data in refine, do we have any excel like spreadsheet example ?
https://github.com/adazzle/react-data-grid.
https://reactgrid.com/examples/?utm_source=github&utm_medium=readme

Something like this

**Comment by omeraplak** [comment]
Hey @nirmaanlabs ,
Wow, I think it would be a great example! Anyone want to do it in community?

**Comment by DVGY** [comment]
@omeraplak do you have any guide, on how to get started if I want to integrate something into refine and make it open source.

For example, it would be great if there was a guide on how to integrate a smaller library with refine.

I see refine has its own version of react-table. I think you get what I mean. 

Thanks

**Comment by nirmaanlabs** [comment]
@omeraplak Do you have any guide, on how to get started if I want to integrate something into refine and make it open source.

For example, it would be great if there was a guide on how to integrate a smaller library with refine.

I see refine has its own version of react-table. I think you get what I mean.

Thanks

**Comment by omeraplak** [comment]
Hey @nirmaanlabs ,
Have you reviewed our [Contributing](https://refine.dev/docs/contributing/) doc? I think you can do it by following the steps in this doc. https://refine.dev/docs/contributing/

Additionally, you can start by copying one of our existing packages -> https://github.com/pankod/refine/tree/next/packages

**Comment by aliemir** [comment]
Hey @nirmaanlabs, @biskuvit is working on an example using [handsontable](https://handsontable.com). We're planning to release this soon. If you want, you can tweak that example to use `react-data-grid` and maybe open a PR with it? We may also discuss adding examples with other libraries in the future 🤔

**Comment by nirmaanlabs** [comment]
> maybe open a PR wit

@aliemir Yes I can do that. Thanks

**Comment by omeraplak** [comment]
Hey @nirmaanlabs ,
We've released [`Handson Table`](https://refine.dev/docs/examples/table/handsontable/handsontable/) example. You can check out ->
