### ISSUE TITLE
[FEAT] Redis Stack Data Provider

### ISSUE THREAD

**Issue by amiorin** [pankod/refine#2054]
I'd like to try to connect Redis Stack to Refine. Redis Stack has capabilities of document store and search engine in one database. 

The manual says:
> A data provider makes HTTP requests and returns response data back using predefined methods.

I'd like to skip the HTTP layer for now. The content is all created and consumed through the Refine app and an API is not needed at the moment.

Any feedback?

**Comment by omeraplak** [comment]
Hey @amiorin ,
In this case, I think you can use Next.js. Is there any support we can provide?
