### ISSUE TITLE
UseStepForm INSIDE a Modal: Fields have no values after the initial step (0)

### ISSUE THREAD

**Issue by capsloq** [pankod/refine#2082]
**Describe the bug**
UseStepForm INSIDE a Modal:
When you click on 'EDIT IN MODAL WITH STEPPER" you can see that step 2 Textfield "content" has no value.
When you add the same Textfield "content" to step 1 it does work. Looks like only step 0 is working.

**To Reproduce**
1. Click on the codesandbox
2. Click on "EDIT IN MODAL WITH STEPPER"
3. Click on Next Step
4. See error:  Textfield "content" has no value

**Expected behavior**
Fields should work on all steps not only the very first step

**Screenshots**
[See Codesandbox](https://codesandbox.io/s/romantic-monad-y0vph2)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
[Codesandbox](https://codesandbox.io/s/romantic-monad-y0vph2)

**Comment by omeraplak** [comment]
Hey @capsloq ,
The main problem is using `useModalForm` and `useStepsForm` at the same time. Using `useModal` with `useStepsForm` instead solves the issue.

I created a CodeSandbox for you,
https://codesandbox.io/s/kru14p

I hope this helps you. Please feel free to write if there is any part that is not clear to you.

**Comment by capsloq** [comment]
Thank you @omeraplak 

May consider adding this as an example to the documentation. its an edge case but might be interesting for others.

**Comment by omeraplak** [comment]
It would be great! Would you like to do this? 🎁

**Comment by capsloq** [comment]
Will give it a try, but i am not very familiar with the process.
by pull request?

Sorry in advance if i get this wrong

**Comment by omeraplak** [comment]
Yes, PR would be great 👊 
here is our documentation on `how to run our docs in development mode`, https://refine.dev/docs/contributing/#starting-documentation-in-watch-mode
