### ISSUE TITLE
[BUG][Typescript] Children element type is not found on List, Edit, Show,Create component 

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2090]
Hi,
I use the examples described in the tutorial. I get this typescript error on all components.

Typescript error is;

List
`
Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & ListProps'.
`

Create
`
Type '{ children: Element; saveButtonProps: Partial<{ href: string; target?: string | undefined; onClick?: MouseEventHandler<HTMLElement> | undefined; } & BaseButtonProps & Omit<...> & { ...; } & Omit<...>> & { ...; }; }' is not assignable to type 'IntrinsicAttributes & CreateProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & CreateProps'.
`

Edit
`
Type '{ children: Element; saveButtonProps: Partial<{ href: string; target?: string | undefined; onClick?: MouseEventHandler<HTMLElement> | undefined; } & BaseButtonProps & Omit<...> & { ...; } & Omit<...>> & { ...; }; }' is not assignable to type 'IntrinsicAttributes & EditProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & EditProps'.
`

Show
`
Type '{ children: Element[]; isLoading: boolean; }' is not assignable to type 'IntrinsicAttributes & ShowProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ShowProps'.
`

I use 

    "@pankod/refine-antd": "^3.27.0",
    "@pankod/refine-core": "^3.36.0",
    "@pankod/refine-react-router-v6": "^3.25.2",
    "@pankod/refine-simple-rest": "^3.25.6",
    "@pankod/refine-strapi-graphql": "^3.25.8",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.41",
    "@types/react": "^18.0.14",
    "@types/react-dom": "^18.0.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us. A similar issue has been opened before, can you check here for details?
- https://github.com/pankod/refine/issues/1839#issuecomment-1138177075

**Comment by emehmet** [comment]
When I downgrade to React In 17.0.2, this time I am getting error in code. 
`import ReactDOM from 'react-dom/client';` in index.tsx
React is being imported with its latest version

create-react-app installs the code accordingly. 
This detail should be explained in the documents until the transition to React@18

**Comment by omeraplak** [comment]
Thank you, we will publish our react@18 support soon.

for now, it may be easiest to use `superplate-cli`
