### ISSUE TITLE
[FEAT] Implement GraphQL subscriptions data provider

### ISSUE THREAD

**Issue by zion-zadik** [pankod/refine#2091]
Hi,
Would be great to have an example of a data provider for GraphQL (and Hasura) subscriptions for live data updates

**Comment by omeraplak** [comment]
Hey @zion-zadik ,
Thank you for contacting us! Let's see what we can do ⚡

**Comment by salihozdemir** [comment]
Hey @zion-zadik 

I started working on your suggestion. When I create a PR, I link the PR here. 🎉

**Comment by omeraplak** [comment]
Hey @zion-zadik ,
We've released `@pankod/refine-core@3.42.0`. You can find how you can enable it in our Hasura example -> https://github.com/pankod/refine/blob/next/examples/dataProvider/hasura/src/App.tsx#L23
