### ISSUE TITLE
[DOC] How to get the URLs for record actions?

### ISSUE THREAD

**Issue by KrishnaPG** [pankod/refine#2094]
In the examples, there is a way to add action buttons such as `show`, `edit` etc. using
````
            <ShowButton
              size="small"
              recordItemId={record.CIF_NO}
              hideText={true}
            />
````

Is there a way to get the URLs for those actions (e.g. show, edit etc.) without rendering the button?

For example, I have an ID column in the table that I want to make as clickable content. i.e. if the user clicks on the ID number on the row, it should open the `show` view for that row record - how to do that (without manually patching up URLs)?
````
        <Table.Column
          dataIndex="CIF_NO"
          title="ID"
          render={(value) => <a href={?????}>{value}</a>}
        />
````

**Comment by KrishnaPG** [comment]
Thank you @omeraplak 

`show("posts", 1);` is expecting the resource name. Is there anyway to get the current page's resource name programmatically without having to type it explicitly (the way `useShow` gets it)?

If there is a way to get the current page's resource, I can pass on that to the `show` method.

**Comment by omeraplak** [comment]
Hmm maybe you can use with ["useResource()"](https://refine.dev/docs/core/hooks/resource/useResource/) hook. Would that make sense to you?

**Comment by KrishnaPG** [comment]
Using the `useResource` on the list page is causing additional re-renders when switching to `show` view. Not a usable solution.

Anyway, I am hardcoding the resource names for the `show` call. That's fine, I guess. But is there any similar hook for dataProviderName for https://github.com/pankod/refine/issues/2096 ?

**Comment by omeraplak** [comment]
The `useNavigation` hook can use the current resource by default. How is this for you? 

I haven't had a chance to talk about #2096 with the core team yet, we will update you during the day

**Comment by KrishnaPG** [comment]
On the `list` page I have added `useNavigation` as below:

```
const { show } = useNavigation();
  const { tableProps, sorter } = useTable();


      <Table {...tableProps} rowKey="CIF_NO">
        <Table.Column
          dataIndex="CIF_NO"
          render={(value) => (
            <Button type="link"  onClick={() => show("cif", value)}>
              {value}
            </Button>
          )}
        />
```

However, this is causing a re-render when show button is clicked (due to the `useNavigation` hook revaluation).

**Comment by omeraplak** [comment]
This was not the behavior we expected. I tried but I couldn't reproduce it, am I missing something?

CodeSandbox;
https://codesandbox.io/s/hh10yn
