### ISSUE TITLE
[BUG] Change default action after submit Create request ?

### ISSUE THREAD

**Issue by vnStrawHat** [pankod/refine#2123]
Hi,

I just update **refine** and seen default action after submit **Create** request was changed.
**Old**:
1. **Create** Post
2. Save
3. UI redirect to **List** Post

**New**:
1. **Create** Post
2. Submit
3. UI redirect to **Edit** Post

All examples in refine.dev has **New** behavior. https://refine.dev/docs/examples/form/antd/useForm/

How can I change this behavior ?

**Comment by omeraplak** [comment]
Hey @vnStrawHat 👋,
Thank you for contacting us. You can change it with the "redirect" property of useForm.

By the way, sorry for this situation, We didn't want that to change, we'll look into the matter.

**Comment by omeraplak** [comment]
Hey @vnStrawHat ,
We've released [`@pankod/refine-core@3.44.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-core%403.44.0). Could you approve this fix?

**Comment by vnStrawHat** [comment]
Hi @omeraplak,

Sorry for not getting back to you sooner. This fix look good to me.

Thanks.

**Comment by Kkkassini** [comment]
The List view has already active syncWithLocation, but after clicking save in Edit view, the page still jumps to the default state in List view
