### ISSUE TITLE
[BUG] Filters using OR comparator are not correctly merged

### ISSUE THREAD

**Issue by tynan-cr** [pankod/refine#2124]
**Describe the bug**

**To Reproduce**
1. Return filter array with top level OR filter from `onSearch` when using `useTable` (setFilterBehavior should be 'merge')
2. Note that each time the filter is changed it is appended to filter array passed to `DataProvider` (instead of replacing existing)

**Expected behavior**
Changing this filter and returning from `onSearch` should replace the filter when passed down to `DataProvider` through `useTable` internals

**Comment by aliemir** [comment]
Thanks for the issue 🙏 This can be resolved if #2130 is resolved but still this is an issue with `merge` not handling `or` filters. We will handle this separately but probably #2130 will be resolved sooner as a quick workaround for this issue.

**Comment by omeraplak** [comment]
Hey @tynan-cr ,
We've released [`@pankod/refine-core@3.44.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-core%403.44.0). Could you approve this fix?

**Comment by tynan-cr** [comment]
Fix confirmed! Thank you. And #2130 is also fixed.
