### ISSUE TITLE
[BUG] Appwrite 0.15 not working

### ISSUE THREAD

**Issue by rospisey** [pankod/refine#2132]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**

**Comment by omeraplak** [comment]
Hey @rospisey ,
Thank you for contacting us! We'll try it with Appwrite@0.15 and let you know!

**Comment by omeraplak** [comment]
Hey @rospisey ,
Can you share some more details about the error?

**Comment by rospisey** [comment]
Hello @omeraplak 
Appwrite error with auth_provider and data_provider with package @pankod/refine-appwrite. You can just change these function to support new appwrite version. Appwrite V0.15 has new database.

**Comment by omeraplak** [comment]
Hey @rospisey ,
We've updated our Appwrite API to 0.15 and it's working as an expected. How can we reproduce the issue?

Example: https://refine.dev/docs/examples/data-provider/appwrite/
Multi-tenancy example: https://refine.dev/docs/examples/multi-tenancy/appwrite/
