### ISSUE TITLE
[BUG] Some menu errors. it doesn't automatically close the submenu

### ISSUE THREAD

**Issue by luuquangtrung98** [pankod/refine#2148]
1. **Some menu errors. It doesn't automatically close the submenu**
_(here is the video link describing error )_
[https://drive.google.com/file/d/15V1KUGj7McCwqyOTI4pZ1HgucvyNDNdJ/view?usp=sharing]

----------------------------------
2. **I tried using antd's library to render the menu and didn't get above error**
(here is link codesandbox using antd's library, didn't get above error, you can go to link and copy *item in file data_menu.json
(extract file data_menu.zip)). 
[data_menu.zip](https://github.com/pankod/refine/files/9138192/data_menu.zip)

[https://codesandbox.io/s/vertical-menu-antd-4-21-7-forked-wzwxcj?file=/demo.js]

Thanks,
Quang Trung

**Comment by omeraplak** [comment]
Hey @luuquangtrung98 ,
Thank you for contacting us! We've tried your menu.json and works as expected. Did you customize Sider? If you have customized it, can you share your Sider with us?

https://user-images.githubusercontent.com/1110414/179743298-f2fc6980-17a3-4158-88b8-c8665ca075c9.mov

**Comment by luuquangtrung98** [comment]
Hey @omeraplak ,
you can see my videos, see my mouse movements. your mouse operation is different from mine . I'm not customize Sider. thanks

**Comment by omeraplak** [comment]
Sorry. Is it possible to share the Refine version you added `menu.json` on StackBlitz? Unfortunately, I cannot reproduce the problem. I'm sure I'm missing something. Many thanks for your interest and patience! 🏄‍♂️

**Comment by luuquangtrung98** [comment]
sorry for the long reply.  I found a way to fix the error.
when i changed it to the 2nd way of writing the code, the submenu error didn't happen.
you can see the attached picture.

Thanks!


![aaaa](https://user-images.githubusercontent.com/35988009/181156964-7727530e-0470-41c2-9c5c-6a7f314491bc.png)
