### ISSUE TITLE
[FEAT] Optional "sort" and "where" props in graphql dataPrivder

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2189]
Hi,

In Graphql dataProvider, pagination is optional with hasPagination props. Is it possible to add optional usage props for "where" and "sort"?

**Comment by salihozdemir** [comment]
Hi @emehmet,

Thank you for contact us

**Comment by salihozdemir** [comment]
Hi @emehmet,

Thank you for contact us :tada: 

Could you explain in detail why you needed such a feature? Is it because you can't sort and filter on the client side or are there other reasons?

**Comment by emehmet** [comment]
Hi @salihozdemir,

Thank you for your comment!

I have a graphql server that I have already used. I don't want to make changes to the queries here. 
Because it is used by other projects. 
I get message: "Unknown argument sort on field Query" error because Graphql server does not contain sort or where in my queries.

**Comment by salihozdemir** [comment]
We will discuss for find a solution with team. As soon as possible i will inform you about this.

**Comment by salihozdemir** [comment]
Hi @emehmet,

We think, you can override `dataProvider` like that:
https://refine.dev/docs/faq/#how-i-can-override-specific-function-of-data-providers

I hope it helps.

**Comment by emehmet** [comment]
Hi @salihozdemir,

I will try. Thanks for your effort.
