### ISSUE TITLE
.gitignore in examples/

### ISSUE THREAD

**Issue by vibl** [pankod/refine#2195]
You might want to add a .gitignore inside each example (for people who open them individually as projects in VSCode).

Also maybe add `examples/**/node_modules` in the root .gitignore (for people who open just the root directory but `npm i` inside each example).

BTW, what's the purpose of the `/*/` in the line `examples/**/*/package-lock.json`?

**Comment by aliemir** [comment]
Thank you for the issue! Opened a PR and added `.gitignore` to all examples, good point! That extra `/*/` had no purpose really, so I removed it 😅
