### ISSUE TITLE
[BUG] Logout issue.

### ISSUE THREAD

**Issue by Thirumalai62** [pankod/refine#2211]
Describe the bug:
When I am trying to logout the app. It passes the url with login & query params as resources name: For example, i will attach the
screenshot eg.., **/login?to=%2Fposts**  . Even though I am trying to pass the custom url it routes with same route name **/login?to=%2Fposts**

When Logged In:
![image](https://user-images.githubusercontent.com/80027472/180834292-9a2699d7-a156-4969-96a9-c045bbcdbf50.png)

When Logged Out:
I have passed the 
 logout: () => {
        localStorage.removeItem(TOKEN_KEY);
        return Promise.resolve("/");
    },
but it routes as i mentioned below:
![image](https://user-images.githubusercontent.com/80027472/180834543-948786b4-da75-477a-b592-3b81186f1a06.png)

After Passing the custom url:
 logout: () => {
        localStorage.removeItem(TOKEN_KEY);
        return Promise.resolve("/custom-login");
    },
 after logged out:
![image](https://user-images.githubusercontent.com/80027472/180834913-206d2569-4285-4929-9d05-e7415b9a7289.png)

**Expected behavior**
The expected behavior when we are trying to pass the /custom-login. It should render this page <CustomLogin />

**Desktop (please complete the following information):**
 - OS: Windows OS
 - Browser [chrome,]
 - Used dataProvider [REST API]

**Comment by omeraplak** [comment]
Hey @Thirumalai62 ,
We've released [`@pankod/refine-core@3.48.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-core%403.48.0) and [`@pankod/refine-react-router-v6@3.27.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-react-router-v6%403.27.0). Could you approve this fix?

**Comment by Thirumalai62** [comment]
> Hey @Thirumalai62 , We've released [`@pankod/refine-core@3.48.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-core%403.48.0) and [`@pankod/refine-react-router-v6@3.27.0`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-react-router-v6%403.27.0). Could you approve this fix?

still having same issue...

**Comment by omeraplak** [comment]
Could you try update all refine dependencies?

**Comment by Thirumalai62** [comment]
> Could you try update all refine dependencies?

i updated the dependencies which you mentioned above.
![image](https://user-images.githubusercontent.com/80027472/181060052-2604943b-cd66-46ba-8075-962a8df66c1e.png)

**Comment by Thirumalai62** [comment]
yes this issue is fixed...!
