### ISSUE TITLE
[FEAT] Please make the PageHeader extra extensible

### ISSUE THREAD

**Issue by KrishnaPG** [pankod/refine#2246]
**Is your feature request related to a problem? Please describe.**
Currently the views such as `Show`, `Edit`, `Create`, `List` etc. offer default buttons in the PageHeader `extra`. This is good because these default buttons inherit many things such as `recordItemId`, `dataProviderName` etc from the parent view component and auto-configure themselves.

The problem is, when we need to add additional buttons **before** and **after** the default buttons. For example, in the `Show` view I already get a `RefreshButton` by default and would like to add a `Download` button before the built-in Refresh Button.

This requires me to rewrite everything in the PageHeader `extra` (including all the configuration of `recordItemId`, `dataProviderName` etc required for the built-in buttons).

There is no way to just **prepend** and **append** few buttons to the already existing built-in buttons.

**Describe the solution you'd like**

- Kindly allow extra ReactNode contents to be **prepended** and **appended** to the built-in Page Header components (instead of overwriting them)

For example, 
- Should be able to add few `ReactNode`s  **before** the built-in `extra` components and **after** the built-in `extra` components in the `PageHeader`

**Comment by aliemir** [comment]
Hey @KrishnaPG, thank you for the issue! I think this will be a nice feature 🚀 We're currently working on a refactor in UI framework integrations and added couple of props to do changes in action buttons at the header and the footer of the crud elements like `headerButtons` and `footerButtons`, which are `actionButtons` currently. We'll also update `headerButtons` and footerButtons` like the following; 

**Type**

```ts
type headerButtons = ({ defaultButtons }: { defaultButtons: React.ReactNode }) => React.ReactNode;
type footerButtons = ({ defaultButtons }: { defaultButtons: React.ReactNode }) => React.ReactNode;
```

**Usage**

```tsx
<List
    headerButtons={({defaultButtons}) => (
        <>
          <MyButton />
          {defaultButtons}
          <OtherButton />
        </>
    )}
```

This will allow developers to prepend/append elements to the current buttons. Hope you like this approach, we're aiming to release this as soon as possible.

**Comment by KrishnaPG** [comment]
Thank you @aliemir Yes, that seems like would solve the purpose.

**Comment by KrishnaPG** [comment]
Also, may be you have already considered it, but thought of sharing it just in case:

- Please make these default buttons each of them controllable individually, without having to rewrite much code or touch the other components. 
 
For example, we should be able to hide or show the `RefreshButton` (without affecting the other default buttons). Currently, in the `Show` view there is no way to just hide only the `RefreshButton` without rewriting the whole other components in the `extra`

![image](https://user-images.githubusercontent.com/4610831/181875500-dedfce84-5881-4f50-9ace-7adb9eeff177.png)

**Comment by KrishnaPG** [comment]
Also, please allow customizing the text or icon of these default buttons each independently (without having to touch the other buttons).

For example, in the `Show` view we would like use the text `Finalize` for the button instead of `Edit` (only for this specific view, and not everywhere, as per the business context). Currently there is no way to just change the button text or icon without having to rewrite the whole button.

And also would like to supply tool tips for these buttons with custom text / message, which is not possible.

![image](https://user-images.githubusercontent.com/4610831/181875713-d55cea89-a536-465f-bc01-045d98b3435c.png)

I guess each of these default buttons should have a props param that is to be passed for the parent container (`Show`, `Edit` etc.), which can then be passed directly to the buttons, something like
````
Show({
 listButtonProps={}, 
 editButtonProps={}, 
 refreshButtonProps={}, 
 ...otherParams} = {}) {

   //... other code as usual

    <ListButton
        data-testid="show-list-button"
        resourceNameOrRouteName={resource.route}
        {...listButtonProps}
    />

    <EditButton
        disabled={isLoading}
        data-testid="show-edit-button"
        resourceNameOrRouteName={resource.route}
        recordItemId={id}
        {...editButtonProps}
    />

      <RefreshButton
          resourceNameOrRouteName={resource.route}
          recordItemId={id}
          {...refreshButtonProps}
      />
}
````
This sounds laborious, but grants maximum flexibility to the user.

**Comment by aliemir** [comment]
Hey @KrishnaPG, we're releasing the changes to `next` channel today including the feature mentioned here https://github.com/pankod/refine/issues/2246#issuecomment-1198974638

Currently, we don't offer modifications on the default buttons but there's an on-going internal discussion on how to achieve this, there are multiple ideas on implementation of those. We'll announce the decision and place it on the roadmap as soon as possible. Thank you for your patience.
