### ISSUE TITLE
[DOC] Webpack Polyfills querystring

### ISSUE THREAD

**Issue by alphonso06** [pankod/refine#2265]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
Data Providers, specifically the [getMany section.](https://refine.dev/docs/core/providers/data-provider/#getmany)

**Describe the thing to improve**
Causes this error on compile:
```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
    - add a fallback 'resolve.fallback: { "querystring": require.resolve("querystring-es3") }'
    - install 'querystring-es3'
If you don't want to include a polyfill, you can use an empty module like this:
    resolve.fallback: { "querystring": false }
```

**Describe the solution (optional)**
I typically use Vite for all my front-end related development. So I'm not exactly sure what those are, but it would be nice to follow the documentation without any friction. Maybe an up-to-date snippet of code or extended explanation on what to do with webpack causing problems.

**Comment by omeraplak** [comment]
Hey @alphonso06 ,
Thank you for contacting us. We originally wanted to point to the [query-string](https://www.npmjs.com/package/query-string) package, but we forgot about it in our documentation. I've added it now, how does this look for you?

https://github.com/pankod/refine/pull/2266
