### ISSUE TITLE
[BUG] Browser back navigation broken with syncWithLocation and paginated useTable

### ISSUE THREAD

**Issue by MBecherKurz** [pankod/refine#2276]
**Describe the bug**
Using 'syncWithLocation' within a paginated table breaks the browser back navigation. It gets stuck and reloads the same page over and over. 

Reason for that is propbably, that after loading the previos page refine adds the query parameters back to the URL. By pressing the back button the next time, the browser reloads the same page without the query parmeters -> query parameters are added  again -> and so on...

**To Reproduce**
1. Go to https://example.admin.refine.dev/products
2. Use the bottom navigation to switch between pages
3. Use the browser back button

**Expected behavior**
The browser loads the previous page (still product page but the the previous pagination page).

**Video**
https://user-images.githubusercontent.com/106522540/182851274-aedb6259-408a-454a-9075-dac2bf12ee98.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome & Edge
 - Version: 3.23.0
 - Used dataProvider: useTable

**Additional context**

**Comment by omeraplak** [comment]
Hey @MBecherKurz 👋,
Thank you for contacting us! Let's see what we can do!

**Comment by omeraplak** [comment]
We've created #2279. We will release it soon!

**Comment by omeraplak** [comment]
Hey @MBecherKurz 👋,
We've released @pankod/refine-core@3.56.4. Could you approve this fix?

**Comment by MBecherKurz** [comment]
Sorry for the late reply. I've just updated my project and can confirm the fix :)
