### ISSUE TITLE
[DOC] Web3 example fails on initialization

### ISSUE THREAD

**Issue by btargac** [pankod/refine#2309]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
Sign-In with Ethereum example fails on initialization.
https://refine.dev/docs/examples/web3/web3Login/

**Describe the thing to improve**
Example does not work as expected.

**Describe the solution (optional)**
Module not found: Error: Can't resolve 'stream' in '/home/projects/xoriygyzy.github/node_modules/cipher-base' might help checking some missing dependencies or import maps.

**Comment by omeraplak** [comment]
Hey @btargac ,
Thank you for contacting us! Let's see what we can do 💥

**Comment by omeraplak** [comment]
Hey @btargac ,
We've fixed this issue! 🚀
