### ISSUE TITLE
[BUG] Google Auth example outdated

### ISSUE THREAD

**Issue by icybergenome** [pankod/refine#2355]
We are trying to build an admin panel using Refine. For the authentication we choose Google OAuth but the popup for Google Authentication is so random. Sometimes it shows up other times it doesn't. We used the skeleton code that is provided by refine cli.

**To Reproduce**
1. Setup refine boilerplate: `npx superplate-cli -p refine-react .`
2. Used settings as follow:
```
✔ Package manager: · yarn
✔ Do you want to use a UI Framework?: · antd
✔ Do you want a customized theme?: · antd-css
✔ Router Provider: · react-location
✔ Data Provider: · data-provider-hasura
✔ Auth Provider: · auth-provider-google
✔ Do you want a customized layout? · no
✔ Do you want to add Kbar command palette: · no
✔ i18n - Internationalization: · no
✔ Would you like to share your choices with us anonymously? · yes

```
3. Setup Google OAuth and whitelist the domain

**Expected behavior**
Google Authentication should work fine. 

**Actual Behavior**
* Popup is so random, sometimes it appears other times `Sign in`  does nothing.
* Errors in console.

**Screenshots**
<img width="667" alt="image" src="https://user-images.githubusercontent.com/12095716/186374756-77355384-0923-4e27-b12b-59181163e92c.png">
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/12095716/186375329-b0361636-f768-4f97-9149-d0099414fb5f.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Firefox, Safari
 - Used dataProvider: Hasura

**Additional context**
On response to my discord comment I am creating this issue.
https://discord.com/channels/837692625737613362/896336798429642785/1011902038822617099

**Comment by ozkalai** [comment]
hey @icybergenome 👋, Sorry to hear that you are having a problem with Google Auth, thanks for the issue. We will update it with the new Google Identity Service to eliminate the problem you have and also notify you of updates. 🎉

**Comment by ozkalai** [comment]
@icybergenome, We have updated our Google Auth example with the new Google Identity Service, you can check out all updates in the example [link.](https://refine.dev/docs/examples/auth-provider/google-auth/) We are also planning to fix in `superplate` at the beginning of next week.
