### ISSUE TITLE
[FEAT] Add an option to hide the resource in the menu

### ISSUE THREAD

**Issue by aliemir** [pankod/refine#2388]
**Is your feature request related to a problem? Please describe.**

Currently, users need to customize the `<Sider />` components to hide resources from their menu. We should support a way in our `useMenu` hook at `@pankod/refine-core` to let users hide resources in the menu. 

**Describe the solution you'd like**

A field on `options` property of the resources.

```tsx
<Refine
    resources={[
        {
            name: "posts",
            options: {
                visible: false, // or hide: true
            }
        }
    ]}
/>
```

**Comment by omeraplak** [comment]
Hey @aliemir  ,
We've released `@pankod/refine-core@3.64.0`. Could you approve this feature?

```tsx
    <Refine
        ...
        ...
        resources={[
            {
                name: "posts",
                list: PostList,
                options: {
                    hide: true,
                },
            },
        ]}
    />
```
