### ISSUE TITLE
[FEAT] Add the ability to export the filtered data from a table to .csv with useExport(), rather than the whole resource

### ISSUE THREAD

**Issue by BenGardiner123** [pankod/refine#2393]
**Is your feature request related to a problem? Please describe.**
Currently you can;t export only the filtered data from a table

**Describe the solution you'd like**
Add the ability for either the current filters from onSearch to be passed to the export, or the filtered table data 

**Describe alternatives you've considered**
I can write my own csv reader / writer but i think this would be pretty useful for the wider community

**Additional context**

**Comment by omeraplak** [comment]
Hey @BenGardiner123 ,
Thank you for contacting us! After discussing it with the team, this approach did not seem right. Relying on server-state for CSV export seems like the best way 💥
