### ISSUE TITLE
[BUG] useStepsForm Mutation does not return result

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2462]
**Describe the bug**
The form successfully passes the data to the server, but returns no results. I see the result data is coming on chrome network but there is no MutationResult.

**Expected behavior**
Return data in onMutationSuccess when the mutation completes successfully

```
"@pankod/refine-antd": "^3.41.0",
"@pankod/refine-core": "^3.69.0",
```

**Additional context**
```javascript

import {
  useStepsForm
} from '@pankod/refine-antd';

  const {
    current,
    gotoStep,
    stepsProps,
    formProps,
    saveButtonProps,
    form,
    queryResult: qs,
    mutationResult,
    formResult,
  } = useStepsForm<{ createReport: ReportResult }>({
    isBackValidate: false,
    metaData: {
      fields: ['id'],
    },
    onMutationSuccess: (data) => {
      console.log('🚀 ~ file: list.tsx ~ line 82 ~ data', data);
    },
  });
```

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us! Let's see what we can do 💥

**Comment by emehmet** [comment]
Also here it doesn't work when I give a specific name to the resource. The resource name is automatically given as createReport.

**Comment by aliemir** [comment]
Hey @emehmet, tried to create a reproduction here https://stackblitz.com/edit/pankod-refine-fpag82?file=src%2Fpages%2Fposts%2Fedit.tsx&preset=node but couldn't. I was able to get the data in `onMutationSuccess` and `mutationResult`. For `mutationResult` you probably need to set `redirect:false` to be able to use the values after the mutation is settled. 

The resource and id issue is probably related to #2467 and will be fixed after it ships.

Can you please check the example I shared above and maybe try to get a minimal reproduction?
