### ISSUE TITLE
[BUG] useTable Refresh button resets resource name

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2508]
**Describe the bug**
I enter a specific resource for useTable. It sends a query with success. But when I press the reset button, it does not remember the resource I entered. It uses the default resource.

**Expected behavior**
useTable should use the resource name when it was first created.

```
"@pankod/refine-antd": "^3.41.0",
"@pankod/refine-core": "^3.69.2",

```

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us! Can you share a StackBlitz where we can reproduce this issue? You can get a fork here,
https://refine.dev/docs/examples/table/antd/useTable/

**Comment by emehmet** [comment]
Hi @omeraplak,
I use useTable on show page. And Table is wrapped with Show tag. You can see on StackBlitz.
https://stackblitz.com/edit/pankod-refine-1hy2nx?file=src/pages/posts/list.tsx

Refresh button comes with Show tag. I guess that's my problem. I can write the resource name in Show's resource. But I also need to write metaData.

I did not use the Show page to show a single record detail. Show page is a table showing the result from the filters collected on the previous list page.  I didn't share it all in the example but this is what I did.

If I want to do something other than CRUD operations, I'm sorry for not understanding how I can do it yet. Your Read part only exists to query a record. This is Show. The list section is the first page by default. I'm sorry I may have misunderstood.

Best regards.

**Comment by omeraplak** [comment]
Hey @emehmet ,
I'm not sure I understand correctly but are you looking for something like this?

https://stackblitz.com/edit/pankod-refine-zhdzfw?file=src%2Fpages%2Fposts%2Flist.tsx

**Comment by emehmet** [comment]
Hi @omeraplak ,

Yes, this works for me. Thank you. 👍
