### ISSUE TITLE
[BUG] Casbin example not working

### ISSUE THREAD

**Issue by polly3d** [pankod/refine#2514]
**Describe the bug**
Casbin is not working when flowing from the example.

**To Reproduce**
Just flowing from the document: https://refine.dev/docs/guides-and-concepts/access-control/#casbin
1. install casbin
2. write access control provider

The [node-casbin](https://github.com/casbin/node-casbin) is just for the backend, not the fronted. So there're errors when webpack building.

**Comment by salihozdemir** [comment]
Hey @polly3d,
Thank you for information. As soon as possible we'll update the casbin example. Right now we are very busy, we would be very happy if you would like to open a PR and contribute to us  🚀

**Comment by amit-ksh** [comment]
I would like to work on this issues. Can you assign this issue to me?

**Comment by salihozdemir** [comment]
> I would like to work on this issues. Can you assign this issue to me?

We'll look forward to your contribution 🚀

**Comment by amit-ksh** [comment]
Hey @salihozdemir! I fixed all the errors raised by webpack in Refine Casbin Example app.

What I have done - 

1) Upgraded the webpack to the latest version i.e. 5.0.1
     - **Reason**: webpack 4 does not support the nullish coalescing and optional chaining
1) Uses the react-app-rewired package for overriding the webpack config to support polyfills.
     - **Reason**: app created using `create-react-app` does not support the webpack overriding and for that, we need [react-app-rewired](https://www.npmjs.com/package/react-app-rewired)
     
Here is the updated app - [site](https://stackblitz.com/edit/pankod-refine-bmukwm)

**Comment by salihozdemir** [comment]
Hey @amit-ksh, 
First, sorry for my late response I missed the notification. 
Great job! 🎉  We can't wait to merge. Could you want to open a PR?

**Comment by amit-ksh** [comment]
I wanted to confirm that I have to make changes in the docs right?

**Comment by amit-ksh** [comment]
OK! I'll try to create PR as soon as possible.

**Comment by omeraplak** [comment]
Thank you @amit-ksh 🎁
