### ISSUE TITLE
[DOC] Headless tutorial code causes error when trying to import icons

### ISSUE THREAD

**Issue by vijayganeshpk** [pankod/refine#2575]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
https://refine.dev/docs/tutorials/headless-tutorial/#adding-resources

**Describe the thing to improve**
After setting up tutorial as instructed (`npx superplate-cli -o refine-headless tutorial`), when trying to use icons as in the tutorial code
```javascript
import { PostIcon } from "icons";
```
I am getting error:
`Cannot find module 'icons' or its corresponding type declarations.ts(2307)`

Please note I did not execute `npm i @pankod/refine-simple-rest` as I had used `superplate` to bootstrap the project.

My system info:
MacOS `v12.6`
node `v16.17.0` 
nvm `v8.15.0`

From `package.json`:

```json
"dependencies": {
    "@pankod/refine-core": "^3.18.0",
    "@pankod/refine-react-router-v6": "^3.18.0",
    "@pankod/refine-react-table": "^4.7.2",
    "@pankod/refine-simple-rest": "^3.18.0",
    "@testing-library/jest-dom": "^5.12.0",
    "@testing-library/react": "^11.2.6",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.23",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^5.0.0",
    "web-vitals": "^1.1.1"
  },
  "devDependencies": {
    "@types/node": "^12.20.10",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "autoprefixer": "^10.4.12",
    "postcss": "^8.4.16",
    "tailwindcss": "^3.1.8",
    "typescript": "^4.7.4"
  },
```

**Describe the solution (optional)**
Update tutorial with missing package, maybe?

**Comment by salihozdemir** [comment]
Hey @vijayganeshpk,

The tutorial assumes your project is configured for absolute imports. So you should configure a [tsconfig.json](https://www.typescriptlang.org/tsconfig#baseUrl) with `baseUrl` setting pointing to the /src directory in your project.

You may not be able to see the `PostIcon` in the document because it is collapsable. Actually, `import { PostIcon } from "icons"` under src points to a `icons.ts` file like the one below:

```tsx
export const PostIcon = (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="20"
        height="20"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
    >
        <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
        <polyline points="2 17 12 22 22 17"></polyline>
        <polyline points="2 12 12 17 22 12"></polyline>
    </svg>
);
```

**Comment by aliemir** [comment]
Hey @vijayganeshpk, thank you for your feedback. We're sorry to hear that you had a problem while following the tutorial. @salihozdemir shared the content for the file and `npx superplate-cli -o refine-headless tutorial` comes with `basePath` set to `src` already but I have to admit, `Show PostIcon` section is really easy to skip when you are following the tutorial so I added a bit more contrast and an explanation to avoid users missing out this section. 

Opened a PR for this [here](https://github.com/pankod/refine/pull/2576)

**Comment by vijayganeshpk** [comment]
@salihozdemir / @aliemir thank you. 

Sorry, my bad!

I missed it due to not looking properly at the `Show PostIcon` expansion box. Maybe I assumed it was a sample data from server, similar to the previous `Show response` section.
