### ISSUE TITLE
[BUG] When integrating with Antd, time picker returns time with date

### ISSUE THREAD

**Issue by hisunnymay** [pankod/refine#2581]
**Describe the bug**
When using [time picker](https://ant.design/components/time-picker/#header) from Ant Design, the value of `form.item` is a timestamp which includes time and date. Therefore, when we try to update the value to the database, we get an error : "_invalid input syntax for type time_".

**To Reproduce**
1. Refer to [antd example](https://github.com/pankod/refine/blob/next/examples/tutorial/antd/src/pages/posts/edit.tsx), replace `<Form.Item>...</Form.Item>` with following codes
```
<Form.Item
   label="Test"
   name="test"
   rules={[
           {
              required: true,
            },
   ]}
>
   <TimePicker size="large" />
</Form.Item>
```
2. Input time using time picker
3. Click "Save"
5. See the value get from time picker is `"2022-09-26T06:00:00.000Z\"` instead of `"06:00:00"`

**Expected behavior**
When we use time picker, we want to get only the time without date so we can update the value to the databse.

**Screenshots**
![image](https://user-images.githubusercontent.com/95261974/192269374-8ddc5c10-f44c-4c24-ae3e-7273edfb9f7a.png)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [refine-antd: "3.41.0"]
 - Used dataProvider [custom]

**Smartphone (please complete the following information):**
 null

**Additional context**
 null

**Comment by vinclou** [comment]
Not a maintainer, but I don't think it's a bug per say, AntD handles lots of "magic" for you. Refer to the 
[Timepicker docs](https://ant.design/components/time-picker/#header)

If you need a string and not MomentJs, they use DayJs under the hood in case of refine.

You would do something like this:

```tsx
const onChange = (time: Moment, timeString: string) => {
  console.log(time, timeString);
 // time string is the value you need
 // grab it and set it to whatever data model u want
};

const Example: React.FC = () => (
  <TimePicker onChange={onChange} defaultOpenValue={moment('00:00:00', 'HH:mm:ss')} />
);
```

So I would in your place write the custom onChange/onSelect handler to get the logic I wanted.

`Memo: Refine uses DayJs, so you probably need this as your peer dep or direct dep, if you want to manipulate/work more with the dates`

**Comment by hisunnymay** [comment]
Thank you, it sounds like a good idea. We will give it a try. :)
