### ISSUE TITLE
[BUG] useMenu hook is not reacting to locale change

### ISSUE THREAD

**Issue by spatialvlad** [pankod/refine#2598]
`useMenu` hook is not changing content when language is changed.

Ways to reproduce: try switching the language of samples with several languages and observe items in the sider. E.g. here: https://stackblitz.com/edit/pankod-refine-4u7qf4

Likely it is a result of not having a dependency on locale/language in useMemo when building `treeMenuItems`  here: https://github.com/pankod/refine/blob/next/packages/core/src/hooks/menu/useMenu.tsx#L75

**Comment by omeraplak** [comment]
Hey @spatialvlad 👋,
Thank you for contacting us! Want to create a PR? 🚀

**Comment by spatialvlad** [comment]
@omeraplak , the code to fix it should be small, but I'm extremely busy next ~5 days to run/test the code. If nobody fixes it, I'll make a PR in ~5 days.

**Comment by omeraplak** [comment]
Hey @spatialvlad ,
We've released [`@pankod/refine-core@3.74.4`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-core%403.74.4). Could you approve fix?

**Comment by spatialvlad** [comment]
@omeraplak , thanks for the quick fix. I did a quick check and can confirm that the issue is fixed.

Thanks for the great framework and the hard work you do!
