### ISSUE TITLE
[FEAT] Returned data structure from useTable

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2602]
**Is your feature request related to a problem? Please describe.**
useTable has an array as a result data. I want to return an object. Because columns will be ready and get from server in one query.  Also can be need another things. The current structure is not very flexible. The generic type entered assumes you refer to continuous data and returning an array.

It seems to apply to all the list hooks I've described here.

**Describe the solution you'd like**
Data can be expected in type all the time, but it should be allowed to define fields that the user wants outside of data.

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us! The `select` function of `queryOptions` may be useful for you.

```tsx
    const table = useTable({
        queryOptions: {
            select: (data) => {
                // manipulate your data
                return data;
            },
        },
    });
```

**Comment by emehmet** [comment]
Hey @omeraplak ,

Typescript interface is as follows;

```js
export interface GetListResponse<TData = BaseRecord> {
    data: TData[];
    total: number;
}
```

```js
select?: ((data: GetListResponse<BaseRecord>) => GetListResponse<BaseRecord>)
```

I can't manipulate it because Typescript is fixed directly to data.

**Comment by omeraplak** [comment]
or you can directly use dataSource property of Table component.
```tsx
const { tableQueryResult, tableProps } = useTable();

// manipulate your data
const newData = tableQueryResult.data;
<Table {...tableProps} dataSource={newData} />
```
