### ISSUE TITLE
[BUG] Wrong total value of Graphql dataProvider getList 

### ISSUE THREAD

**Issue by emehmet** [pankod/refine#2603]
**Describe the bug**
total value is undefined. Because count is used instead of length.

https://github.com/pankod/refine/blob/next/packages/graphql/src/dataProvider/index.ts

```js
    return {
      data: response[operation],
      total: response[operation].count,
    };
```

**Comment by omeraplak** [comment]
Hey @emehmet ,
Thank you for contacting us! The `@pankod/refine-graphql` package is configured to run when the `count` property is set in the response. If this is not suitable for your API, you can override it.

https://refine.dev/docs/faq/#how-i-can-override-specific-function-of-data-providers
