### ISSUE TITLE
[FEAT] Allow passing custom queryClient instance

### ISSUE THREAD

**Issue by jsbrain** [pankod/refine#2665]
It's currently not possible to pass a queryClient to refine.

This make invalidating queries from outside react context really hard as this can currently only be done using the `useInvalidate` hook.

Passing your own queryClient would allow sharing the queryClient instance with other parts of the application, even other frameworks.

**Comment by salihozdemir** [comment]
Hey @jsbrain,

Yes you cannot pass the queryClient, but you can configure queryClient like this: 
https://refine.dev/docs/api-reference/core/components/refine-config/#reactquery. 
Also, If you need to use queryClient you can get current queryClient instance like this: https://tanstack.com/query/v4/docs/reference/useQueryClient

**Comment by jsbrain** [comment]
@salihozdemir yes, that's what I just said. I know the hook can be used to receive the query client. But it's a react hook, which means it can only be used inside react.

There are times you'd want to access the queryClient outside of react.

I don't think allowing to pass the client would be hard to achieve. It could still be merged with the existing options.

**Comment by aliemir** [comment]
Hey @jsbrain, it makes sense to have the option to pass `queryClient` and then you can have the necessary flexibility to access it from outside of React. We added this to our todo list and prioritized. We're aiming to release it with the next minor version (probably today or tomorrow)

**Comment by alicanerdurmaz** [comment]
Hi @jsbrain, we implement this feature and released [@pankod/refine-core@3.78.0](https://github.com/pankod/refine/releases/tag/%40pankod/refine-core%403.78.0)

Thank you for opening the issue 🙏

**Comment by rayphilip141** [comment]
Hey 👋

**Comment by jsbrain** [comment]
Amazing, that really helps a ton! Thank you 🥳
