### ISSUE TITLE
[DOC] Wording is confusing for advanced-tutorials/ssr/remix.md

### ISSUE THREAD

**Issue by malixsys** [pankod/refine#2671]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
[Remix SSR Doc](https://github.com/pankod/refine/blob/master/documentation/docs/advanced-tutorials/ssr/remix.md)

**Describe the thing to improve**
Refine wraps Outlet and not vice versa

**Describe the solution (optional)**
Reword the doc

**Comment by malixsys** [comment]
https://github.com/pankod/refine/pull/2672

**Comment by omeraplak** [comment]
Thank you! 🎁
