### ISSUE TITLE
over lapping of content of navbar

### ISSUE THREAD

**Issue by AbhishekTiwari23** [pankod/refine#2676]
**Describe the bug**
I found that Github, store and version are overlapping over each other. You can figure it out through this attachment.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Google chrome on MAC
2. Click on refine website/ tutorial page or hacktoberfest page
4. See the error on the navbar of the page.

**Expected behaviour**
There should be no overlapping of the content on the page.

**Screenshots**

<img width="1440" alt="Screenshot 2022-10-08 at 2 43 53 AM" src="https://user-images.githubusercontent.com/97469132/194654894-d5f1cf22-d9cb-4a4c-9ddb-91aa16261641.png">

**Desktop (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Device: Mac Air
 - OS: Mac os
 - Browser google chrome
 - Version latest
 - Used dataProvider Excitel

**Additional context**

**Comment by AbhishekTiwari23** [comment]
And please guide me for some UI/UX-based issues if available. I want to contribute to this project. Thanks

**Comment by omeraplak** [comment]
Hey @AbhishekTiwari23 ,
Thank you! If you want to try to fix the issue, you can review our contributing document 🚀
https://refine.dev/docs/contributing/#starting-documentation-in-watch-mode

**Comment by AbhishekTiwari23** [comment]
> Hey @AbhishekTiwari23 , Thank you! If you want to try to fix the issue, you can review our contributing document 🚀 https://refine.dev/docs/contributing/#starting-documentation-in-watch-mode

Thanks @omeraplak, I will make a pr as soon as possible

**Comment by CyberGeni** [comment]
hi @omeraplak is there anyone working on this? i want to work on it. if no one, please assign me

**Comment by aliemir** [comment]
Hey @CyberGeni, @AbhishekTiwari23 showed interest to work on this issue but if they are not going to work on it, you can get this one. Let's ask @AbhishekTiwari23 about it; what's the progress on this issue, can we expect a PR soon or do you want to leave it to the @CyberGeni ?

**Comment by aliemir** [comment]
Thank you for the clarification @AbhishekTiwari23, closing this issue for now, maybe we can re-visit the layout of Navbar in the future

**Comment by AbhishekTiwari23** [comment]
> Thank you for the clarification @AbhishekTiwari23, closing this issue for now, maybe we can re-visit the layout of Navbar in the future

Thanks, sir, if there is any UI UX issue, please let me know, hover effect or anything. I am ready to serve the community
