### ISSUE TITLE
Issue on the home page

### ISSUE THREAD

**Issue by AbhishekTiwari23** [pankod/refine#2677]
**Describe the bug**
I am not clear whether it is a bug or not, but it looks not good to me as most of the content is behind the navbar, which is not readable properly
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Refine home page
3. View on the top just below the navbar.
4. See the error

**Expected behaviour**
<img width="1440" alt="Screenshot 2022-10-08 at 1 43 01 PM" src="https://user-images.githubusercontent.com/97469132/194697503-9a74801f-6f69-4554-b9de-deff0d1563b2.png">

**Screenshots**
<img width="1440" alt="Screenshot 2022-10-08 at 1 38 31 PM" src="https://user-images.githubusercontent.com/97469132/194697498-9f1408dc-2432-4c15-b34d-b591ee4114c1.png">

**Desktop (please complete the following information):**
 - OS: Mac Os
 - Browser Google chrome
 - Version latest
 - Used dataProvider Excitel

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**
If this is a genuine issue, please let me know so I can contribute to this fabulous project.

**Comment by vcvedika** [comment]
Can I work on this issue if it hasn't been assigned yet?
