### ISSUE TITLE
[DOC] Typo and odd phrase in landing page

### ISSUE THREAD

**Issue by Manethpak** [pankod/refine#2681]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
Typo on footer and odd phrase in landing page
( Joining hacktober )

**Describe the thing to improve**
- Typo in footer "whereever"
![image](https://user-images.githubusercontent.com/58499300/194773721-405f2de7-6827-45d2-bf66-e65cde94d7a7.png)

- The phrase "Come to dark side" is oddly phrase with grammatical mistake. 
![image](https://user-images.githubusercontent.com/58499300/194773837-99789acb-e873-4cdf-a6a9-cb801c22695f.png)

**Describe the solution (optional)**
- Fix "whereever" to "wherever"
- Change the phrase "Come to dark side" to "Join the dark side" instead. I tried to change it to "Come to the dark side" but it a bit too long for the container in desktop view.

*Edited 1
While I'm at it I also update the README in documentation to match the [contributing](https://refine.dev/docs/contributing/) page. The old documentation use yarn as the command instead of npm.

**Comment by Alcadeus0** [comment]
hi, can i fix this?
