### ISSUE TITLE
[BUG] useSelect Ignores fetchSize

### ISSUE THREAD

**Issue by vinclou** [pankod/refine#2692]
### Discussed in https://github.com/pankod/refine/discussions/2691

<div type='discussions-op-text'>

<sup>Originally posted by **vinclou** October 10, 2022</sup>
### Deps:

    `"@pankod/refine-antd": "^3.53.0",`
    `"@pankod/refine-core": "^3.78.0",`

### Example:

```tsx
	const { selectProps: someDataSelectProps } = useSelect<SomeData>({
		resource: 'someResource',
		fetchSize: 5,
		optionValue: 'id',
		optionLabel: 'displayName',
		queryOptions: {
			enabled: true,
			staleTime: Timer.FifteenMinutes
		}
	})
```

This will get you the correct data back, but in the network tab you will see 2 queries being made one `without params` and another one with correct pageSize params which are -> `pageSize: 5`

ex:
```js
Req One: SomeData
Req Two: SomeData/page=0&pageSize=5
```

I'm a bit confused about why is there a fetchSize option if it fetches all data on initial render that exists anyway?

Clarification: If you use useList, with overridden pagination, it will work and make expected 1 query only
```tsx
	const res = useList<SomeData>({
		resource: 'someResource',
		config: {
			pagination: {
				current: 1,
				pageSize: 100
			},
			filters: [
				{
					field: 'sort',
					operator: 'eq',
					value: 'NameAsc'
				}
			]
		},
		queryOptions: {
			enabled: true,
			staleTime: Timer.Hour
		}
	})
```

</div>

**Comment by vinclou** [comment]
### I figured what's causing this:

`If u override queryOptions obj, the double fetch bug appears, removing it solves the problem`

Yet it is an issue, as metadata select is pretty much stale data that doesn't change quite often. A long staleTime on metaData queries is preferable.

```tsx
		queryOptions: {
			enabled: true,
			staleTime: Timer.Hour
		}
```

**Comment by alicanerdurmaz** [comment]
@vinclou Thank you for the issue 🙏 

We prioritized this bug and we will solve it as soon as possible.

**Comment by alicanerdurmaz** [comment]
@vinclou Hi again, we solved the problem. We will merge fix today. Thanks for the issue 🙏
