### ISSUE TITLE
[BUG] bug in the store search 

### ISSUE THREAD

**Issue by saimaheshtaduri** [pankod/refine#2694]
**Describe the bug**
whenever I searched for an item ( say **bottle** ), I am getting a weird answer.
![Screenshot (43)](https://user-images.githubusercontent.com/53844369/194932107-c6d5d0d5-f7a8-4ae0-81e3-cbc8ac2f7ba5.png)

**To Reproduce**
1. Go to 'https://store.refine.dev/'
2. type say **bottle** in search box
3. See error

**Expected behavior**
It just has to be number of results available or No results but not both.

**Comment by aliemir** [comment]
Hey @saimaheshtaduri, thank you for the issue! Looks like there's a problem with the conditional rendering of the result texts 😅 If you like to work on this issue, feel free to open a PR otherwise @sevkioruc is willing to work on this one 🚀

**Comment by aliemir** [comment]
> Hi everyone,
> Can i work on it?

Hey @sevkioruc thank you for your interest on this issue, we think it will be better to wait @saimaheshtaduri's action before assigning it to you, thank you for your patience. You can have the issue if @saimaheshtaduri wants to skip it.

**Comment by sevkioruc** [comment]
Hi @aliemir thank you for your comment. I am waiting for now :)
Good luck @saimaheshtaduri.

**Comment by saimaheshtaduri** [comment]
Yes, I would like to contribute. please assign the issue to me.

**Comment by omeraplak** [comment]
> Yes, I would like to contribute. please assign the issue to me. @aliemir

Happy hacking! 🧭

**Comment by aliemir** [comment]
Hey @saimaheshtaduri, what's the progress on this issue? Were you able to take a look at this? If you are not able to take this one maybe we can re-assign to someone else?

**Comment by saimaheshtaduri** [comment]
Yes.im working on it. Give me a day or two

**Comment by sevkioruc** [comment]
Hey @saimaheshtaduri,
If you stopped working on, can i work on this issue?

**Comment by aliemir** [comment]
@saimaheshtaduri we're trying to close issues as fast as possible and we consider this as a kinda important issue on the store. Sorry but we're assigning this issue to someone else 🙍‍♂️

**Comment by aliemir** [comment]
Hey @sevkioruc assigned the issue on you, waiting for your PR 🚀

**Comment by sevkioruc** [comment]
Thanks @aliemir. I will work on it soon. 🙏

**Comment by sevkioruc** [comment]
Hey @aliemir, could you please review it? (https://github.com/pankod/refine/pull/2811)
Thank you :)
