### ISSUE TITLE
[FEAT]Reorganizing Store Page

### ISSUE THREAD

**Issue by Smartmind12** [pankod/refine#2696]
**Is your feature request related to a problem? Please describe.**
Once you arrive at (https://store.refine.dev/) and scroll for products you can witness white black space next to the water bottle.

**Describe the solution you'd like**
Rearranging the layout of pictures on the Store page to make it look more streamligned and remove the white space.

![Screenshot 2022-10-11 at 8 47 41 AM](https://user-images.githubusercontent.com/91927689/194989598-cac3e5bf-0710-4d45-8df4-9a7dc804273e.png)

**Additional Information**
Kindly assign this issue to me as i would like to work on it !

**Comment by salihozdemir** [comment]
Hey @saimaheshtaduri thank you for the issue, It is not about the front-end side, we've forwarded the issue to the relevant teams. 👊🏻

**Comment by omeraplak** [comment]
Hey @Smartmind12 ,
We've fixed the issue! Thank you 💥
