### ISSUE TITLE
[FEAT]Add Announcement Bar 

### ISSUE THREAD

**Issue by Smartmind12** [pankod/refine#2698]
**Is your feature request related to a problem? Please describe.**
Currently there is no Announcement Bar feature in the Home Page (https://refine.dev/). This Feature is useful for all users coming to the landing page can be aware of announcements/alerts like.."Refine releasing version 3.x.x" or "Refine participating in Hacktoberfest"

**Describe the solution you'd like**
Addition of the announcement Bar to the Home Page (& other pages).

**Additional context**
Kindly assign this issue to me so that i can try to add this feature...Thanks!

**Comment by aliemir** [comment]
Hey @Smartmind12, we already have an announcement bar feature coming from the Docusaurus, there are no announcements now so you might have skipped it 😅 Thank you for the issue but closing this for now.
