### ISSUE TITLE
[BUG]Typo in the Footer

### ISSUE THREAD

**Issue by superiorsd10** [pankod/refine#2702]
**Describe the bug**
There is a typing mistake in the footer on the website. It should be `wherever` instead of `whereever`.

**To Reproduce**
1. Go to 'website'
2. Scroll down to the 'footer'
3. See typo

**Expected behavior**
The spelling should be corrected.

**Screenshots**
![SCR-20221011-jm6](https://user-images.githubusercontent.com/92971894/195041837-4c9cad01-45e5-41fe-bd7e-d73e6e7bf134.png)

**Desktop (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**
I would like to work on this issue. So please assign this issue to me. Thank you!

**Comment by omeraplak** [comment]
Hey @superiorsd10 ,
Thank you for reporting the issue! We've already fixed it and will release it soon!
