### ISSUE TITLE
[DOC] Grammatical Error in Readme File

### ISSUE THREAD

**Issue by harshagrawal523** [pankod/refine#2710]
**Is this issue related to an existing part of the documentation? If so, please provide a link**
The section can be accessed from [here](https://github.com/pankod/refine#what-do-you-mean-by-headless-)

**Describe the thing to improve**
There were a few grammatical and punctuation errors in the document. (Improved in the PR)

**Describe the solution (optional)**
Wholesome documentation provides a better reading experience for a first-time product user. Hence, I have changed a few words and punctuation to provide a better reading experience.

**Comment by harshagrawal523** [comment]
@aliemir Please review the [PR](https://github.com/pankod/refine/pull/2711) here. Thanks!

**Comment by aliemir** [comment]
Hey @harshagrawal523 thank you for the issue and the quick PR 🚀 Leaving a quick review to the PR now.

**Comment by harshagrawal523** [comment]
@aliemir How can we claim the Refine Swag Tshirt?
