### ISSUE TITLE
[BUG] startswithoperator not supported in hasura dataprovider

### ISSUE THREAD

**Issue by syed1RehanAhmed** [pankod/refine#2724]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**

**Comment by omeraplak** [comment]
Hey @syed1RehanAhmed ,
We've released `@pankod/refine-hasura@4.15.0` 💥
