### ISSUE TITLE
[FEAT]add hover effect the the footer links

### ISSUE THREAD

**Issue by ShravaniAK** [pankod/refine#2733]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShravaniAK** [comment]
please assign me this issue

**Comment by alicanerdurmaz** [comment]
@ShravaniAK Hi,

Hover effect already added to social links: [PR](https://github.com/pankod/refine/issues/2683)

Hover effect already have on navigation links.
![image](https://user-images.githubusercontent.com/23058882/195533530-da735d95-2467-48a0-a055-fea66d1d4058.png)

Which part for footer do you want to add an effect?

**Comment by ShravaniAK** [comment]
i will make the words bolder on hovering

**Comment by ShravaniAK** [comment]
now only an underline is there

**Comment by alicanerdurmaz** [comment]
Thank you for idea 🙏  but we think this is not fit our design language.
