### ISSUE TITLE
[BUG] unable to add nested filter to jsonb object in setFilters function in hasura data provider

### ISSUE THREAD

**Issue by syed1RehanAhmed** [pankod/refine#2735]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Smartphone (please complete the following information):**
 - Used dataProvider [e.g. custom, Strapi, Airtable]

**Additional context**

**Comment by salihozdemir** [comment]
Hey @syed1RehanAhmed,

It is not a bug, it is a feature request. If you want to this you should create a feature request issue with feature request template. Also, we have planned to change the our filter system. For now you can override the dataProvider as you want then you can use `metaData` and do whatever you want.
