### ISSUE TITLE
[BUG]on opening the cart and after that login page the cross option to close the cart is not present.

### ISSUE THREAD

**Issue by ShravaniAK** [pankod/refine#2738]
<img width="1440" alt="Screenshot 2022-10-13 at 1 30 12 PM" src="https://user-images.githubusercontent.com/97099574/195537775-5e168f17-717a-42d1-b7f0-860c1dca5453.png">

**Comment by aliemir** [comment]
Hey @ShravaniAK, I think there's a bit confusion 😅 When you open the cart, it opens a drawer; when you click on the user to log in, it opens a modal and closes the drawer. When you close the modal, you end up with the product detail page without the drawer. They look alike so might be the cause of the confusion but there's no bug here 😅 Please reach out if you have any more issues 🙏
