### ISSUE TITLE
[BUG] Login and sign in text on button can only be seen when hovered in refine store

### ISSUE THREAD

**Issue by s-vamshi** [pankod/refine#2744]
**Describe the bug**
Login text on button in  login model is not visible until hovered.
Sign In text on button in sign in model is not visible until hovered.

**To Reproduce**

1. Go to https://store.refine.dev/
2. Click on login button
3. Below password field there is a login button but the text is not visible until hovered.
4. Same happens with sign in button in signin model

**Expected behavior**
Login text and sign in  should be visible to the user.

**Screenshots**
**Login model**
![n5](https://user-images.githubusercontent.com/62489114/195560707-2eeabd2a-698f-46d0-87c5-d7bf3d8796e8.PNG)
![Screenshot (437)](https://user-images.githubusercontent.com/62489114/195562071-b9ef8682-5dc0-4bca-b495-50d02e453c2d.png)

**Sign in model**
![Screenshot (465)](https://user-images.githubusercontent.com/62489114/195561792-b05986fd-83a3-4d6d-9f33-2093499391d1.png)

![Screenshot (466)](https://user-images.githubusercontent.com/62489114/195561917-e0500fb7-4b1d-4ea3-9c11-dbe1147a9558.png)

**Comment by s-vamshi** [comment]
@aliemir I would like to work on this issue. Can you please assign this to me?

**Comment by omeraplak** [comment]
> @aliemir I would like to work on this issue. Can you please assign this to me?

Hey @s-vamshi ,
I did. Happy hacking!

**Comment by s-vamshi** [comment]
@omeraplak Thanks for assigning this to me. Will this issues PR count towards hacktoberfest?
