### ISSUE TITLE
[FEAT] Update issue template

### ISSUE THREAD

**Issue by Manethpak** [pankod/refine#2753]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to any problem of the project functionality nor documentation. I'm making this request to update the project current issue template to GitHub new [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). This will able contributors to create issues much quicker and easier. 

**Describe the solution you'd like**
I have already written the new form issue for this project and to have the exact same field and tested it. I will make a pull request on this issue, please see below screenshots for how the new issue template will looks. 
Also this is for Hacktoberfest 😄 

**Additional Content**

- Issue page
![Screenshot 2022-10-13 at 20-36-07 New Issue · Manethpak_test-issue-form](https://user-images.githubusercontent.com/58499300/195613934-12e7c8e7-aae6-4ee0-ae01-eb71c100286e.png)

- Bug report page
![Screenshot 2022-10-13 at 20-35-27 New Issue · Manethpak_test-issue-form](https://user-images.githubusercontent.com/58499300/195614468-91320d74-1ff6-4ba8-ba32-8ea90dd13725.png)

- Documentation report page
![Screenshot 2022-10-13 at 20-35-41 New Issue · Manethpak_test-issue-form](https://user-images.githubusercontent.com/58499300/195615231-d9c3adb6-531d-449c-ae55-8b7768aa0631.png)

- Feature request page
![Screenshot 2022-10-13 at 20-48-33 New Issue · Manethpak_test-issue-form](https://user-images.githubusercontent.com/58499300/195614994-624ac7af-cb6a-49aa-972f-8738b82ad286.png)

**Comment by omeraplak** [comment]
Wow looks so cool! Thank you 🎉
