### ISSUE TITLE
[BUG] Invalid Link in Readme

### ISSUE THREAD

**Issue by kailashchoudhary11** [pankod/refine#2759]
### Describe the bug

the contributor covenant link is redirecting to 404 page not found.

### Steps To Reproduce

Go to Readme File and click on Contributor Covenant link

### Expected behavior

it should redirect to a valid Contributor Covenant Page.

**Comment by kailashchoudhary11** [comment]
@omeraplak If the bug seems valid to you I would like to fix it!

**Comment by omeraplak** [comment]
Hey @kailashchoudhary11 ,
I couldn't find this link on README but you can create a PR
