### ISSUE TITLE
[BUG] Fix eslint warnings on whole examples

### ISSUE THREAD

**Issue by salihozdemir** [pankod/refine#2765]
### Describe the bug

All examples has a known eslint warning like following:

```tsx
const container = document.getElementById("root");
const root = createRoot(container!); // this line throw null-assertion warning
```

It can be solved like this:

```tsx
const container = document.getElementById("root");
// eslint-disable-next-line
const root = createRoot(container!); // this line throw null-assertion warning
```

Also, some variables, types or functions are declared but not using.

### Steps To Reproduce

1. `npm run bootstrap`
2. `npm run bootstrap -- --scope "example-name"`
3. `npm run start -- --scope "example-name"`
4. Shows eslint warnings and errors in the terminal.

### Expected behavior

The examples run with no lint warnings or errors.

**Comment by sevkioruc** [comment]
Hey @salihozdemir,
If it is available, I'd like to work on.

**Comment by sevkioruc** [comment]
thank you so much! 😅 @salihozdemir.

**Comment by amit-ksh** [comment]
Hey @sevkioruc! can you add the `examples/` in the `.eslintignore` file in the project's root directory? This will ignore the eslint checks in the `examples/` folder and probably fixes the issue. 

Also could you please replace all the lines in the casbin example `.eslintignore` file with 
```
*
```

And sorry for these issues, I should first check all the changes before creating the PR.

**Comment by sevkioruc** [comment]
Hey @amit-ksh , thank you for your comment.
But this way isn't it the same thing as a project without eslint?

**Comment by amit-ksh** [comment]
Ya! You are right. There should be a better way of handling these warnings.

**Comment by sevkioruc** [comment]
I see but why are there eslint packages and configs in projects? It is not clear for me :)
I think we had better ask it to anyone in core team.
What do you think about it? :) @salihozdemir

**Comment by salihozdemir** [comment]
The main reason for using the eslint is because every developer has her style of writing (like naming conventions/tabs/single or double quotes for a string). With different styling techniques, your codebase may look weird, more error-prone and vulnerable.  For these reasons we don't want to ignore eslint.

Thanks @sevkioruc for helping us to maintain the code standard. 🚀

**Comment by sevkioruc** [comment]
Thanks for your explanation @salihozdemir :)
