### ISSUE TITLE
[BUG] Mantine AuthPage hooks incorrect

### ISSUE THREAD

**Issue by dgelineau** [pankod/refine#2768]
### Describe the bug

The AuthPage exported by refine-mantine is calling the useLogin() hook for the Register, ForgotPassword, and UpdatePassword instead of their respective hooks exported from the core library. As a result; filling out the form and submitting on any of these pages will result in the login function being called in the authProvider.

### Steps To Reproduce

1. Go to any of the pages (Register, ForgotPassword, UpdatePassword) using the refine-mantine library
2. Fill out the form and submit
3. The login() function in authProvider will be called instead of the expected function

### Expected behavior

Expecting the correct functions inside of the authProvider to be called onSubmit (Register should call register, etc...)

### Screenshot

https://github.com/pankod/refine/blob/2d50ce85e2907a8c2345ad26da150ad324ac544c/packages/mantine/src/components/pages/auth/components/forgotPassword/index.tsx#L64-L65

https://github.com/pankod/refine/blob/2d50ce85e2907a8c2345ad26da150ad324ac544c/packages/mantine/src/components/pages/auth/components/register/index.tsx#L63

https://github.com/pankod/refine/blob/2d50ce85e2907a8c2345ad26da150ad324ac544c/packages/mantine/src/components/pages/auth/components/updatePassword/index.tsx#L61-L62

**Comment by omeraplak** [comment]
Hey @dgelineau ,
Thank you for reporting issue. Anyone want to do? 👀
