### ISSUE TITLE
[FEAT] Add i18n to pages/ready to match other components

### ISSUE THREAD

**Issue by jerempy** [pankod/refine#2770]
### Is your feature request related to a problem? Please describe.

There is a missing `useTranslate` hook in the pages.ready component at: [](https://github.com/pankod/refine/blob/next/packages/core/src/components/pages/ready/index.tsx)

All of the other componets in `/src/components/pages/pages` make use of the translate feature so I would like to add it there.

### Describe alternatives you've considered

Leaving it as it is without i18n

### Additional context

I would be happy to open a PR on this. I got a fix ready to go if you can assign this issue to me

### Describe the thing to improve

uniformity of use of translation in these pages components.

**Comment by omeraplak** [comment]
Hey @jerempy ,
Thank you for contacting us! Is there a real use case for the ready page? A welcome screen only when the empty refine project is opened

**Comment by jerempy** [comment]
Hey there @omeraplak its just something I noticed since all the components in this folder use translate but this one doesn’t for some reason.  If you think it’s unimportant feel free to close the issue
