### ISSUE TITLE
[DOC] Improve react-hook-form-validation.md

### ISSUE THREAD

**Issue by kaustav202** [pankod/refine#2773]
### Documentation issue

The [react-hook-form-validation.md](https://github.com/pankod/refine/blob/next/documentation/blog/2022-09-27-react-hook-form-validation.md) under blogs has a few typos and grammatical  errors

### Describe the thing to improve

Fix the errors in the blog

**Comment by kaustav202** [comment]
I'd like to solve this

**Comment by omeraplak** [comment]
> I'd like to solve this

Happy hacking 🚀

**Comment by BhaskarKarnatak** [comment]
I would like to work on this. It is possible for you to assign me this issue.

**Comment by omeraplak** [comment]
Thank you @kaustav202 🚀
