### ISSUE TITLE
Pagination for useTable hooks

### ISSUE THREAD

**Issue by markuz899** [pankod/refine#2802]
### Describe the bug

Hi,
is it possible to use parameters in the custom query string for pagination in useTable hooks?

### Steps To Reproduce

useTable
setPageSize(20)
setPage(2)

### Expected behavior

url: enooint_api/product?page=2&pageSize=20

**Comment by salihozdemir** [comment]
Hey @markuz899,

You can use the 'syncWithLocation' property od the 'useTable' for using the sync your params with the URL. Please, check it out the [useTable](https://refine.dev/docs/api-reference/core/hooks/useTable/#properties) documentation.

**Comment by markuz899** [comment]
thanks for the quick reply, but in doing so the call to the server will still have the default values
_end = 20 & _start = 10

**Comment by markuz899** [comment]
Overriding the getList method of the data provider helped me override the queries for pagination, by implementing the Pagination component I integrated it all

thanks for the support

good work
